"use strict";

import Creature from "../creature.js";

export function all(): Creature[] {
  let behaviors = ["cautious", "hunting", "lethargic", "resting", "sleeping", "stalking"];

  let creatures = [
    new Creature("ape", "apes", "", [], ["forest"], behaviors, ["beast"], ["simian"], 1),
    new Creature(
      "axe beak",
      "axe beaks",
      "",
      [],
      ["grassland", "hill"],
      behaviors,
      ["beast"],
      [],
      1,
    ),
    new Creature(
      "baboon",
      "baboons",
      "",
      [],
      ["forest", "hill"],
      behaviors,
      ["beast"],
      ["monkey"],
      1,
    ),
    new Creature("badger", "badgers", "", [], ["forest"], behaviors, ["beast"], [], 1),
    new Creature("bat", "bats", "", [], ["cave"], behaviors, ["beast"], ["flying"], 1),
    new Creature(
      "black bear",
      "black bears",
      "",
      [],
      ["forest"],
      behaviors,
      ["beast"],
      ["bear"],
      1,
    ),
    new Creature("blink dog", "blink dogs", "", [], ["forest"], behaviors, ["fey"], ["canine"], 1),
    new Creature(
      "boar",
      "boars",
      "",
      [],
      ["forest", "grassland", "hill"],
      behaviors,
      ["beast"],
      ["boar"],
      1,
    ),
    new Creature(
      "brown bear",
      "brown bears",
      "",
      [],
      ["arctic", "forest", "hill"],
      behaviors,
      ["beast"],
      ["bear"],
      1,
    ),
    new Creature("camel", "camels", "", [], ["desert"], behaviors, ["beast"], ["camel"], 1),
    new Creature(
      "cat",
      "cats",
      "",
      [],
      ["desert", "forest", "grassland", "hill"],
      behaviors,
      ["beast"],
      ["cat"],
      1,
    ),
    new Creature(
      "cave bear",
      "cave bears",
      "",
      [],
      ["forest", "hill"],
      behaviors,
      ["beast"],
      ["bear"],
      3,
    ),
    new Creature(
      "constrictor snake",
      "constrictor snakes",
      "",
      [],
      ["desert", "forest", "swamp", "underwater"],
      behaviors,
      ["beast"],
      ["snake"],
      1,
    ),
    new Creature(
      "crocodile",
      "crocodiles",
      "",
      [],
      ["swamp"],
      behaviors,
      ["beast"],
      ["reptile"],
      1,
    ),
    new Creature(
      "dire bat",
      "dire bats",
      "",
      [],
      ["forest"],
      behaviors,
      ["beast"],
      ["bat", "flying"],
      2,
    ),
    new Creature(
      "dire bear",
      "dire bears",
      "",
      [],
      ["forest", "hill"],
      behaviors,
      ["beast"],
      ["bear"],
      2,
    ),
    new Creature(
      "dire wolf",
      "dire wolves",
      "",
      [],
      ["forest"],
      behaviors,
      ["beast"],
      ["canine", "wolf"],
      2,
    ),
    new Creature(
      "elk",
      "elks",
      "",
      [],
      ["forest", "grassland", "hill"],
      behaviors,
      ["beast"],
      [],
      1,
    ),
    new Creature(
      "flying snake",
      "flying snakes",
      "",
      [],
      ["forest", "grassland", "hill", "urban"],
      behaviors,
      ["beast"],
      ["snake"],
      1,
    ),
    new Creature(
      "giant bat",
      "giant bats",
      "",
      [],
      ["forest", "underdark"],
      behaviors,
      ["beast"],
      ["bat", "flying"],
      2,
    ),
    new Creature(
      "giant rat",
      "giant rats",
      "",
      [],
      ["forest", "urban", "underdark"],
      behaviors,
      ["beast"],
      ["rat"],
      1,
    ),
    new Creature(
      "goat",
      "goats",
      "",
      [],
      ["forest", "grassland", "hill", "mountain"],
      behaviors,
      ["beast"],
      ["goat"],
      1,
    ),
    new Creature(
      "great eagle",
      "great eagles",
      "",
      [],
      ["forest", "hill", "mountain"],
      behaviors,
      ["beast"],
      ["eagle", "bird", "flying"],
      3,
    ),
    new Creature("horse", "horses", "", [], ["grassland"], behaviors, ["beast"], ["horse"], 1),
    new Creature("jaguar", "jaguars", "", [], ["forest"], behaviors, ["beast"], ["feline"], 1),
    new Creature(
      "lion",
      "lions",
      "",
      [],
      ["desert", "forest"],
      behaviors,
      ["beast"],
      ["feline"],
      1,
    ),
    new Creature(
      "stirge",
      "stirges",
      "",
      ["drain blood"],
      [
        "coastal",
        "desert",
        "forest",
        "grassland",
        "hill",
        "mountain",
        "swamp",
        "underdark",
        "urban",
      ],
      behaviors,
      ["beast"],
      [],
      1,
    ),
    new Creature("tiger", "tigers", "", [], ["forest"], behaviors, ["beast"], ["feline"], 2),
    new Creature(
      "war dog",
      "war dogs",
      "",
      [],
      ["forest", "grassland", "hill", "mountain", "underdark", "urban"],
      behaviors,
      ["beast"],
      ["canine", "dog", "martial"],
      1,
    ),
    new Creature("wild pig", "wild pigs", "", [], ["forest"], behaviors, ["beast"], ["pig"], 1),
    new Creature("wolf", "wolves", "", [], ["forest"], behaviors, ["beast"], ["canine", "wolf"], 1),
  ];

  for (let i = 0; i < creatures.length; i++) {
    creatures[i].tags.push(creatures[i].name);
    creatures[i].tags.push("animal");
  }

  return creatures;
}
