import type { FoodComponent } from './component.js';

export function all(): FoodComponent[] {
  const result: FoodComponent[] = [];
  return result.concat(spices(), herbs(), vegetables(), meats(), seafood(), fruits());
}

export function spices(): FoodComponent[] {
  return [
    {
      name: 'black pepper',
      flavors: ['spicy'],
      textures: [''],
      colors: ['black'],
      category: 'spice',
    },
    {
      name: 'chili powder',
      flavors: ['spicy'],
      textures: [''],
      colors: ['red'],
      category: 'spice',
    },
    { name: 'cinnamon', flavors: ['sweet'], textures: [''], colors: ['brown'], category: 'spice' },
    { name: 'cloves', flavors: ['sweet'], textures: [''], colors: ['brown'], category: 'spice' },
    {
      name: 'coriander',
      flavors: ['bitter'],
      textures: [''],
      colors: ['green'],
      category: 'spice',
    },
    { name: 'cumin', flavors: ['bitter'], textures: [''], colors: ['brown'], category: 'spice' },
    { name: 'fennel', flavors: ['sweet'], textures: [''], colors: ['green'], category: 'spice' },
    { name: 'ginger', flavors: ['sweet'], textures: [''], colors: ['brown'], category: 'spice' },
    { name: 'mustard', flavors: ['bitter'], textures: [''], colors: ['yellow'], category: 'spice' },
    { name: 'nutmeg', flavors: ['sweet'], textures: [''], colors: ['brown'], category: 'spice' },
    { name: 'paprika', flavors: ['sweet'], textures: [''], colors: ['red'], category: 'spice' },
    { name: 'salt', flavors: ['salty'], textures: [''], colors: ['white'], category: 'spice' },
    {
      name: 'turmeric',
      flavors: ['bitter'],
      textures: [''],
      colors: ['yellow'],
      category: 'spice',
    },
    {
      name: 'white pepper',
      flavors: ['spicy'],
      textures: [''],
      colors: ['white'],
      category: 'spice',
    },
  ];
}

export function fruits(): FoodComponent[] {
  return [
    {
      name: 'apple',
      flavors: ['sweet'],
      textures: ['crunchy'],
      colors: ['red', 'green', 'yellow'],
      category: 'fruit',
    },
    {
      name: 'banana',
      flavors: ['sweet'],
      textures: ['soft'],
      colors: ['yellow'],
      category: 'fruit',
    },
    {
      name: 'blackberry',
      flavors: ['sweet'],
      textures: ['soft'],
      colors: ['black'],
      category: 'fruit',
    },
    {
      name: 'blueberry',
      flavors: ['sweet'],
      textures: ['soft'],
      colors: ['blue'],
      category: 'fruit',
    },
    {
      name: 'dragonfruit',
      flavors: ['mild'],
      textures: ['crunchy'],
      colors: ['pink', 'yellow'],
      category: 'fruit',
    },
    {
      name: 'grape',
      flavors: ['sweet'],
      textures: ['soft'],
      colors: ['purple', 'green', 'red'],
      category: 'fruit',
    },
    {
      name: 'grapefruit',
      flavors: ['tart'],
      textures: ['crunchy'],
      colors: ['pink'],
      category: 'fruit',
    },
    {
      name: 'guava',
      flavors: ['tart'],
      textures: ['crunchy'],
      colors: ['green'],
      category: 'fruit',
    },
    { name: 'kiwi', flavors: ['tart'], textures: ['soft'], colors: ['brown'], category: 'fruit' },
    {
      name: 'lemon',
      flavors: ['sour'],
      textures: ['crunchy'],
      colors: ['yellow'],
      category: 'fruit',
    },
    {
      name: 'lime',
      flavors: ['tart'],
      textures: ['crunchy'],
      colors: ['green'],
      category: 'fruit',
    },
    { name: 'lychee', flavors: ['sweet'], textures: ['soft'], colors: ['red'], category: 'fruit' },
    {
      name: 'mango',
      flavors: ['sweet'],
      textures: ['soft'],
      colors: ['orange'],
      category: 'fruit',
    },
    {
      name: 'orange',
      flavors: ['tart'],
      textures: ['crunchy'],
      colors: ['orange'],
      category: 'fruit',
    },
    {
      name: 'papaya',
      flavors: ['sweet'],
      textures: ['soft'],
      colors: ['orange'],
      category: 'fruit',
    },
    {
      name: 'pineapple',
      flavors: ['sweet'],
      textures: ['crunchy'],
      colors: ['brown', 'yellow'],
      category: 'fruit',
    },
    {
      name: 'raspberry',
      flavors: ['sweet'],
      textures: ['soft'],
      colors: ['red'],
      category: 'fruit',
    },
    {
      name: 'strawberry',
      flavors: ['sweet'],
      textures: ['soft'],
      colors: ['red'],
      category: 'fruit',
    },
    {
      name: 'watermelon',
      flavors: ['sweet'],
      textures: ['crunchy'],
      colors: ['green', 'red'],
      category: 'fruit',
    },
  ];
}

export function herbs(): FoodComponent[] {
  return [
    {
      name: 'basil',
      flavors: ['sweet'],
      textures: ['aromatic'],
      colors: ['green'],
      category: 'herb',
    },
    {
      name: 'bay leaves',
      flavors: ['bitter'],
      textures: ['aromatic'],
      colors: ['green'],
      category: 'herb',
    },
    {
      name: 'chives',
      flavors: ['sweet'],
      textures: ['aromatic'],
      colors: ['green'],
      category: 'herb',
    },
    {
      name: 'cilantro',
      flavors: ['bitter'],
      textures: ['aromatic'],
      colors: ['green'],
      category: 'herb',
    },
    {
      name: 'coriander',
      flavors: ['bitter'],
      textures: ['aromatic'],
      colors: ['green'],
      category: 'herb',
    },
    {
      name: 'dill',
      flavors: ['bitter'],
      textures: ['aromatic'],
      colors: ['green'],
      category: 'herb',
    },
    {
      name: 'fennel',
      flavors: ['sweet'],
      textures: ['aromatic'],
      colors: ['green'],
      category: 'herb',
    },
    {
      name: 'holy basil',
      flavors: ['sweet'],
      textures: ['aromatic'],
      colors: ['green'],
      category: 'herb',
    },
    {
      name: 'lavender',
      flavors: ['sweet'],
      textures: ['aromatic'],
      colors: ['purple'],
      category: 'herb',
    },
    {
      name: 'lemon balm',
      flavors: ['sweet'],
      textures: ['aromatic'],
      colors: ['green'],
      category: 'herb',
    },
    {
      name: 'lemongrass',
      flavors: ['sour'],
      textures: ['aromatic'],
      colors: ['green'],
      category: 'herb',
    },
    {
      name: 'marjoram',
      flavors: ['bitter'],
      textures: ['aromatic'],
      colors: ['green'],
      category: 'herb',
    },
    {
      name: 'mint',
      flavors: ['sweet'],
      textures: ['aromatic'],
      colors: ['green'],
      category: 'herb',
    },
    {
      name: 'oregano',
      flavors: ['bitter'],
      textures: ['aromatic'],
      colors: ['green'],
      category: 'herb',
    },
    {
      name: 'parsley',
      flavors: ['bitter'],
      textures: ['aromatic'],
      colors: ['green'],
      category: 'herb',
    },
    {
      name: 'rosemary',
      flavors: ['bitter'],
      textures: ['aromatic'],
      colors: ['green'],
      category: 'herb',
    },
    {
      name: 'sage',
      flavors: ['bitter'],
      textures: ['aromatic'],
      colors: ['green'],
      category: 'herb',
    },
    {
      name: 'tarragon',
      flavors: ['sweet'],
      textures: ['aromatic'],
      colors: ['green'],
      category: 'herb',
    },
    {
      name: 'thyme',
      flavors: ['sweet'],
      textures: ['aromatic'],
      colors: ['green'],
      category: 'herb',
    },
  ];
}

export function vegetables(): FoodComponent[] {
  return [
    {
      name: 'artichoke',
      flavors: ['nutty'],
      textures: ['soft'],
      colors: ['green'],
      category: 'vegetable',
    },
    {
      name: 'asparagus',
      flavors: ['nutty'],
      textures: ['crunchy'],
      colors: ['green'],
      category: 'vegetable',
    },
    {
      name: 'beetroot',
      flavors: ['earthy'],
      textures: ['crunchy'],
      colors: ['red'],
      category: 'vegetable',
    },
    {
      name: 'bell pepper',
      flavors: ['sweet'],
      textures: ['crunchy'],
      colors: ['green'],
      category: 'vegetable',
    },
    {
      name: 'broccoli',
      flavors: ['sour'],
      textures: ['crunchy'],
      colors: ['green'],
      category: 'vegetable',
    },
    {
      name: 'cabbage',
      flavors: ['sour'],
      textures: ['crunchy'],
      colors: ['green'],
      category: 'vegetable',
    },
    {
      name: 'carrot',
      flavors: ['sweet'],
      textures: ['crunchy'],
      colors: ['orange'],
      category: 'vegetable',
    },
    {
      name: 'cauliflower',
      flavors: ['mild'],
      textures: ['crunchy'],
      colors: ['white'],
      category: 'vegetable',
    },
    {
      name: 'celery',
      flavors: ['mild'],
      textures: ['crunchy'],
      colors: ['green'],
      category: 'vegetable',
    },
    {
      name: 'cucumber',
      flavors: ['sour'],
      textures: ['crunchy'],
      colors: ['green'],
      category: 'vegetable',
    },
    {
      name: 'eggplant',
      flavors: ['mild'],
      textures: ['soft'],
      colors: ['purple'],
      category: 'vegetable',
    },
    {
      name: 'kale',
      flavors: ['bitter'],
      textures: ['leafy'],
      colors: ['green'],
      category: 'vegetable',
    },
    {
      name: 'onion',
      flavors: ['sour'],
      textures: ['crunchy'],
      colors: ['white'],
      category: 'vegetable',
    },
    {
      name: 'potato',
      flavors: ['sweet'],
      textures: ['crunchy'],
      colors: ['brown'],
      category: 'vegetable',
    },
    {
      name: 'radish',
      flavors: ['spicy'],
      textures: ['crunchy'],
      colors: ['red'],
      category: 'vegetable',
    },
    {
      name: 'spinach',
      flavors: ['bitter'],
      textures: ['leafy'],
      colors: ['green'],
      category: 'vegetable',
    },
    {
      name: 'sweet potato',
      flavors: ['sweet'],
      textures: ['soft'],
      colors: ['orange'],
      category: 'vegetable',
    },
    {
      name: 'tomato',
      flavors: ['sour'],
      textures: ['crunchy'],
      colors: ['red'],
      category: 'vegetable',
    },
    {
      name: 'zucchini',
      flavors: ['mild'],
      textures: ['crunchy'],
      colors: ['green'],
      category: 'vegetable',
    },
  ];
}

export function meats(): FoodComponent[] {
  return [
    { name: 'beef', flavors: ['savory'], textures: ['tender'], colors: ['red'], category: 'meat' },
    {
      name: 'chicken',
      flavors: ['savory'],
      textures: ['tender'],
      colors: ['white'],
      category: 'meat',
    },
    {
      name: 'duck',
      flavors: ['savory'],
      textures: ['tender'],
      colors: ['brown'],
      category: 'meat',
    },
    { name: 'elk', flavors: ['savory'], textures: ['tender'], colors: ['red'], category: 'meat' },
    {
      name: 'goose',
      flavors: ['savory'],
      textures: ['tender'],
      colors: ['brown'],
      category: 'meat',
    },
    { name: 'lamb', flavors: ['savory'], textures: ['tender'], colors: ['red'], category: 'meat' },
    {
      name: 'moose',
      flavors: ['savory'],
      textures: ['tender'],
      colors: ['brown'],
      category: 'meat',
    },
    {
      name: 'pheasant',
      flavors: ['savory'],
      textures: ['tender'],
      colors: ['brown'],
      category: 'meat',
    },
    { name: 'pork', flavors: ['savory'], textures: ['tender'], colors: ['pink'], category: 'meat' },
    {
      name: 'quail',
      flavors: ['savory'],
      textures: ['tender'],
      colors: ['brown'],
      category: 'meat',
    },
    {
      name: 'rabbit',
      flavors: ['savory'],
      textures: ['tender'],
      colors: ['brown'],
      category: 'meat',
    },
    {
      name: 'turkey',
      flavors: ['savory'],
      textures: ['tender'],
      colors: ['white'],
      category: 'meat',
    },
    {
      name: 'venison',
      flavors: ['savory'],
      textures: ['tender'],
      colors: ['red'],
      category: 'meat',
    },
  ];
}

export function seafood(): FoodComponent[] {
  return [
    {
      name: 'anchovies',
      flavors: ['salty'],
      textures: ['soft'],
      colors: ['brown'],
      category: 'seafood',
    },
    {
      name: 'catfish',
      flavors: ['mild'],
      textures: ['firm'],
      colors: ['white'],
      category: 'seafood',
    },
    {
      name: 'clams',
      flavors: ['briny'],
      textures: ['chewy'],
      colors: ['white'],
      category: 'seafood',
    },
    { name: 'cod', flavors: ['mild'], textures: ['firm'], colors: ['white'], category: 'seafood' },
    { name: 'crab', flavors: ['sweet'], textures: ['soft'], colors: ['red'], category: 'seafood' },
    {
      name: 'halibut',
      flavors: ['mild'],
      textures: ['firm'],
      colors: ['white'],
      category: 'seafood',
    },
    {
      name: 'lobster',
      flavors: ['sweet'],
      textures: ['soft'],
      colors: ['red'],
      category: 'seafood',
    },
    {
      name: 'mussels',
      flavors: ['briny'],
      textures: ['chewy'],
      colors: ['black'],
      category: 'seafood',
    },
    {
      name: 'octopus',
      flavors: ['mild'],
      textures: ['chewy'],
      colors: ['white'],
      category: 'seafood',
    },
    {
      name: 'oysters',
      flavors: ['briny'],
      textures: ['chewy'],
      colors: ['gray'],
      category: 'seafood',
    },
    { name: 'perch', flavors: ['mild'], textures: ['firm'], colors: ['pink'], category: 'seafood' },
    {
      name: 'salmon',
      flavors: ['mild'],
      textures: ['soft', 'flaky'],
      colors: ['pink'],
      category: 'seafood',
    },
    {
      name: 'sardines',
      flavors: ['salty'],
      textures: ['soft'],
      colors: ['silver'],
      category: 'seafood',
    },
    {
      name: 'scallops',
      flavors: ['mild'],
      textures: ['soft', 'chewy'],
      colors: ['white'],
      category: 'seafood',
    },
    {
      name: 'shrimp',
      flavors: ['mild'],
      textures: ['soft', 'crunchy'],
      colors: ['pink'],
      category: 'seafood',
    },
    {
      name: 'squid',
      flavors: ['mild'],
      textures: ['chewy'],
      colors: ['white'],
      category: 'seafood',
    },
    { name: 'tuna', flavors: ['mild'], textures: ['firm'], colors: ['red'], category: 'seafood' },
  ];
}
