export function all() {
  return [
    {
      name: 'ale',
      strengthMin: 0,
      strengthMax: 3,
      costMin: 0,
      costMax: 2,
      appearances: ['yellow', 'tan', 'dark brown', 'brown'],
    },
    {
      name: 'beer',
      strengthMin: 0,
      strengthMax: 3,
      costMin: 0,
      costMax: 2,
      appearances: ['yellow', 'tan', 'dark brown', 'brown'],
    },
    {
      name: 'lager',
      strengthMin: 0,
      strengthMax: 3,
      costMin: 0,
      costMax: 2,
      appearances: ['yellow', 'tan', 'light brown', 'brown'],
    },
    {
      name: 'cider',
      strengthMin: 0,
      strengthMax: 3,
      costMin: 0,
      costMax: 3,
      appearances: ['yellow', 'tan', 'dark brown', 'brown', 'red', 'dull orange', 'pale'],
    },
    {
      name: 'wine',
      strengthMin: 0,
      strengthMax: 3,
      costMin: 0,
      costMax: 10,
      appearances: ['red', 'white', 'dark red', 'pale', 'burgundy'],
    },
    {
      name: 'whiskey',
      strengthMin: 1,
      strengthMax: 5,
      costMin: 0,
      costMax: 15,
      appearances: ['yellow', 'dark brown', 'brown', 'clear', 'caramel-colored'],
    },
    {
      name: 'brandy',
      strengthMin: 1,
      strengthMax: 5,
      costMin: 0,
      costMax: 10,
      appearances: ['cloudy', 'red', 'golden', 'caramel-colored'],
    },
    {
      name: 'bourbon',
      strengthMin: 1,
      strengthMax: 5,
      costMin: 0,
      costMax: 15,
      appearances: ['yellow', 'dark brown', 'brown', 'clear', 'caramel-colored'],
    },
    {
      name: 'gin',
      strengthMin: 1,
      strengthMax: 5,
      costMin: 0,
      costMax: 10,
      appearances: ['clear', 'cloudy', 'white'],
    },
  ];
}
