import { buildTrueDragonSpecies } from './dragon_species_helpers';

export default buildTrueDragonSpecies({
  breedType: 'amethyst_dragon',
  name: 'amethyst dragon',
  pluralName: 'amethyst dragons',
  adjective: 'amethyst draconic',
  family: 'gem',
  environments: ['hill', 'mountain', 'underdark'],
  physicalTraitGeneratorConfigs: [
    {
      name: 'scales',
      category: 'scales',
      options: [
        'amethyst crystal facet',
        'concord grape deep',
        'dream haze violet',
        'druzy glitter surface',
        'dusk lavender metal',
        'feldspar frost',
        'geode ringed',
        'iris shimmer',
        'phantom quartz inclusion',
        'royal purple bright',
        'spirit veil matte',
        'ultraviolet gleam',
      ],
      tags: ['scales'],
    },
    {
      name: 'horns',
      category: 'horns',
      options: [
        'crystal branch fork',
        'dual meditation spike',
        'faceted obelisk',
        'ring of small prisms',
        'smooth dream curve',
        'spiral seer',
        'third eye stump',
        'twinned soul branch',
      ],
      tags: ['horns'],
    },
    {
      name: 'eyes',
      category: 'eyes',
      options: [
        'blank white trance',
        'hollow starfield',
        'indigo prophecy',
        'milky seer',
        'pink empathy',
        'silver ringed',
        'sleepwalker blue',
        'violet spiral',
      ],
      tags: ['eyes'],
    },
    {
      name: 'wing membrane',
      category: 'wings',
      options: [
        'aurora filament',
        'dream smoke thin',
        'halo vein pattern',
        'lucid almost gone',
        'mind mist mottle',
        'prism crackle',
        'shadow undersides',
        'thin moth shimmer',
      ],
      tags: ['wings'],
    },
    {
      name: 'tail',
      category: 'tail',
      options: [
        'crystal club',
        'divination fork',
        'heavy prophetic',
        'rake of shards',
        'serpent hypnotic',
        'short grounded',
        'stellate fin',
        'whip thin focus',
      ],
      tags: ['tail'],
    },
    {
      name: 'muzzle',
      category: 'snout',
      options: [
        'delicate visionary',
        'heavy oracle',
        'knowing narrow',
        'nostril flared trance',
        'short serene',
        'slit dreaming',
        'tapered mystic',
        'wide gentle seer',
      ],
      tags: ['snout'],
    },
  ],
  abilities: [
    {
      name: 'flight',
      description: 'beats wings you remember more than hear',
      category: 'movement',
      threatLevel: 3,
    },
    {
      name: 'breath weapon: psychic',
      description: 'unleashes a blast of mind-rending force and doubt',
      category: 'attack',
      threatLevel: 5,
    },
    {
      name: 'dream walk',
      description: 'slips through thought, memory, and nightmare alike',
      category: 'utility',
      threatLevel: 3,
    },
  ],
  baseThreatLevel: 5,
  commonality: 2,
  tags: ['amethyst_dragon', 'gem'],
  resourceProductNames: { scale: 'amethyst dragon scale' },
});
