import { buildTrueDragonSpecies } from './dragon_species_helpers';

export default buildTrueDragonSpecies({
  breedType: 'black_dragon',
  name: 'black dragon',
  pluralName: 'black dragons',
  adjective: 'black draconic',
  family: 'chromatic',
  environments: ['swamp', 'marsh', 'underdark', 'coastal'],
  physicalTraitGeneratorConfigs: [
    {
      name: 'scales',
      category: 'scales',
      options: [
        'acid-gloss obsidian',
        'blue-black wet shine',
        'bog-rot iridescent',
        'char matte',
        'deep purple black',
        'inky ripple',
        'marsh tar sheen',
        'oil slick rainbow',
        'pit charcoal',
        'rotten wood undertone',
        'slick amphibian',
        'streaked with violet',
      ],
      tags: ['scales'],
    },
    {
      name: 'horns and crest',
      category: 'horns',
      options: [
        'backward sickle',
        'crumpled coral',
        'curved swamp rake',
        'knotted rootlike',
        'many short nubs',
        'razor ridge row',
        'single gnarled',
        'split crocodilian',
      ],
      tags: ['horns'],
    },
    {
      name: 'eyes',
      category: 'eyes',
      options: [
        'acid yellow',
        'ember slit',
        'green swamp glow',
        'milky cataract',
        'pin red',
        'rust orange',
        'violet ringed',
        'void black',
        'yellow basking',
      ],
      tags: ['eyes'],
    },
    {
      name: 'wing membrane',
      category: 'wings',
      options: [
        'bat dark tattered',
        'dripping membrane',
        'malarial green web',
        'moss-flecked',
        'rotten sail',
        'slimy translucent',
        'streaked spore',
        'thorn-edged',
      ],
      tags: ['wings'],
    },
    {
      name: 'tail',
      category: 'tail',
      options: [
        'flat paddle',
        'heavy muscled',
        'paddle with spines',
        'ridged crocodile',
        'serrated keel',
        'short thick',
        'whip thin',
        'wormlike long',
      ],
      tags: ['tail'],
    },
    {
      name: 'muzzle',
      category: 'snout',
      options: [
        'elongate gharial',
        'lumpy warted',
        'nostril flared wide',
        'pug blunt',
        'skull broad',
        'snaggle tusked',
        'thin mean',
        'wide froglike',
      ],
      tags: ['snout'],
    },
  ],
  abilities: [
    {
      name: 'flight',
      description: 'lumbers into the air despite marsh-soaked wings',
      category: 'movement',
      threatLevel: 2,
    },
    {
      name: 'breath weapon: acid',
      description: 'vomits a line of corrosive slime that eats metal and flesh',
      category: 'attack',
      threatLevel: 4,
    },
    {
      name: 'water adept',
      description: 'dives and runs bog water like a second sky',
      category: 'movement',
      threatLevel: 2,
    },
  ],
  baseThreatLevel: 5,
  commonality: 2,
  tags: ['black_dragon', 'chromatic'],
  resourceProductNames: { scale: 'black dragon scale' },
});
