import { buildTrueDragonSpecies } from './dragon_species_helpers';

export default buildTrueDragonSpecies({
  breedType: 'blue_dragon',
  name: 'blue dragon',
  pluralName: 'blue dragons',
  adjective: 'blue draconic',
  family: 'chromatic',
  environments: ['coastal', 'desert', 'grassland', 'mountain'],
  physicalTraitGeneratorConfigs: [
    {
      name: 'scales',
      category: 'scales',
      options: [
        'arcing metallic sheen',
        'azure storm',
        'cerulean sandblasted',
        'cobalt deep',
        'electric bright edge',
        'indigo thunderhead',
        'powder desert sky',
        'sand scoured pale',
        'sapphire mirror',
        'sea spray undertone',
        'storm grey-blue',
        'zigzag lightning pale',
      ],
      tags: ['scales'],
    },
    {
      name: 'horns and ridge',
      category: 'horns',
      options: [
        'backward bolt curve',
        'forked conductive',
        'hammer blunt',
        'hook lightning',
        'impala symmetry',
        'ridge of short spikes',
        'swept cavalry saber',
        'twisted corkscrew',
      ],
      tags: ['horns'],
    },
    {
      name: 'eyes',
      category: 'eyes',
      options: [
        'arc white iris',
        'electric white',
        'ice blue calm',
        'indigo spark',
        'storm cloud ring',
        'teal slit',
        'thunder yellow',
        'turquoise keen',
        'violet storm',
      ],
      tags: ['eyes'],
    },
    {
      name: 'wing membrane',
      category: 'wings',
      options: [
        'charged vein lines',
        'dark storm undersides',
        'frayed wind shear',
        'pale desert bleached',
        'ribbed like dunes',
        'sand-tattered tips',
        'static crackle when taut',
        'thin high altitude',
      ],
      tags: ['wings'],
    },
    {
      name: 'tail',
      category: 'tail',
      options: [
        'bladed lightning fin',
        'heavy dune ripper',
        'multiple fins',
        'plow sand wedge',
        'rattle spike clusters',
        'scorpion arch',
        'tapered whip crack',
        'thick rudder',
      ],
      tags: ['tail'],
    },
    {
      name: 'muzzle',
      category: 'snout',
      options: [
        'beak sharp',
        'boxy charger',
        'hooked raptor',
        'long narrow probe',
        'proud roman',
        'serrated smile',
        'short pug power',
        'wide breathe line',
      ],
      tags: ['snout'],
    },
  ],
  abilities: [
    {
      name: 'flight',
      description: 'rides the gale front of its own storms',
      category: 'movement',
      threatLevel: 3,
    },
    {
      name: 'breath weapon: lightning',
      description: 'releases a line of crackling electricity across open ground',
      category: 'attack',
      threatLevel: 4,
    },
    {
      name: 'storm caller',
      description: 'summons dust devils and thunderheads by instinct',
      category: 'utility',
      threatLevel: 3,
    },
  ],
  baseThreatLevel: 5,
  commonality: 2,
  tags: ['blue_dragon', 'chromatic'],
  resourceProductNames: { scale: 'blue dragon scale' },
});
