import { buildTrueDragonSpecies } from './dragon_species_helpers';

export default buildTrueDragonSpecies({
  breedType: 'brass_dragon',
  name: 'brass dragon',
  pluralName: 'brass dragons',
  adjective: 'brass draconic',
  family: 'metallic',
  environments: ['desert', 'grassland', 'hill', 'mountain'],
  physicalTraitGeneratorConfigs: [
    {
      name: 'scales',
      category: 'scales',
      options: [
        'antique patina green',
        'bead blasted matte',
        'bright trumpet gold',
        'burnt sienna undertone',
        'dune sunflare',
        'hammered sheet texture',
        'ochre warm',
        'polished cymbal',
        'sandblasted pale',
        'sun bronze fleck',
        'tarnished teal kiss',
        'weather vane streak',
      ],
      tags: ['scales'],
    },
    {
      name: 'horns',
      category: 'horns',
      options: [
        'coil scroll',
        'crescent back sweep',
        'flared trumpet',
        'knobbed dignified',
        'paired symmetrical',
        'ring stubbed',
        'swept sand crescent',
        'twisted story hook',
      ],
      tags: ['horns'],
    },
    {
      name: 'eyes',
      category: 'eyes',
      options: [
        'blue wise rim',
        'chatty black sparkle',
        'clever hazel',
        'desert mirage',
        'deep well black',
        'gold rim calm',
        'knowing squint',
        'teal ringed',
      ],
      tags: ['eyes'],
    },
    {
      name: 'wing membrane',
      category: 'wings',
      options: [
        'dust veil thin',
        'heat shimmer edge',
        'kite broad',
        'pale dune underside',
        'ribbed flexible',
        'sand stained tips',
        'story scroll scars',
        'sun bleached',
      ],
      tags: ['wings'],
    },
    {
      name: 'tail',
      category: 'tail',
      options: [
        'bell curve',
        'fork shallow',
        'muscle heavy',
        'rake of fins',
        'spiral curl tip',
        'thick grounded',
        'thin expressive',
        'triple ribbon',
      ],
      tags: ['tail'],
    },
    {
      name: 'muzzle',
      category: 'snout',
      options: [
        'grin lines',
        'narrow witty',
        'noble broad',
        'nostril wide talker',
        'roman storyteller',
        'short friendly',
        'slight smirk',
        'wide laugh',
      ],
      tags: ['snout'],
    },
  ],
  abilities: [
    {
      name: 'flight',
      description: 'soars heat pillars with almost lazy grace',
      category: 'movement',
      threatLevel: 3,
    },
    {
      name: 'breath weapon: fire sleep',
      description: 'breathes flame that lulls survivors toward magical slumber',
      category: 'attack',
      threatLevel: 4,
    },
    {
      name: 'silver tongue',
      description: 'negotiates, deceives, or charms as readily as it battles',
      category: 'utility',
      threatLevel: 2,
    },
  ],
  baseThreatLevel: 5,
  commonality: 2,
  tags: ['brass_dragon', 'metallic'],
  resourceProductNames: { scale: 'brass dragon scale' },
});
