import { buildTrueDragonSpecies } from './dragon_species_helpers';

export default buildTrueDragonSpecies({
  breedType: 'bronze_dragon',
  name: 'bronze dragon',
  pluralName: 'bronze dragons',
  adjective: 'bronze draconic',
  family: 'metallic',
  environments: ['coastal', 'hill', 'mountain'],
  physicalTraitGeneratorConfigs: [
    {
      name: 'scales',
      category: 'scales',
      options: [
        'aquatic teal shift',
        'bell bronze deep',
        'cerulean tide line',
        'hammered statue',
        'kelp stain mottle',
        'naval patina',
        'salt lace freckle',
        'seafoam bright edge',
        'ship hull rivet look',
        'storm weathered',
        'sun bronze flash',
        'wave ripple polish',
      ],
      tags: ['scales'],
    },
    {
      name: 'horns',
      category: 'horns',
      options: [
        'anchor back curve',
        'coral textured',
        'helical tide',
        'naval cross',
        'paired trident nod',
        'short harbor',
        'swept dolphin',
        'twisted kelp',
      ],
      tags: ['horns'],
    },
    {
      name: 'eyes',
      category: 'eyes',
      options: [
        'aqua calm',
        'deep harbour',
        'kelp green',
        'lightning white ring',
        'pearl grey',
        'salt blue',
        'storm watch',
        'tide pool black',
      ],
      tags: ['eyes'],
    },
    {
      name: 'wing membrane',
      category: 'wings',
      options: [
        'foam lace edge',
        'gull wing curve',
        'high cliff wind',
        'kelp vein web',
        'rain slick',
        'spray mottled',
        'thin soaring',
        'underbelly pale tide',
      ],
      tags: ['wings'],
    },
    {
      name: 'tail',
      category: 'tail',
      options: [
        'broad rudder',
        'fork riptide',
        'keel finned',
        'otter thickness',
        'paddle flat',
        'ridge of coral knobs',
        'serpent wave',
        'whale power',
      ],
      tags: ['tail'],
    },
    {
      name: 'muzzle',
      category: 'snout',
      options: [
        'broad shark grin',
        'hooked fisher',
        'noble roman sea',
        'nostril salt flare',
        'short sturdy',
        'sleek dolphin',
        'tusk hint',
        'wise creased',
      ],
      tags: ['snout'],
    },
  ],
  abilities: [
    {
      name: 'flight',
      description: 'cuts coastal gales without losing an inch of altitude',
      category: 'movement',
      threatLevel: 3,
    },
    {
      name: 'breath weapon: lightning',
      description: 'releases a crackling repulsion line along wet ground',
      category: 'attack',
      threatLevel: 4,
    },
    {
      name: 'tidal lore',
      description: 'reads reefs, wrecks, and riddles with equal patience',
      category: 'utility',
      threatLevel: 2,
    },
  ],
  baseThreatLevel: 5,
  commonality: 2,
  tags: ['bronze_dragon', 'metallic'],
  resourceProductNames: { scale: 'bronze dragon scale' },
});
