import { buildTrueDragonSpecies } from './dragon_species_helpers';

export default buildTrueDragonSpecies({
  breedType: 'copper_dragon',
  name: 'copper dragon',
  pluralName: 'copper dragons',
  adjective: 'copper draconic',
  family: 'metallic',
  environments: ['desert', 'hill', 'mountain'],
  physicalTraitGeneratorConfigs: [
    {
      name: 'scales',
      category: 'scales',
      options: [
        'acid green patina',
        'bright new penny',
        'chevron mottle',
        'forge heat blush',
        'malachite freckle',
        'orange metal flash',
        'oxidized lace',
        'red brown autumn',
        'rivet line rows',
        'statue verdigris',
        'warm penny roll',
        'weathered clutch',
      ],
      tags: ['scales'],
    },
    {
      name: 'horns',
      category: 'horns',
      options: [
        'acrobat twist',
        'backward jester hook',
        'double trouble fork',
        'jest bell curve',
        'knobbed cap',
        'slim upward',
        'swept humor',
        'tiny mischief nub',
      ],
      tags: ['horns'],
    },
    {
      name: 'eyes',
      category: 'eyes',
      options: [
        'amber joke',
        'chartreuse glint',
        'copper ring',
        'emerald sparkle',
        'grey trickster',
        'turquoise tease',
        'wise crow foot',
        'yellow bright',
      ],
      tags: ['eyes'],
    },
    {
      name: 'wing membrane',
      category: 'wings',
      options: [
        'bat carnival',
        'dapple leaf shade',
        'earthy umber',
        'greenish copper web',
        'mirth worn patch',
        'thin valley glide',
        'tree dapple mimic',
        'weathered fold',
      ],
      tags: ['wings'],
    },
    {
      name: 'tail',
      category: 'tail',
      options: [
        'acrobat curl',
        'club friendly',
        'expressive lash',
        'heavy ridge joke',
        'long storyteller',
        'fork shallow mirth',
        'short stumpy bounce',
        'whip crack timing',
      ],
      tags: ['tail'],
    },
    {
      name: 'muzzle',
      category: 'snout',
      options: [
        'bat ear hint',
        'chipmunk cheek',
        'grin tooth show',
        'long foxish',
        'snub impish',
        'wide laugh lines',
        'wrinkled comic',
        'sharp wit narrow',
      ],
      tags: ['snout'],
    },
  ],
  abilities: [
    {
      name: 'flight',
      description: 'loops and stalls like it enjoys the physics',
      category: 'movement',
      threatLevel: 3,
    },
    {
      name: 'breath weapon: acid',
      description: 'spits a sticky corrosive line that clings and eats cover',
      category: 'attack',
      threatLevel: 4,
    },
    {
      name: 'prankster guile',
      description: 'lays traps of word, illusion, and sheer annoyance',
      category: 'utility',
      threatLevel: 2,
    },
  ],
  baseThreatLevel: 4,
  commonality: 2,
  tags: ['copper_dragon', 'metallic'],
  resourceProductNames: { scale: 'copper dragon scale' },
});
