import { buildTrueDragonSpecies } from './dragon_species_helpers';

export default buildTrueDragonSpecies({
  breedType: 'crystal_dragon',
  name: 'crystal dragon',
  pluralName: 'crystal dragons',
  adjective: 'crystal draconic',
  family: 'gem',
  environments: ['arctic', 'mountain', 'underdark'],
  physicalTraitGeneratorConfigs: [
    {
      name: 'scales',
      category: 'scales',
      options: [
        'albite chalk white',
        'citrine ice prism',
        'clear glass veil',
        'diamond dust sparkle',
        'frosted pane',
        'hall of mirror polish',
        'ice flower fracture',
        'milky quartz',
        'prism rainbow fleck',
        'salt flat gleam',
        'snow blind bright',
        'vein cracked clear',
      ],
      tags: ['scales'],
    },
    {
      name: 'horns',
      category: 'horns',
      options: [
        'antler ice fork',
        'glass obelisk',
        'helix prism',
        'icicle straight',
        'ring of stalactites',
        'shard crown',
        'twin cathedral',
        'upturned chisel',
      ],
      tags: ['horns'],
    },
    {
      name: 'eyes',
      category: 'eyes',
      options: [
        'black facet hollow',
        'blue glacier',
        'clear no pupil',
        'gold inclusion',
        'pink rose quartz',
        'rainbow refraction',
        'silver needle',
        'white out glare',
      ],
      tags: ['eyes'],
    },
    {
      name: 'wing membrane',
      category: 'wings',
      options: [
        'almost invisible',
        'aurora shard',
        'etched frost lattice',
        'laser thin',
        'opal milk',
        'ribbed glass',
        'shatter line',
        'snowfall veil',
      ],
      tags: ['wings'],
    },
    {
      name: 'tail',
      category: 'tail',
      options: [
        'chisel tip',
        'fork lightning glass',
        'heavy crystal maul',
        'ice saw ridge',
        'long transparent whip',
        'short blunt berg',
        'stellate burst',
        'tail of hanging icicles',
      ],
      tags: ['tail'],
    },
    {
      name: 'muzzle',
      category: 'snout',
      options: [
        'bevel sharp',
        'blunt ice shelf',
        'fox quick narrow',
        'noble faceted',
        'short pug crystal',
        'tusk clear',
        'wide breathe frost',
        'wedge saw',
      ],
      tags: ['snout'],
    },
  ],
  abilities: [
    {
      name: 'flight',
      description: 'prisms sunlight into crawling rainbows in its wake',
      category: 'movement',
      threatLevel: 3,
    },
    {
      name: 'breath weapon: radiant',
      description: 'breathes scouring light that blinds and sears truth plain',
      category: 'attack',
      threatLevel: 4,
    },
    {
      name: 'light bending',
      description: 'bends glare, mirage, and laser into camouflage or lance',
      category: 'utility',
      threatLevel: 3,
    },
  ],
  baseThreatLevel: 5,
  commonality: 2,
  tags: ['crystal_dragon', 'gem'],
  resourceProductNames: { scale: 'crystal dragon scale' },
});
