import { buildTrueDragonSpecies } from './dragon_species_helpers';

export default buildTrueDragonSpecies({
  breedType: 'deep_dragon',
  name: 'deep dragon',
  pluralName: 'deep dragons',
  adjective: 'deep draconic',
  family: 'other',
  environments: ['underdark', 'mountain'],
  physicalTraitGeneratorConfigs: [
    {
      name: 'scales',
      category: 'scales',
      options: [
        'biolume teal freckle',
        'blue black abyss',
        'cavern drip sheen',
        'fang white edge',
        'lichen faint glow',
        'manganese purple',
        'obsidian wet',
        'pressure scar ripple',
        'stalactite grey',
        'sulfur yellow seam',
        'wet cave ink',
        'worm pale cave',
      ],
      tags: ['scales'],
    },
    {
      name: 'horns',
      category: 'horns',
      options: [
        'backward cave pick',
        'chelon shell stubs',
        'helix bore hole',
        'hook miner',
        'paired stalagmite',
        'short blunt tunnel',
        'spiral descent',
        'twisted root stone',
      ],
      tags: ['horns'],
    },
    {
      name: 'eyes',
      category: 'eyes',
      options: [
        'blind cave pink',
        'ember furnace vent',
        'green chem faint',
        'milky cave',
        'nocturne yellow',
        'reflect tapetum',
        'salt crust rim',
        'void hungry',
      ],
      tags: ['eyes'],
    },
    {
      name: 'wing membrane',
      category: 'wings',
      options: [
        'bat cavern',
        'drip line edge',
        'fan cave pale',
        'mold mottle',
        'thin pressure',
        'torn echo',
        'webbed phalanx',
        'wet leather dark',
      ],
      tags: ['wings'],
    },
    {
      name: 'tail',
      category: 'tail',
      options: [
        'club breaker',
        'eel long',
        'fin cave triad',
        'heavy sediment',
        'hook anchor',
        'rake stone chip',
        'short splay',
        'worm coil',
      ],
      tags: ['tail'],
    },
    {
      name: 'muzzle',
      category: 'snout',
      options: [
        'eel long sensor',
        'frog wide',
        'heavy mole',
        'hook lamprey hint',
        'sensor stub',
        'short blunt brute',
        'tapir soft',
        'wide breathe spore',
      ],
      tags: ['snout'],
    },
  ],
  abilities: [
    {
      name: 'flight',
      description: 'threads caverns and shafts that should deny wings',
      category: 'movement',
      threatLevel: 2,
    },
    {
      name: 'breath weapon: acid',
      description: 'sprays caustic spittle that tunnels through rock',
      category: 'attack',
      threatLevel: 4,
    },
    {
      name: 'earth glide',
      description: 'slips through stone and rubble like loose water',
      category: 'utility',
      threatLevel: 3,
    },
  ],
  baseThreatLevel: 5,
  commonality: 2,
  tags: ['deep_dragon'],
  resourceProductNames: { scale: 'deep dragon scale' },
});
