import { buildTrueDragonSpecies } from './dragon_species_helpers';

export default buildTrueDragonSpecies({
  breedType: 'emerald_dragon',
  name: 'emerald dragon',
  pluralName: 'emerald dragons',
  adjective: 'emerald draconic',
  family: 'gem',
  environments: ['forest', 'hill', 'mountain', 'underdark'],
  physicalTraitGeneratorConfigs: [
    {
      name: 'scales',
      category: 'scales',
      options: [
        'bottle glass green',
        'chrome edge green',
        'chlorite matte',
        'deep beryl black green',
        'faceted pavilion',
        'jungle metal',
        'moss undertone bright',
        'oil slick green',
        'poison bright chartreuse',
        'trapiche star',
        'verdant mirror',
        'wet stone gleam',
      ],
      tags: ['scales'],
    },
    {
      name: 'horns',
      category: 'horns',
      options: [
        'backward saber',
        'crown of chips',
        'fork viper',
        'helix thorn',
        'jade knob',
        'leaf curve pair',
        'stinger short',
        'twisted briar glass',
      ],
      tags: ['horns'],
    },
    {
      name: 'eyes',
      category: 'eyes',
      options: [
        'acid chartreuse',
        'black pin predatory',
        'cat vertical',
        'emerald flash',
        'malachite band',
        'neon strike',
        'soft moss',
        'yellow trap',
      ],
      tags: ['eyes'],
    },
    {
      name: 'wing membrane',
      category: 'wings',
      options: [
        'bee stripe dark',
        'canopy mottle',
        'lichen lace',
        'shadow leaf',
        'stained poison bright',
        'thin jungle',
        'venom drip edge',
        'waxy undersides',
      ],
      tags: ['wings'],
    },
    {
      name: 'tail',
      category: 'tail',
      options: [
        'barbed injector',
        'club stone weight',
        'heavy constrictor',
        'leaf fin',
        'needle lash',
        'rake of glass spines',
        'short viper',
        'whip toxin',
      ],
      tags: ['tail'],
    },
    {
      name: 'muzzle',
      category: 'snout',
      options: [
        'boxy cruel',
        'croc long',
        'noble roman poison',
        'nostril heat pit',
        'short blunt striker',
        'snake elegant',
        'tusk glass',
        'wide grin hunter',
      ],
      tags: ['snout'],
    },
  ],
  abilities: [
    {
      name: 'flight',
      description: 'drops from canopy dark without rustling a leaf',
      category: 'movement',
      threatLevel: 3,
    },
    {
      name: 'breath weapon: poison',
      description: 'exhales a clinging green vapor that eats courage and breath',
      category: 'attack',
      threatLevel: 5,
    },
    {
      name: 'silent mind',
      description: 'masks thought and speech inside jeweled calm',
      category: 'utility',
      threatLevel: 3,
    },
  ],
  baseThreatLevel: 5,
  commonality: 2,
  tags: ['emerald_dragon', 'gem'],
  resourceProductNames: { scale: 'emerald dragon scale' },
});
