import { buildTrueDragonSpecies } from './dragon_species_helpers';

export default buildTrueDragonSpecies({
  breedType: 'gold_dragon',
  name: 'gold dragon',
  pluralName: 'gold dragons',
  adjective: 'gold draconic',
  family: 'metallic',
  environments: ['grassland', 'hill', 'mountain'],
  physicalTraitGeneratorConfigs: [
    {
      name: 'scales',
      category: 'scales',
      options: [
        'auric mirror',
        'baroque filigree edge',
        'coin bright',
        'crown jewel fleck',
        'ember undertone',
        'hammered royal',
        'honey deep',
        'linen pale belly',
        'museum polish',
        'rose gold wash',
        'sun coronet flash',
        'white gold frost rim',
      ],
      tags: ['scales'],
    },
    {
      name: 'horns',
      category: 'horns',
      options: [
        'coronet flourish',
        'imperial sweep',
        'justice scale curve',
        'paired sovereign',
        'philosopher spiral',
        'ridge of gems',
        'stately backward',
        'temple spire pair',
      ],
      tags: ['horns'],
    },
    {
      name: 'eyes',
      category: 'eyes',
      options: [
        'amber wise',
        'azure just',
        'black depth',
        'gold fleck',
        'green discernment',
        'platinum ring',
        'topaz stern kindness',
        'violet far seeing',
      ],
      tags: ['eyes'],
    },
    {
      name: 'wing membrane',
      category: 'wings',
      options: [
        'aurora edge',
        'banner clean',
        'dawn pale undersides',
        'gilded rib',
        'martial square',
        'mist vein',
        'proud broad',
        'ritual scar rare',
      ],
      tags: ['wings'],
    },
    {
      name: 'tail',
      category: 'tail',
      options: [
        'banner ribbon',
        'judgment club',
        'long mentor',
        'peacock fan',
        'regal taper',
        'rite knot tip',
        'rudder stately',
        'winglet paired',
      ],
      tags: ['tail'],
    },
    {
      name: 'muzzle',
      category: 'snout',
      options: [
        'aristocrat roman',
        'calm judge',
        'flared dragon lord',
        'gentle giant wide',
        'keen scholar narrow',
        'kind-eyed heavy',
        'stern beak',
        'wise creased smile',
      ],
      tags: ['snout'],
    },
  ],
  abilities: [
    {
      name: 'flight',
      description: 'wings eclipse the ridgeline like a moving sunrise',
      category: 'movement',
      threatLevel: 3,
    },
    {
      name: 'breath weapon: fire',
      description: 'breathes refined flame that honours oaths and scourges tyrants',
      category: 'attack',
      threatLevel: 5,
    },
    {
      name: 'arcane majesty',
      description: 'weaves law, starlight, and prophecy into working magic',
      category: 'utility',
      threatLevel: 3,
    },
  ],
  baseThreatLevel: 6,
  commonality: 1,
  tags: ['gold_dragon', 'metallic'],
  resourceProductNames: { scale: 'gold dragon scale' },
});
