import { buildTrueDragonSpecies } from './dragon_species_helpers';

export default buildTrueDragonSpecies({
  breedType: 'green_dragon',
  name: 'green dragon',
  pluralName: 'green dragons',
  adjective: 'green draconic',
  family: 'chromatic',
  environments: ['forest', 'hill', 'mountain'],
  physicalTraitGeneratorConfigs: [
    {
      name: 'scales',
      category: 'scales',
      options: [
        'bark brown mottled',
        'bottle emerald',
        'lichen speckled',
        'moss carpeted',
        'needle green',
        'olive drab',
        'pine deep',
        'shadowed jade',
        'spring leaf bright',
        'surgical poison green',
        'teal undertone',
        'wet canopy',
      ],
      tags: ['scales'],
    },
    {
      name: 'horns and crown',
      category: 'horns',
      options: [
        'antler forked',
        'branching woody',
        'curved leaflike',
        'ivy wrapped stubs',
        'swept back thorn',
        'triple crown',
        'twisted briar',
        'vestigial knobs',
      ],
      tags: ['horns'],
    },
    {
      name: 'eyes',
      category: 'eyes',
      options: [
        'amber hunter',
        'chartreuse slit',
        'ember through leaves',
        'gold ring',
        'malachite fleck',
        'predator yellow',
        'pupil thin black',
        'toxic yellow-green',
      ],
      tags: ['eyes'],
    },
    {
      name: 'wing membrane',
      category: 'wings',
      options: [
        'dapple stained glass',
        'leaf vein pattern',
        'mottled shade',
        'pale spring undersides',
        'semi-transparent canopy',
        'spore dusted',
        'thick ivy edge',
        'wood rot flecks',
      ],
      tags: ['wings'],
    },
    {
      name: 'tail',
      category: 'tail',
      options: [
        'club of bone',
        'feathered ridge',
        'leaf-shaped fin',
        'long whip',
        'sawback spines',
        'short forest brute',
        'split fishing',
        'thick constrictor',
      ],
      tags: ['tail'],
    },
    {
      name: 'muzzle',
      category: 'snout',
      options: [
        'croc long',
        'noble roman curve',
        'ridged snarl lip',
        'short blunt',
        'snake narrow',
        'wide nostril flare',
        'wrinkled wise',
        'narrow fox',
      ],
      tags: ['snout'],
    },
  ],
  abilities: [
    {
      name: 'flight',
      description: 'glides between redwoods and ravines without stirring leaves',
      category: 'movement',
      threatLevel: 3,
    },
    {
      name: 'breath weapon: poison',
      description: 'breathes a cloud of caustic gas that strips lungs bare',
      category: 'attack',
      threatLevel: 4,
    },
    {
      name: 'woodland wile',
      description: 'speaks in guile and ambush as second nature',
      category: 'utility',
      threatLevel: 2,
    },
  ],
  baseThreatLevel: 5,
  commonality: 2,
  tags: ['green_dragon', 'chromatic'],
  resourceProductNames: { scale: 'green dragon scale' },
});
