import { buildTrueDragonSpecies } from './dragon_species_helpers';

export default buildTrueDragonSpecies({
  breedType: 'moon_dragon',
  name: 'moon dragon',
  pluralName: 'moon dragons',
  adjective: 'moon draconic',
  family: 'other',
  environments: ['arctic', 'coastal', 'mountain'],
  physicalTraitGeneratorConfigs: [
    {
      name: 'scales',
      category: 'scales',
      options: [
        'alabaster cool',
        'blue silver tide',
        'crater dimple grey',
        'echo pale pearl',
        'iridescent night',
        'lunar maria dark',
        'mirror tide calm',
        'opal milk shell',
        'quartz frost',
        'selene bright',
        'star spec pin field',
        'white gold moon edge',
      ],
      tags: ['scales'],
    },
    {
      name: 'horns',
      category: 'horns',
      options: [
        'backward crescent thin',
        'crown of small spheres',
        'helix orbit',
        'paired crescent',
        'ring eclipse',
        'smooth meridian',
        'spiral apogee',
        'twin sickle',
      ],
      tags: ['horns'],
    },
    {
      name: 'eyes',
      category: 'eyes',
      options: [
        'black full disc',
        'blue earthshine',
        'gold eclipse ring',
        'milky halo',
        'pale tired kind',
        'silver mirror',
        'white out',
        'violet dream',
      ],
      tags: ['eyes'],
    },
    {
      name: 'wing membrane',
      category: 'wings',
      options: [
        'cirrus thin',
        'eclipse gradient',
        'ghost ripples',
        'high cold sheer',
        'lunar phase mottle',
        'pale underside glow',
        'star scattered',
        'tide pulled',
      ],
      tags: ['wings'],
    },
    {
      name: 'tail',
      category: 'tail',
      options: [
        'comet taper',
        'fan night fin',
        'grace ribbon',
        'heavy grounded calm',
        'long meditative',
        'ring crater club',
        'short wise',
        'whip star trail',
      ],
      tags: ['tail'],
    },
    {
      name: 'muzzle',
      category: 'snout',
      options: [
        'delicate lunar',
        'gentle slope',
        'kind nostril',
        'meditative short',
        'moon curve roman',
        'narrow seer',
        'wide calm',
        'wise creased',
      ],
      tags: ['snout'],
    },
  ],
  abilities: [
    {
      name: 'flight',
      description: 'hangs in the sky as if gravity forgot its name',
      category: 'movement',
      threatLevel: 3,
    },
    {
      name: 'breath weapon: cold',
      description: 'exhales silence and frost that steals warmth from memory',
      category: 'attack',
      threatLevel: 4,
    },
    {
      name: 'lunar tide',
      description: 'pulls tides of emotion, sleep, and tide water alike',
      category: 'utility',
      threatLevel: 3,
    },
  ],
  baseThreatLevel: 5,
  commonality: 2,
  tags: ['moon_dragon'],
  resourceProductNames: { scale: 'moon dragon scale' },
});
