import { buildTrueDragonSpecies } from './dragon_species_helpers';

export default buildTrueDragonSpecies({
  breedType: 'night_dragon',
  name: 'night dragon',
  pluralName: 'night dragons',
  adjective: 'night draconic',
  family: 'other',
  environments: ['forest', 'hill', 'mountain', 'swamp'],
  physicalTraitGeneratorConfigs: [
    {
      name: 'scales',
      category: 'scales',
      options: [
        'blue black velvet',
        'charcoal blue sheen',
        'crow feather ripple',
        'dusk purple seam',
        'eventide silver speck',
        'ink swallow matte',
        'midnight teal flash',
        'obsidian frost rim',
        'owl grey mottle',
        'shade silk gloss',
        'starfield freckle',
        'twilight bruise metal',
      ],
      tags: ['scales'],
    },
    {
      name: 'horns',
      category: 'horns',
      options: [
        'backward crescent dark',
        'crown of short thorns',
        'fork dream',
        'helix smoke',
        'paired hunter curves',
        'ring of stubs',
        'swept bat wing',
        'twisted nocturne',
      ],
      tags: ['horns'],
    },
    {
      name: 'eyes',
      category: 'eyes',
      options: [
        'amber hunt ring',
        'cat green glow',
        'gold lunar ring',
        'milky navigator',
        'silver pin stars',
        'violet tired wise',
        'white reflective',
        'yellow predator',
      ],
      tags: ['eyes'],
    },
    {
      name: 'wing membrane',
      category: 'wings',
      options: [
        'bat broad silence',
        'cloud veil thin',
        'eclipse gradient',
        'moth powder edge',
        'night sky scatter star',
        'owl primary',
        'ragged storm hem',
        'sheet aurora hint',
      ],
      tags: ['wings'],
    },
    {
      name: 'tail',
      category: 'tail',
      options: [
        'club velvet weight',
        'fan cooling fin',
        'fork shallow',
        'heavy prowler',
        'rake soft spine',
        'serpent endless',
        'short stalker',
        'whip quiet',
      ],
      tags: ['tail'],
    },
    {
      name: 'muzzle',
      category: 'snout',
      options: [
        'blunt sleeper',
        'fox quick',
        'heavy judge',
        'hook owl',
        'narrow patient',
        'nostril wide breathe',
        'roman noble dark',
        'short kind',
      ],
      tags: ['snout'],
    },
  ],
  abilities: [
    {
      name: 'flight',
      description: 'crosses from dusk to dawn without a sound worth hearing',
      category: 'movement',
      threatLevel: 3,
    },
    {
      name: 'breath weapon: necrotic gloom',
      description: 'exhales clinging darkness that numbs limbs and thought',
      category: 'attack',
      threatLevel: 4,
    },
    {
      name: 'tread of night',
      description: 'walks star paths and deep shade as if they were solid trails',
      category: 'utility',
      threatLevel: 3,
    },
  ],
  baseThreatLevel: 5,
  commonality: 2,
  tags: ['night_dragon'],
  resourceProductNames: { scale: 'night dragon scale' },
});
