import { buildTrueDragonSpecies } from './dragon_species_helpers';

export default buildTrueDragonSpecies({
  breedType: 'platinum_dragon',
  name: 'platinum dragon',
  pluralName: 'platinum dragons',
  adjective: 'platinum draconic',
  family: 'metallic',
  environments: ['grassland', 'hill', 'mountain'],
  physicalTraitGeneratorConfigs: [
    {
      name: 'scales',
      category: 'scales',
      options: [
        'aurora ice rim',
        'chalice bright white',
        'court polish mirror',
        'crown fleck diamond',
        'forge white heat',
        'hall of dawn',
        'linen pale belly scale',
        'museum flawless',
        'oath shine edge',
        'palladium cool',
        'snow steel bright',
        'winter sun flash',
      ],
      tags: ['scales'],
    },
    {
      name: 'horns',
      category: 'horns',
      options: [
        'architect spire pair',
        'coronet justice',
        'helix benediction',
        'imperial sweep',
        'paired sovereign long',
        'ridge of small stars',
        'spiral code',
        'temple fork calm',
      ],
      tags: ['horns'],
    },
    {
      name: 'eyes',
      category: 'eyes',
      options: [
        'azure law',
        'black depth kind',
        'gold merciful',
        'ice blue stern',
        'platinum ring',
        'silver far seeing',
        'violet gentle',
        'white star point',
      ],
      tags: ['eyes'],
    },
    {
      name: 'wing membrane',
      category: 'wings',
      options: [
        'banner white clean',
        'cloud paladin',
        'dawn blush thin',
        'halo stained',
        'high cold sheer',
        'mist bright',
        'proud broad',
        'ritual scar rare',
      ],
      tags: ['wings'],
    },
    {
      name: 'tail',
      category: 'tail',
      options: [
        'banner ribbon',
        'grace heavy',
        'judgment club',
        'long mentor',
        'peacock fan pale',
        'regal taper',
        'rudder calm',
        'stellate fin bright',
      ],
      tags: ['tail'],
    },
    {
      name: 'muzzle',
      category: 'snout',
      options: [
        'aristocrat stern',
        'gentle giant kind',
        'judge merciful wide',
        'keen scholar',
        'noble roman flare',
        'open benediction',
        'short warm',
        'wise creased',
      ],
      tags: ['snout'],
    },
  ],
  abilities: [
    {
      name: 'flight',
      description: 'eclipses lesser wyrms without haste or pride on display',
      category: 'movement',
      threatLevel: 3,
    },
    {
      name: 'breath weapon: cold',
      description: 'exhales cleansing frost that quenches false flame and tyrants alike',
      category: 'attack',
      threatLevel: 5,
    },
    {
      name: 'apex ward',
      description: 'layers truth, law, and starlight into working sanctuary',
      category: 'utility',
      threatLevel: 4,
    },
  ],
  baseThreatLevel: 7,
  commonality: 1,
  tags: ['platinum_dragon', 'metallic'],
  resourceProductNames: { scale: 'platinum dragon scale' },
});
