import { buildTrueDragonSpecies } from './dragon_species_helpers';

export default buildTrueDragonSpecies({
  breedType: 'radiant_dragon',
  name: 'radiant dragon',
  pluralName: 'radiant dragons',
  adjective: 'radiant draconic',
  family: 'other',
  environments: ['grassland', 'hill', 'mountain'],
  physicalTraitGeneratorConfigs: [
    {
      name: 'scales',
      category: 'scales',
      options: [
        'aurora seam',
        'bone white blaze',
        'burnished dawn gold',
        'chrome holy edge',
        'halo scratch facet',
        'ivory sun rim',
        'mirror benediction',
        'pearl glare soft',
        'platinum clean',
        'rainbow oil thin',
        'white gold flame kiss',
        'wing feather bright fleck',
      ],
      tags: ['scales'],
    },
    {
      name: 'horns',
      category: 'horns',
      options: [
        'crown burst ray',
        'flame spiral up',
        'helix benediction',
        'pair dawn spire',
        'ring stub glory',
        'smooth sunlight curve',
        'star point triple',
        'swept aurora',
      ],
      tags: ['horns'],
    },
    {
      name: 'eyes',
      category: 'eyes',
      options: [
        'amber kind furnace',
        'blue white noon',
        'gold merciful',
        'jade stern',
        'platinum ring',
        'rose compassion',
        'silver far',
        'white searing',
      ],
      tags: ['eyes'],
    },
    {
      name: 'wing membrane',
      category: 'wings',
      options: [
        'banner clean',
        'dawn blush underside',
        'gold leaf vein',
        'halo stained',
        'mist bright',
        'proud broad choir',
        'stained glass hint',
        'thin high choir',
      ],
      tags: ['wings'],
    },
    {
      name: 'tail',
      category: 'tail',
      options: [
        'banner ribbon',
        'flame fork bright',
        'grace heavy',
        'pillar club',
        'rudder calm',
        'split sunrise',
        'starburst fin',
        'whip light line',
      ],
      tags: ['tail'],
    },
    {
      name: 'muzzle',
      category: 'snout',
      options: [
        'aristocrat stern good',
        'gentle giant',
        'judge kind wide',
        'narrow bright spear',
        'open smile benediction',
        'roman noble flare',
        'short warm',
        'stern merciful',
      ],
      tags: ['snout'],
    },
  ],
  abilities: [
    {
      name: 'flight',
      description: 'casts daylight shadows sharp as blades below',
      category: 'movement',
      threatLevel: 3,
    },
    {
      name: 'breath weapon: radiant',
      description: 'breathes consecrating light that scourges malice and shadow',
      category: 'attack',
      threatLevel: 5,
    },
    {
      name: 'sanctuary aura',
      description: 'makes air hum with wards against fear and lies',
      category: 'utility',
      threatLevel: 3,
    },
  ],
  baseThreatLevel: 6,
  commonality: 1,
  tags: ['radiant_dragon'],
  resourceProductNames: { scale: 'radiant dragon scale' },
});
