import { buildTrueDragonSpecies } from './dragon_species_helpers';

export default buildTrueDragonSpecies({
  breedType: 'red_dragon',
  name: 'red dragon',
  pluralName: 'red dragons',
  adjective: 'red draconic',
  family: 'chromatic',
  environments: ['desert', 'hill', 'mountain'],
  physicalTraitGeneratorConfigs: [
    {
      name: 'scales',
      category: 'scales',
      options: [
        'basalt edged ember',
        'blood crimson',
        'brick matte',
        'cinder black kissed',
        'coal seam undertone',
        'copper oxide flash',
        'ember gradient',
        'garnet faceted',
        'magma vein bright',
        'rust oxide freckle',
        'smoke veined',
        'volcanic glass gleam',
      ],
      tags: ['scales'],
    },
    {
      name: 'horns and crown',
      category: 'horns',
      options: [
        'backward infernal curl',
        'bison heavy',
        'double royal curve',
        'fuel spike forward',
        'iron dark spiral',
        'notched battle',
        'ring of stubs',
        'sweeping bull',
      ],
      tags: ['horns'],
    },
    {
      name: 'eyes',
      category: 'eyes',
      options: [
        'coal black pit',
        'furnace orange',
        'gold furnace ring',
        'incandescent slit',
        'molten yellow',
        'ruby reflective',
        'smoke ringed',
        'white hot pin',
      ],
      tags: ['eyes'],
    },
    {
      name: 'wing membrane',
      category: 'wings',
      options: [
        'ash undersides',
        'bat volcanic',
        'ember mottled',
        'flare orange web',
        'scarred siege',
        'smoke stained',
        'thin heat shimmer',
        'torn battle banner',
      ],
      tags: ['wings'],
    },
    {
      name: 'tail',
      category: 'tail',
      options: [
        'club volcanic mass',
        'fork lava river',
        'heavy siege ram',
        'hook barbed',
        'line of dorsal blades',
        'thin lash whip',
        'triple fin flare',
        'wedge smasher',
      ],
      tags: ['tail'],
    },
    {
      name: 'muzzle',
      category: 'snout',
      options: [
        'blunt ram',
        'heavy tyrant wide',
        'hooked furnace',
        'noble flare nostril',
        'short cruel grin',
        'swept hawkish',
        'tusk lower jut',
        'wide furnace pit',
      ],
      tags: ['snout'],
    },
  ],
  abilities: [
    {
      name: 'flight',
      description: 'heat shimmers off its wingbeats like forge hammers',
      category: 'movement',
      threatLevel: 3,
    },
    {
      name: 'breath weapon: fire',
      description: 'unleashes a cone of flame hot enough to slag stone',
      category: 'attack',
      threatLevel: 5,
    },
    {
      name: 'magma sense',
      description: 'feels tunnels and vents of molten rock for miles',
      category: 'senses',
      threatLevel: 2,
    },
  ],
  baseThreatLevel: 6,
  commonality: 2,
  tags: ['red_dragon', 'chromatic'],
  resourceProductNames: { scale: 'red dragon scale' },
});
