import { buildTrueDragonSpecies } from './dragon_species_helpers';

export default buildTrueDragonSpecies({
  breedType: 'sapphire_dragon',
  name: 'sapphire dragon',
  pluralName: 'sapphire dragons',
  adjective: 'sapphire draconic',
  family: 'gem',
  environments: ['coastal', 'mountain', 'underdark'],
  physicalTraitGeneratorConfigs: [
    {
      name: 'scales',
      category: 'scales',
      options: [
        'abyss ink blue',
        'cornflower bright',
        'electric vein line',
        'glacier shear',
        'lapis lazuli freckle',
        'midnight starfield',
        'peacock metal',
        'sapphire star facet',
        'sea cliff sheen',
        'steel blue storm',
        'tide pool teal',
        'velvet cobalt',
      ],
      tags: ['scales'],
    },
    {
      name: 'horns',
      category: 'horns',
      options: [
        'anchor back',
        'bolt upright',
        'crown of chips',
        'helix tide',
        'judge bench curve',
        'paired trident short',
        'smooth meridian',
        'wave carved',
      ],
      tags: ['horns'],
    },
    {
      name: 'eyes',
      category: 'eyes',
      options: [
        'arctic ice',
        'black calm storm',
        'clean white ring',
        'electric arc',
        'grey judge',
        'piercing teal',
        'silver calm',
        'storm yellow',
      ],
      tags: ['eyes'],
    },
    {
      name: 'wing membrane',
      category: 'wings',
      options: [
        'foam edge',
        'hurricane rib',
        'iron rain stain',
        'kelp teal web',
        'sheet lightning trace',
        'spray mottle',
        'thick pressure',
        'thin high front',
      ],
      tags: ['wings'],
    },
    {
      name: 'tail',
      category: 'tail',
      options: [
        'anchor fluke',
        'club tidal',
        'fork riptide',
        'keel razor',
        'rudder storm',
        'serpent press',
        'short blunt harbor',
        'whip whitecap',
      ],
      tags: ['tail'],
    },
    {
      name: 'muzzle',
      category: 'snout',
      options: [
        'beak gull',
        'heavy magistrate',
        'hook predatory',
        'narrow piercing',
        'short square',
        'sleek dolphin',
        'wide breathe gale',
        'wise creased stern',
      ],
      tags: ['snout'],
    },
  ],
  abilities: [
    {
      name: 'flight',
      description: 'threads storms and pressure fronts like lanes of a highway',
      category: 'movement',
      threatLevel: 3,
    },
    {
      name: 'breath weapon: thunder',
      description: 'releases a rolling sonic bolt that shatters bone and stone',
      category: 'attack',
      threatLevel: 5,
    },
    {
      name: 'pressure sense',
      description: 'reads weather, tide, and crowd mood as plain pressures',
      category: 'senses',
      threatLevel: 2,
    },
  ],
  baseThreatLevel: 5,
  commonality: 2,
  tags: ['sapphire_dragon', 'gem'],
  resourceProductNames: { scale: 'sapphire dragon scale' },
});
