import { buildTrueDragonSpecies } from './dragon_species_helpers';

export default buildTrueDragonSpecies({
  breedType: 'shadow_dragon',
  name: 'shadow dragon',
  pluralName: 'shadow dragons',
  adjective: 'shadow draconic',
  family: 'other',
  environments: ['mountain', 'swamp', 'underdark'],
  physicalTraitGeneratorConfigs: [
    {
      name: 'scales',
      category: 'scales',
      options: [
        'ash matte swallowing',
        'eclipse rim purple',
        'ghost smoke border',
        'hole black soft',
        'ink ripple',
        'midnight oil',
        'negative light edge',
        'soot velvet',
        'star swallow matte',
        'tar faint blue',
        'twilight bruise',
        'void fleck silver',
      ],
      tags: ['scales'],
    },
    {
      name: 'horns',
      category: 'horns',
      options: [
        'antler smoke',
        'backward sickle night',
        'broken crown shard',
        'fork umbral',
        'helix hollow',
        'obsidian blade pair',
        'stub nightmare',
        'twisted crawl',
      ],
      tags: ['horns'],
    },
    {
      name: 'eyes',
      category: 'eyes',
      options: [
        'ember pin far',
        'green rot faint',
        'hollow white',
        'purple tired',
        'red pin hunger',
        'silver moon ring',
        'yellow predatory',
        'absent black',
      ],
      tags: ['eyes'],
    },
    {
      name: 'wing membrane',
      category: 'wings',
      options: [
        'bat torn night',
        'cloak hem',
        'fog through',
        'moth eaten dark',
        'night sky pin stars',
        'ragged eclipse',
        'sheet grave',
        'thin hunger',
      ],
      tags: ['wings'],
    },
    {
      name: 'tail',
      category: 'tail',
      options: [
        'barbed hook',
        'club grave weight',
        'fork shadow river',
        'heavy silence',
        'rake spine',
        'serpent endless',
        'short stump menace',
        'whip quiet',
      ],
      tags: ['tail'],
    },
    {
      name: 'muzzle',
      category: 'snout',
      options: [
        'blunt skull',
        'croc grave',
        'grin too wide',
        'heavy tyrant',
        'hook raptor',
        'narrow stalker',
        'nostril smoke',
        'short cruel',
      ],
      tags: ['snout'],
    },
  ],
  abilities: [
    {
      name: 'flight',
      description: 'crosses darkness as if it were solid ground',
      category: 'movement',
      threatLevel: 3,
    },
    {
      name: 'breath weapon: necrotic shadow',
      description: 'exhales chill that eats strength and bleeds color away',
      category: 'attack',
      threatLevel: 5,
    },
    {
      name: 'umbral merge',
      description: 'steps through shadow as doorways',
      category: 'utility',
      threatLevel: 3,
    },
  ],
  baseThreatLevel: 6,
  commonality: 2,
  tags: ['shadow_dragon'],
  resourceProductNames: { scale: 'shadow dragon scale' },
});
