import { buildTrueDragonSpecies } from './dragon_species_helpers';

export default buildTrueDragonSpecies({
  breedType: 'silver_dragon',
  name: 'silver dragon',
  pluralName: 'silver dragons',
  adjective: 'silver draconic',
  family: 'metallic',
  environments: ['arctic', 'coastal', 'mountain'],
  physicalTraitGeneratorConfigs: [
    {
      name: 'scales',
      category: 'scales',
      options: [
        'aluminum bright',
        'cloud grey blue',
        'frost filament',
        'mercury ripple',
        'mirror polish',
        'moon axe gleam',
        'nickel satin',
        'snow shadow',
        'star specular pin',
        'storm brushed',
        'tarnish lavender',
        'winter steel',
      ],
      tags: ['scales'],
    },
    {
      name: 'horns',
      category: 'horns',
      options: [
        'backward crescent moon',
        'feather notch',
        'ice carving',
        'paired contemplative',
        'smooth meridian',
        'spiral star path',
        'swept cloud',
        'thin astrolabe',
      ],
      tags: ['horns'],
    },
    {
      name: 'eyes',
      category: 'eyes',
      options: [
        'blue grey kind',
        'ice chip clear',
        'indigo dream',
        'mauve soft',
        'pearl grey',
        'silver ring',
        'sky meditative',
        'white star point',
      ],
      tags: ['eyes'],
    },
    {
      name: 'wing membrane',
      category: 'wings',
      options: [
        'cirrus thin',
        'dawn pink underside',
        'high altitude sheer',
        'mist scalloped',
        'moonlit translucence',
        'quiet snow veil',
        'ribbed silver',
        'zenith broad',
      ],
      tags: ['wings'],
    },
    {
      name: 'tail',
      category: 'tail',
      options: [
        'cloud plume',
        'comet taper',
        'fin of frost',
        'gentle giant thick',
        'graceful ribbon',
        'ridge serene',
        'split vent',
        'wake eddy',
      ],
      tags: ['tail'],
    },
    {
      name: 'muzzle',
      category: 'snout',
      options: [
        'elfin narrow',
        'gentle slope',
        'kind nostril',
        'meditative short',
        'moon curve',
        'noble long',
        'shy tucked chin',
        'starry freckle skin',
      ],
      tags: ['snout'],
    },
  ],
  abilities: [
    {
      name: 'flight',
      description: 'rides the thin air as if the sky were solid',
      category: 'movement',
      threatLevel: 3,
    },
    {
      name: 'breath weapon: cold',
      description: 'exhales paralyzing frost that locks muscles mid-stride',
      category: 'attack',
      threatLevel: 4,
    },
    {
      name: 'cloud home',
      description: 'shapes mists, mirages, and hidden eyries at will',
      category: 'utility',
      threatLevel: 2,
    },
  ],
  baseThreatLevel: 5,
  commonality: 2,
  tags: ['silver_dragon', 'metallic'],
  resourceProductNames: { scale: 'silver dragon scale' },
});
