import { buildTrueDragonSpecies } from './dragon_species_helpers';

export default buildTrueDragonSpecies({
  breedType: 'steel_dragon',
  name: 'steel dragon',
  pluralName: 'steel dragons',
  adjective: 'steel draconic',
  family: 'other',
  environments: ['hill', 'mountain', 'urban'],
  physicalTraitGeneratorConfigs: [
    {
      name: 'scales',
      category: 'scales',
      options: [
        'blue gunmetal',
        'brushed mill finish',
        'chain mail ripple',
        'chrome cold',
        'forge scale pattern',
        'iron dark matte',
        'nickel satin',
        'oil quench rainbow',
        'rivet line seam',
        'spark grind bright',
        'storm grey plate',
        'temper line blue',
      ],
      tags: ['scales'],
    },
    {
      name: 'horns',
      category: 'horns',
      options: [
        'angle iron back',
        'cutting shear pair',
        'forge hammer blunt',
        'I beam stub',
        'rail curve',
        'reinforcement stub row',
        'tine forklift',
        'twisted scrap',
      ],
      tags: ['horns'],
    },
    {
      name: 'eyes',
      category: 'eyes',
      options: [
        'arc white weld',
        'blue torch',
        'ember cooling',
        'grey engineer',
        'orange hazard',
        'red sensor',
        'slag gold',
        'white hot pin',
      ],
      tags: ['eyes'],
    },
    {
      name: 'wing membrane',
      category: 'wings',
      options: [
        'corrugated sheet',
        'fan turbine',
        'heat haze edge',
        'oil stain web',
        'patch rivet',
        'rust fleck thin',
        'smoke vent line',
        'thin alloy',
      ],
      tags: ['wings'],
    },
    {
      name: 'tail',
      category: 'tail',
      options: [
        'ballast club',
        'fork gantry',
        'heavy girder',
        'hook crane',
        'rake spike',
        'rudder plate',
        'short industrial',
        'whip cable',
      ],
      tags: ['tail'],
    },
    {
      name: 'muzzle',
      category: 'snout',
      options: [
        'blunt bulldozer',
        'boxy foundry',
        'hook wrecking',
        'narrow torch',
        'pug compact',
        'snout vented grate',
        'wide furnace',
        'wedge plow',
      ],
      tags: ['snout'],
    },
  ],
  abilities: [
    {
      name: 'flight',
      description: 'metal wings thunder as if the sky were a forge floor',
      category: 'movement',
      threatLevel: 2,
    },
    {
      name: 'breath weapon: fire',
      description: 'exhales a cone of molten metal spray and spark',
      category: 'attack',
      threatLevel: 4,
    },
    {
      name: 'iron born',
      description: 'folds scrap, ore, and architecture into crude new armor',
      category: 'utility',
      threatLevel: 2,
    },
  ],
  baseThreatLevel: 5,
  commonality: 2,
  tags: ['steel_dragon'],
  resourceProductNames: { scale: 'steel dragon scale' },
});
