import { buildTrueDragonSpecies } from './dragon_species_helpers';

export default buildTrueDragonSpecies({
  breedType: 'sun_dragon',
  name: 'sun dragon',
  pluralName: 'sun dragons',
  adjective: 'sun draconic',
  family: 'other',
  environments: ['desert', 'grassland', 'hill', 'mountain'],
  physicalTraitGeneratorConfigs: [
    {
      name: 'scales',
      category: 'scales',
      options: [
        'aurora flare rim',
        'blinding pale gold',
        'copper flare undertone',
        'dawn blush orange',
        'filament bright',
        'hammered solar disk',
        'honey flame metal',
        'molten white edge',
        'noon chrome',
        'saffron wash',
        'solar flare crackle',
        'white gold corona',
      ],
      tags: ['scales'],
    },
    {
      name: 'horns',
      category: 'horns',
      options: [
        'crown ray burst',
        'curl solar spiral',
        'fork flare',
        'helix prominence',
        'impala dawn pair',
        'ring nub corona',
        'straight zenith spike',
        'twisted sunspot',
      ],
      tags: ['horns'],
    },
    {
      name: 'eyes',
      category: 'eyes',
      options: [
        'black eclipse ring',
        'blue white furnace',
        'copper spark',
        'gold merciless bright',
        'orange plasma',
        'pink corona',
        'white pin glare',
        'yellow flare',
      ],
      tags: ['eyes'],
    },
    {
      name: 'wing membrane',
      category: 'wings',
      options: [
        'aurora stained',
        'banner solar',
        'heat veil thin',
        'mirage ripple',
        'pale dawn underside',
        'ribbed furnace',
        'sheet flare',
        'sunspot mottle',
      ],
      tags: ['wings'],
    },
    {
      name: 'tail',
      category: 'tail',
      options: [
        'comet mass',
        'fan heat',
        'flare fork',
        'heavy noon',
        'lash solar',
        'rake bright spine',
        'rudder sky',
        'whip sunstroke',
      ],
      tags: ['tail'],
    },
    {
      name: 'muzzle',
      category: 'snout',
      options: [
        'beak gull bright',
        'blunt hearth',
        'heavy sovereign',
        'hook flare',
        'noble roman blaze',
        'short grin warmth',
        'wide furnace',
        'wise creased gold',
      ],
      tags: ['snout'],
    },
  ],
  abilities: [
    {
      name: 'flight',
      description: 'throws mirrored glare from its wings like a second sun',
      category: 'movement',
      threatLevel: 3,
    },
    {
      name: 'breath weapon: fire',
      description: 'breathes a cone of desiccating radiance that chars before it burns',
      category: 'attack',
      threatLevel: 5,
    },
    {
      name: 'solar tide',
      description: 'drinks dawn and noon to mend flesh and temper',
      category: 'utility',
      threatLevel: 3,
    },
  ],
  baseThreatLevel: 6,
  commonality: 2,
  tags: ['sun_dragon'],
  resourceProductNames: { scale: 'sun dragon scale' },
});
