import { buildTrueDragonSpecies } from './dragon_species_helpers';

export default buildTrueDragonSpecies({
  breedType: 'topaz_dragon',
  name: 'topaz dragon',
  pluralName: 'topaz dragons',
  adjective: 'topaz draconic',
  family: 'gem',
  environments: ['desert', 'grassland', 'mountain'],
  physicalTraitGeneratorConfigs: [
    {
      name: 'scales',
      category: 'scales',
      options: [
        'amber honey metal',
        'bright citrine',
        'desert flash pale',
        'faceted gold wash',
        'flame orange undertone',
        'honeycomb dimple',
        'imperial topaz pink',
        'lemon bright',
        'melted butter gloss',
        'sandblasted sparkle',
        'solar flare rim',
        'white gold belly',
      ],
      tags: ['scales'],
    },
    {
      name: 'horns',
      category: 'horns',
      options: [
        'bolt forward',
        'crown burst',
        'curve sun ray',
        'impala twin',
        'knob solar',
        'ring of short rays',
        'swept horizon',
        'twisted gnomon',
      ],
      tags: ['horns'],
    },
    {
      name: 'eyes',
      category: 'eyes',
      options: [
        'black pupil furnace',
        'blue white glare',
        'gold ring',
        'honey warm',
        'melon bright',
        'molten pin',
        'orange spark',
        'plasma white',
      ],
      tags: ['eyes'],
    },
    {
      name: 'wing membrane',
      category: 'wings',
      options: [
        'dust devil edge',
        'gilded rib',
        'heat mirage mottle',
        'kite sun bleached',
        'pale dawn underside',
        'sand escher fold',
        'solar flare stain',
        'thin high glare',
      ],
      tags: ['wings'],
    },
    {
      name: 'tail',
      category: 'tail',
      options: [
        'club solar',
        'fan of heat fins',
        'flame fork',
        'heavy dune',
        'lash spark',
        'rake ember',
        'short grounded',
        'whip sunstroke',
      ],
      tags: ['tail'],
    },
    {
      name: 'muzzle',
      category: 'snout',
      options: [
        'blunt charger',
        'fox warm narrow',
        'happy heavy',
        'hook desert',
        'noble flare',
        'short grin',
        'wide furnace',
        'wise creased laugh',
      ],
      tags: ['snout'],
    },
  ],
  abilities: [
    {
      name: 'flight',
      description: 'leaves heat-shimmer contrails even on cool days',
      category: 'movement',
      threatLevel: 3,
    },
    {
      name: 'breath weapon: fire',
      description: 'breathes a lance of desiccating fire that boils blood dry',
      category: 'attack',
      threatLevel: 5,
    },
    {
      name: 'fear flare',
      description: 'projects awe and panic like a second sun',
      category: 'utility',
      threatLevel: 3,
    },
  ],
  baseThreatLevel: 5,
  commonality: 2,
  tags: ['topaz_dragon', 'gem'],
  resourceProductNames: { scale: 'topaz dragon scale' },
});
