import { buildTrueDragonSpecies } from './dragon_species_helpers';

export default buildTrueDragonSpecies({
  breedType: 'void_dragon',
  name: 'void dragon',
  pluralName: 'void dragons',
  adjective: 'void draconic',
  family: 'other',
  environments: ['hill', 'mountain', 'underdark'],
  physicalTraitGeneratorConfigs: [
    {
      name: 'scales',
      category: 'scales',
      options: [
        'absolute black swallow',
        'accretion disk ripple',
        'cosmic dust freckle',
        'dark matter matte',
        'eclipse bruise purple',
        'event horizon seam',
        'gravity lens bend',
        'nebula stain undertone',
        'null light edge',
        'singularity pinprick',
        'star corpse pale fleck',
        'vacuum frost rim',
      ],
      tags: ['scales'],
    },
    {
      name: 'horns',
      category: 'horns',
      options: [
        'backward gravity hook',
        'crown fractal split',
        'helix impossible',
        'obsidian null pair',
        'ring debris',
        'spike orbit',
        'twin singularity curve',
        'twisted fold',
      ],
      tags: ['horns'],
    },
    {
      name: 'eyes',
      category: 'eyes',
      options: [
        'absent pupil',
        'blue dwarf glint',
        'hollow white',
        'nebula green',
        'nothing ring',
        'red shift hunger',
        'silver distant',
        'violet vacuum',
      ],
      tags: ['eyes'],
    },
    {
      name: 'wing membrane',
      category: 'wings',
      options: [
        'black hole fold',
        'dark nebula web',
        'hole through stars',
        'paper thin infinite',
        'ragged cosmos',
        'sheet before time',
        'static snow',
        'void rip',
      ],
      tags: ['wings'],
    },
    {
      name: 'tail',
      category: 'tail',
      options: [
        'anchor singularity',
        'comet debris',
        'fork space tear',
        'heavy dead star',
        'lash vacuum',
        'rake dark matter',
        'serpent endless night',
        'whip gravity',
      ],
      tags: ['tail'],
    },
    {
      name: 'muzzle',
      category: 'snout',
      options: [
        'blunt annihilation',
        'elongate probe',
        'heavy tyrant void',
        'hook hunger',
        'narrow infinite',
        'nostril breathe absence',
        'short cruel fold',
        'wide maw silence',
      ],
      tags: ['snout'],
    },
  ],
  abilities: [
    {
      name: 'flight',
      description: 'falls upward through space that is not quite there',
      category: 'movement',
      threatLevel: 3,
    },
    {
      name: 'breath weapon: annihilating void',
      description: 'unleashes a ray that unravels matter into quiet nothing',
      category: 'attack',
      threatLevel: 6,
    },
    {
      name: 'unbound step',
      description: 'sidesteps distance and sealed doors along null geodesics',
      category: 'utility',
      threatLevel: 3,
    },
  ],
  baseThreatLevel: 7,
  commonality: 1,
  tags: ['void_dragon'],
  resourceProductNames: { scale: 'void dragon scale' },
});
