import { buildTrueDragonSpecies } from './dragon_species_helpers';

export default buildTrueDragonSpecies({
  breedType: 'white_dragon',
  name: 'white dragon',
  pluralName: 'white dragons',
  adjective: 'white draconic',
  family: 'chromatic',
  environments: ['arctic', 'coastal', 'mountain', 'tundra'],
  physicalTraitGeneratorConfigs: [
    {
      name: 'scales',
      category: 'scales',
      options: [
        'blue white frost',
        'bone pale',
        'crystalline ice-edged',
        'glacier blue',
        'hoarfrost rimed',
        'ivory with grey veining',
        'milky opal',
        'pearlescent snow',
        'polar white',
        'silver frost',
        'wind-scoured chalk',
        'winter blue-white',
      ],
      tags: ['scales'],
    },
    {
      name: 'horns and spikes',
      category: 'horns',
      options: [
        'backward curling ice-pale',
        'blunt ridged frost',
        'forked icicle',
        'knobbed crown',
        'serrated brow ridge',
        'short hooked',
        'stubby glacier',
        'twisted ramlike',
      ],
      tags: ['horns'],
    },
    {
      name: 'eyes',
      category: 'eyes',
      options: [
        'aquamarine',
        'ice blue',
        'mirror silver',
        'pale pink',
        'pinprick black on white',
        'sky blue',
        'slit ice',
        'snow blind blue',
        'watery grey',
      ],
      tags: ['eyes'],
    },
    {
      name: 'wing membrane',
      category: 'wings',
      options: [
        'almost transparent',
        'frosty mottled',
        'leathery pale grey',
        'powder blue',
        'tattered glacier tips',
        'thin arctic',
        'veined like cracked ice',
        'white with blue barring',
      ],
      tags: ['wings'],
    },
    {
      name: 'tail',
      category: 'tail',
      options: [
        'club ice-spiked',
        'fan of spines',
        'forked shallow',
        'heavy ridge-backed',
        'multiple small blades',
        'single keel spine',
        'split winter',
        'thick snowdrift',
      ],
      tags: ['tail'],
    },
    {
      name: 'muzzle',
      category: 'snout',
      options: [
        'blunt frost-snouted',
        'heavy icebreaker',
        'narrow pinched',
        'sawtooth jawline',
        'short wide',
        'sleek foxish',
        'thick scaled lips',
        'tusked lower',
      ],
      tags: ['snout'],
    },
  ],
  abilities: [
    {
      name: 'flight',
      description: 'winter winds barely trouble its vast wings',
      category: 'movement',
      threatLevel: 3,
    },
    {
      name: 'breath weapon: cold',
      description: 'exhales a killing cone of frost and rime',
      category: 'attack',
      threatLevel: 4,
    },
    {
      name: 'ice walker',
      description: 'burrows and hunts as easily through snowpack as stone',
      category: 'movement',
      threatLevel: 2,
    },
  ],
  baseThreatLevel: 5,
  commonality: 2,
  tags: ['white_dragon', 'chromatic'],
  resourceProductNames: { scale: 'white dragon scale' },
});
