import type RealmType from "./realm_type.js";

export function all(): RealmType[] {
  let kingdom = {
    name: "kingdom",
    minTiles: 10,
    maxTiles: 50,
    grantedTitle: {
      femaleTitle: "Queen",
      maleTitle: "King",
      femaleHonorific: "Queen",
      maleHonorific: "King",
      hasLands: true,
      landName: "Kingdom of",
      precedence: 7,
    },
    commonality: 5,
    isStandalone: true,
    parentType: null,
  };
  let empire = {
    name: "empire",
    minTiles: 50,
    maxTiles: 100,
    grantedTitle: {
      femaleTitle: "Empress",
      maleTitle: "Emperor",
      femaleHonorific: "Empress",
      maleHonorific: "Emperor",
      hasLands: true,
      landName: "Empire of",
      precedence: 8,
    },
    commonality: 5,
    isStandalone: true,
    parentType: null,
  };

  return [
    {
      name: "earldom",
      minTiles: 2,
      maxTiles: 4,
      grantedTitle: {
        femaleTitle: "Earl",
        maleTitle: "Earl",
        femaleHonorific: "Lady",
        maleHonorific: "Lord",
        hasLands: true,
        landName: "Earldom of",
        precedence: 2,
      },
      commonality: 5,
      isStandalone: false,
      parentType: kingdom,
    },
    {
      name: "county",
      minTiles: 4,
      maxTiles: 6,
      grantedTitle: {
        femaleTitle: "Countess",
        maleTitle: "Count",
        femaleHonorific: "Countess",
        maleHonorific: "Count",
        hasLands: true,
        landName: "County of",
        precedence: 3,
      },
      commonality: 20,
      isStandalone: false,
      parentType: kingdom,
    },
    {
      name: "barony",
      minTiles: 6,
      maxTiles: 8,
      grantedTitle: {
        femaleTitle: "Baroness",
        maleTitle: "Baron",
        femaleHonorific: "Baroness",
        maleHonorific: "Baron",
        hasLands: true,
        landName: "Barony of",
        precedence: 4,
      },
      commonality: 10,
      isStandalone: false,
      parentType: kingdom,
    },
    {
      name: "duchy",
      minTiles: 8,
      maxTiles: 10,
      grantedTitle: {
        femaleTitle: "Duchess",
        maleTitle: "Duke",
        femaleHonorific: "Duchess",
        maleHonorific: "Duke",
        hasLands: true,
        landName: "Duchy of",
        precedence: 5,
      },
      commonality: 5,
      isStandalone: false,
      parentType: kingdom,
    },
    {
      name: "grand duchy",
      minTiles: 10,
      maxTiles: 12,
      grantedTitle: {
        femaleTitle: "Grand Duchess",
        maleTitle: "Grand Duke",
        femaleHonorific: "Grand Duchess",
        maleHonorific: "Grand Duke",
        hasLands: true,
        landName: "Grand Duchy of",
        precedence: 6,
      },
      commonality: 2,
      isStandalone: false,
      parentType: kingdom,
    },
    {
      name: "principality",
      minTiles: 12,
      maxTiles: 14,
      grantedTitle: {
        femaleTitle: "Princess",
        maleTitle: "Prince",
        femaleHonorific: "Princess",
        maleHonorific: "Prince",
        hasLands: true,
        landName: "Principality of",
        precedence: 7,
      },
      commonality: 2,
      isStandalone: false,
      parentType: kingdom,
    },
    {
      name: "province",
      minTiles: 12,
      maxTiles: 14,
      grantedTitle: {
        femaleTitle: "Governor",
        maleTitle: "Governor",
        femaleHonorific: "Governor",
        maleHonorific: "Governor",
        hasLands: true,
        landName: "Province of",
        precedence: 7,
      },
      commonality: 1,
      isStandalone: false,
      parentType: empire,
    },
    kingdom,
    empire,
  ];
}
