/**
 * Potion catalog derived from the D&D 5.1 System Reference Document (SRD 5.1),
 * licensed under CC BY 4.0.
 * This work includes material from the SRD 5.1 by Wizards of the Coast LLC.
 */

import type { PotionCatalogEntry } from './potion_types';

const RESISTANCE_DAMAGE_TYPES = [
  'acid',
  'cold',
  'fire',
  'force',
  'lightning',
  'necrotic',
  'poison',
  'psychic',
  'radiant',
  'thunder',
] as const;

const resistanceVariants = RESISTANCE_DAMAGE_TYPES.map((damageType) => ({
  id: `resistance-${damageType}`,
  suffix: damageType.charAt(0).toUpperCase() + damageType.slice(1),
  rarity: 'uncommon' as const,
  baseValue: 25000,
  magnitude: 45,
  parameters: { kind: 'resistance' as const, damageType },
}));

export const potionCatalog: PotionCatalogEntry[] = [
  {
    id: 'animal-friendship',
    canonicalName: 'Potion of Animal Friendship',
    rarity: 'uncommon',
    baseValue: 25000,
    form: 'drink',
    tags: ['magical', 'potion', 'charm'],
    effectTemplate: {
      description: 'The drinker can cast animal friendship on beasts for 1 hour.',
      duration: { type: 'timed', unit: 'hour', value: 1 },
      intent: 'control',
      elements: ['nature', 'mind'],
      spheres: ['nature', 'mental'],
      magnitude: 35,
      parameters: { kind: 'spell', spellName: 'animal friendship' },
    },
    sensoryHints: {
      colors: ['muddy brown', 'earthy brown'],
      scents: ['damp fur', 'forest floor'],
    },
  },
  {
    id: 'clairvoyance',
    canonicalName: 'Potion of Clairvoyance',
    rarity: 'rare',
    baseValue: 150000,
    form: 'drink',
    tags: ['magical', 'potion', 'divination'],
    effectTemplate: {
      description: 'The drinker gains the effect of the clairvoyance spell.',
      duration: { type: 'timed', unit: 'minute', value: 10 },
      intent: 'sense',
      elements: ['mind', 'arcane'],
      spheres: ['mental', 'arcane'],
      magnitude: 60,
      parameters: { kind: 'spell', spellName: 'clairvoyance' },
    },
    sensoryHints: {
      colors: ['pale blue', 'milky white'],
      appearances: ['swirling motes of light'],
    },
  },
  {
    id: 'climbing',
    canonicalName: 'Potion of Climbing',
    rarity: 'common',
    baseValue: 5000,
    form: 'drink',
    tags: ['magical', 'potion', 'movement'],
    effectTemplate: {
      description: 'The drinker gains a climbing speed equal to their walking speed for 1 hour.',
      duration: { type: 'timed', unit: 'hour', value: 1 },
      intent: 'move',
      elements: ['earth'],
      spheres: ['physical'],
      magnitude: 25,
      parameters: { kind: 'bonus', description: 'climbing speed equals walking speed' },
    },
    sensoryHints: {
      colors: ['brown', 'amber'],
      viscosities: ['syrupy'],
    },
  },
  {
    id: 'diminution',
    canonicalName: 'Potion of Diminution',
    rarity: 'rare',
    baseValue: 150000,
    form: 'drink',
    tags: ['magical', 'potion', 'transformation'],
    effectTemplate: {
      description: 'The drinker gains the reduce effect of enlarge/reduce for 1d4 hours.',
      duration: { type: 'timed', unit: 'hour', value: 2, description: '1d4 hours' },
      intent: 'transform',
      elements: ['arcane'],
      spheres: ['physical', 'arcane'],
      magnitude: 55,
      parameters: { kind: 'spell', spellName: 'enlarge/reduce' },
    },
    sensoryHints: {
      colors: ['deep red', 'crimson'],
      appearances: ['contracting bead of color'],
    },
  },
  {
    id: 'flying',
    canonicalName: 'Potion of Flying',
    rarity: 'epic',
    baseValue: 750000,
    form: 'drink',
    tags: ['magical', 'potion', 'movement'],
    effectTemplate: {
      description:
        'The drinker gains a flying speed equal to their walking speed for 1 hour and can hover.',
      duration: { type: 'timed', unit: 'hour', value: 1 },
      intent: 'move',
      elements: ['air'],
      spheres: ['physical', 'elemental'],
      magnitude: 85,
      parameters: { kind: 'bonus', description: 'flying speed equals walking speed with hover' },
    },
    sensoryHints: {
      colors: ['clear', 'pale white'],
      appearances: [
        'cloudy white impurities drifting in clear liquid',
        'liquid floats at top of container',
      ],
    },
  },
  {
    id: 'gaseous-form',
    canonicalName: 'Potion of Gaseous Form',
    rarity: 'rare',
    baseValue: 150000,
    form: 'drink',
    tags: ['magical', 'potion', 'transformation'],
    effectTemplate: {
      description: 'The drinker gains the effect of gaseous form for 1 hour.',
      duration: { type: 'timed', unit: 'hour', value: 1 },
      intent: 'transform',
      elements: ['air', 'arcane'],
      spheres: ['physical', 'arcane'],
      magnitude: 65,
      parameters: { kind: 'spell', spellName: 'gaseous form' },
    },
    sensoryHints: {
      appearances: ['fog that moves and pours like water'],
      viscosities: ['misty'],
    },
  },
  {
    id: 'giant-strength',
    canonicalName: 'Potion of Giant Strength',
    rarity: 'uncommon',
    baseValue: 25000,
    form: 'drink',
    tags: ['magical', 'potion', 'strength'],
    effectTemplate: {
      description: 'The drinker Strength score changes for 1 hour based on giant type.',
      duration: { type: 'timed', unit: 'hour', value: 1 },
      intent: 'imbue',
      elements: ['earth', 'force'],
      spheres: ['physical'],
      magnitude: 40,
      parameters: { kind: 'strength', score: 21, giantType: 'hill' },
      statOffsets: { power: 15 },
    },
    sensoryHints: {
      colors: ['transparent'],
      appearances: ['sliver of fingernail floating in liquid'],
    },
    variants: [
      {
        id: 'giant-strength-hill',
        suffix: 'Hill Giant',
        rarity: 'uncommon',
        baseValue: 25000,
        magnitude: 40,
        parameters: { kind: 'strength', score: 21, giantType: 'hill' },
        statOffsets: { power: 15 },
      },
      {
        id: 'giant-strength-frost',
        suffix: 'Frost Giant',
        rarity: 'rare',
        baseValue: 150000,
        magnitude: 55,
        parameters: { kind: 'strength', score: 23, giantType: 'frost' },
        statOffsets: { power: 20 },
      },
      {
        id: 'giant-strength-stone',
        suffix: 'Stone Giant',
        rarity: 'rare',
        baseValue: 150000,
        magnitude: 55,
        parameters: { kind: 'strength', score: 23, giantType: 'stone' },
        statOffsets: { power: 20 },
      },
      {
        id: 'giant-strength-fire',
        suffix: 'Fire Giant',
        rarity: 'rare',
        baseValue: 200000,
        magnitude: 65,
        parameters: { kind: 'strength', score: 25, giantType: 'fire' },
        statOffsets: { power: 25 },
      },
      {
        id: 'giant-strength-cloud',
        suffix: 'Cloud Giant',
        rarity: 'epic',
        baseValue: 750000,
        magnitude: 80,
        parameters: { kind: 'strength', score: 27, giantType: 'cloud' },
        statOffsets: { power: 30 },
      },
      {
        id: 'giant-strength-storm',
        suffix: 'Storm Giant',
        rarity: 'legendary',
        baseValue: 1500000,
        magnitude: 95,
        parameters: { kind: 'strength', score: 29, giantType: 'storm' },
        statOffsets: { power: 40 },
      },
    ],
  },
  {
    id: 'growth',
    canonicalName: 'Potion of Growth',
    rarity: 'uncommon',
    baseValue: 25000,
    form: 'drink',
    tags: ['magical', 'potion', 'transformation'],
    effectTemplate: {
      description: 'The drinker gains the enlarge effect of enlarge/reduce for 1d4 hours.',
      duration: { type: 'timed', unit: 'hour', value: 2, description: '1d4 hours' },
      intent: 'transform',
      elements: ['life', 'arcane'],
      spheres: ['physical', 'arcane'],
      magnitude: 45,
      parameters: { kind: 'spell', spellName: 'enlarge/reduce' },
    },
    sensoryHints: {
      colors: ['red', 'crimson'],
      appearances: ['expanding bead of color in clear liquid'],
    },
  },
  {
    id: 'healing',
    canonicalName: 'Potion of Healing',
    rarity: 'common',
    baseValue: 5000,
    form: 'drink',
    tags: ['magical', 'potion', 'healing'],
    effectTemplate: {
      description: 'The drinker regains 2d4+2 hit points.',
      duration: { type: 'instantaneous' },
      intent: 'restore',
      elements: ['life'],
      spheres: ['physical'],
      magnitude: 20,
      parameters: { kind: 'healing', dice: '2d4+2' },
    },
    sensoryHints: {
      colors: ['red', 'ruby red'],
      flavors: ['cinnamon', 'sweet'],
    },
  },
  {
    id: 'heroism',
    canonicalName: 'Potion of Heroism',
    rarity: 'rare',
    baseValue: 150000,
    form: 'drink',
    tags: ['magical', 'potion', 'courage'],
    effectTemplate: {
      description: 'The drinker gains 10 temporary hit points and the effect of bless for 1 hour.',
      duration: { type: 'timed', unit: 'hour', value: 1 },
      intent: 'imbue',
      elements: ['light', 'divine'],
      spheres: ['spiritual', 'divine'],
      magnitude: 60,
      parameters: { kind: 'spell', spellName: 'bless' },
      statOffsets: { resilience: 10, power: 5 },
    },
    sensoryHints: {
      colors: ['blue'],
      appearances: ['bubbles and steam as if boiling'],
    },
  },
  {
    id: 'invisibility',
    canonicalName: 'Potion of Invisibility',
    rarity: 'epic',
    baseValue: 750000,
    form: 'drink',
    tags: ['magical', 'potion', 'illusion'],
    effectTemplate: {
      description:
        'The drinker becomes invisible for 1 hour; ends early if they attack or cast a spell.',
      duration: {
        type: 'conditional',
        unit: 'hour',
        value: 1,
        description: 'ends early on attack or spellcasting',
      },
      intent: 'alter',
      elements: ['shadow', 'arcane'],
      spheres: ['arcane', 'mental'],
      magnitude: 85,
      parameters: { kind: 'spell', spellName: 'invisibility' },
    },
    sensoryHints: {
      appearances: ['container looks empty but feels full of liquid'],
    },
  },
  {
    id: 'mind-reading',
    canonicalName: 'Potion of Mind Reading',
    rarity: 'rare',
    baseValue: 150000,
    form: 'drink',
    tags: ['magical', 'potion', 'divination'],
    effectTemplate: {
      description: 'The drinker can cast detect thoughts (save DC 13) for 1 minute.',
      duration: { type: 'timed', unit: 'minute', value: 1 },
      intent: 'sense',
      elements: ['mind', 'psionic'],
      spheres: ['mental', 'psionic'],
      magnitude: 55,
      parameters: { kind: 'spell', spellName: 'detect thoughts', saveDc: 13 },
    },
    sensoryHints: {
      colors: ['purple', 'dense purple'],
      appearances: ['ovoid cloud of pink floating in liquid'],
    },
  },
  {
    id: 'poison',
    canonicalName: 'Potion of Poison',
    rarity: 'uncommon',
    baseValue: 25000,
    form: 'drink',
    tags: ['magical', 'potion', 'poison'],
    effectTemplate: {
      description: 'Appears to be another potion but inflicts 4d6 poison damage on drinking.',
      duration: { type: 'instantaneous' },
      intent: 'destroy',
      elements: ['poison'],
      spheres: ['physical'],
      magnitude: 50,
      parameters: { kind: 'healing', dice: '4d6 poison damage' },
    },
    sensoryHints: {
      colors: ['varied'],
      appearances: ['indistinguishable from a harmless potion'],
    },
  },
  {
    id: 'resistance',
    canonicalName: 'Potion of Resistance',
    rarity: 'uncommon',
    baseValue: 25000,
    form: 'drink',
    tags: ['magical', 'potion', 'resistance'],
    effectTemplate: {
      description: 'The drinker gains resistance to one damage type for 1 hour.',
      duration: { type: 'timed', unit: 'hour', value: 1 },
      intent: 'protect',
      elements: ['arcane'],
      spheres: ['physical', 'elemental'],
      magnitude: 45,
      parameters: { kind: 'resistance', damageType: 'fire' },
    },
    variants: resistanceVariants,
  },
  {
    id: 'speed',
    canonicalName: 'Potion of Speed',
    rarity: 'epic',
    baseValue: 750000,
    form: 'drink',
    tags: ['magical', 'potion', 'haste'],
    effectTemplate: {
      description: 'The drinker gains the effect of haste for 1 minute.',
      duration: { type: 'timed', unit: 'minute', value: 1 },
      intent: 'alter',
      elements: ['time', 'force'],
      spheres: ['temporal', 'physical'],
      magnitude: 90,
      parameters: { kind: 'spell', spellName: 'haste' },
      statOffsets: { speed: 20 },
    },
    sensoryHints: {
      colors: ['yellow'],
      appearances: ['yellow fluid streaked with black', 'swirls on its own'],
    },
  },
  {
    id: 'water-breathing',
    canonicalName: 'Potion of Water Breathing',
    rarity: 'uncommon',
    baseValue: 25000,
    form: 'drink',
    tags: ['magical', 'potion', 'water'],
    effectTemplate: {
      description: 'The drinker can breathe underwater for 1 hour.',
      duration: { type: 'timed', unit: 'hour', value: 1 },
      intent: 'alter',
      elements: ['water', 'air'],
      spheres: ['physical', 'nature'],
      magnitude: 40,
      parameters: { kind: 'bonus', description: 'breathe underwater' },
    },
    sensoryHints: {
      colors: ['green', 'cloudy green'],
      scents: ['sea salt', 'ocean brine'],
      appearances: ['jellyfish-like bubble floating in liquid'],
    },
  },
  {
    id: 'oil-etherealness',
    canonicalName: 'Oil of Etherealness',
    rarity: 'rare',
    baseValue: 150000,
    form: 'oil',
    tags: ['magical', 'oil', 'ethereal'],
    effectTemplate: {
      description: 'Applied to a creature, grants etherealness for 1 hour.',
      duration: { type: 'timed', unit: 'hour', value: 1 },
      intent: 'transform',
      elements: ['aether', 'shadow'],
      spheres: ['planar', 'spiritual'],
      magnitude: 70,
      parameters: { kind: 'spell', spellName: 'etherealness' },
    },
    sensoryHints: {
      viscosities: ['oily', 'thin'],
      scents: ['incense', 'otherworldly'],
    },
  },
  {
    id: 'oil-sharpness',
    canonicalName: 'Oil of Sharpness',
    rarity: 'epic',
    baseValue: 750000,
    form: 'oil',
    tags: ['magical', 'oil', 'weapon'],
    effectTemplate: {
      description:
        'Coats a slashing or piercing weapon or ammunition; item becomes magical with +3 to attack and damage for 1 hour.',
      duration: { type: 'timed', unit: 'hour', value: 1 },
      intent: 'imbue',
      elements: ['metal', 'force'],
      spheres: ['physical', 'arcane'],
      magnitude: 90,
      parameters: { kind: 'bonus', description: '+3 weapon bonus for 1 hour' },
    },
    sensoryHints: {
      colors: ['clear'],
      appearances: ['gelatinous oil sparkling with ultrathin silver shards'],
      viscosities: ['gelatinous'],
    },
  },
  {
    id: 'oil-slipperiness',
    canonicalName: 'Oil of Slipperiness',
    rarity: 'uncommon',
    baseValue: 25000,
    form: 'oil',
    tags: ['magical', 'oil', 'movement'],
    effectTemplate: {
      description: 'Covers a Medium or smaller creature; grants freedom of movement for 8 hours.',
      duration: { type: 'timed', unit: 'hour', value: 8 },
      intent: 'protect',
      elements: ['oil', 'water'],
      spheres: ['physical'],
      magnitude: 45,
      parameters: { kind: 'spell', spellName: 'freedom of movement' },
    },
    sensoryHints: {
      colors: ['black', 'sticky black'],
      viscosities: ['thick and heavy in container', 'flows quickly when poured'],
    },
  },
  {
    id: 'philter-of-love',
    canonicalName: 'Philter of Love',
    rarity: 'uncommon',
    baseValue: 25000,
    form: 'drink',
    tags: ['magical', 'potion', 'charm'],
    effectTemplate: {
      description: 'The drinker becomes charmed by the first creature they see within 10 minutes.',
      duration: {
        type: 'timed',
        unit: 'minute',
        value: 10,
        description: 'charm lasts 1 hour after sighting',
      },
      intent: 'control',
      elements: ['mind', 'spirit'],
      spheres: ['mental', 'spiritual'],
      magnitude: 40,
      parameters: { kind: 'bonus', description: 'charmed by first creature seen' },
    },
    sensoryHints: {
      colors: ['pink', 'rose'],
      scents: ['roses', 'perfume'],
    },
  },
  {
    id: 'restorative-ointment',
    canonicalName: 'Restorative Ointment',
    rarity: 'uncommon',
    baseValue: 40000,
    form: 'ointment',
    tags: ['magical', 'ointment', 'healing'],
    effectTemplate: {
      description: 'Applied topically; cures poison and disease and heals 2d8+2 hit points.',
      duration: { type: 'instantaneous' },
      intent: 'restore',
      elements: ['life', 'nature'],
      spheres: ['physical', 'nature'],
      magnitude: 50,
      parameters: { kind: 'healing', dice: '2d8+2' },
    },
    sensoryHints: {
      viscosities: ['thick', 'salve-like'],
      scents: ['herbal', 'medicinal'],
      colors: ['green', 'pale green'],
    },
  },
];

export const HOMEBREW_POTION_CATALOG_IDS = [
  'homebrew-buff',
  'homebrew-curse',
  'homebrew-wild',
] as const;

export function getPotionCatalogEntry(id: string): PotionCatalogEntry | undefined {
  return potionCatalog.find((entry) => entry.id === id);
}

export function getAllPotionCatalogIds(): string[] {
  const ids: string[] = [];
  for (const entry of potionCatalog) {
    ids.push(entry.id);
    if (entry.variants) {
      for (const variant of entry.variants) {
        ids.push(variant.id);
      }
    }
  }
  return ids;
}

export const EXPECTED_SRD_BASE_CATALOG_IDS = [
  'animal-friendship',
  'clairvoyance',
  'climbing',
  'diminution',
  'flying',
  'gaseous-form',
  'giant-strength',
  'growth',
  'healing',
  'heroism',
  'invisibility',
  'mind-reading',
  'poison',
  'resistance',
  'speed',
  'water-breathing',
  'oil-etherealness',
  'oil-sharpness',
  'oil-slipperiness',
  'philter-of-love',
  'restorative-ointment',
] as const;
