export function categories() {
  return [
    {
      name: "infant",
      minAge: 0,
      maxAge: 1,
      femaleHeightBase: 50,
      maleHeightBase: 50,
      femaleHeightModifier: 20,
      maleHeightModifier: 20,
      femaleWeightBase: 6,
      maleWeightBase: 7,
      femaleWeightModifier: 4,
      maleWeightModifier: 4,
    },
    {
      name: "child",
      minAge: 2,
      maxAge: 12,
      femaleHeightBase: 100,
      maleHeightBase: 100,
      femaleHeightModifier: 40,
      maleHeightModifier: 40,
      femaleWeightBase: 20,
      maleWeightBase: 20,
      femaleWeightModifier: 20,
      maleWeightModifier: 20,
    },
    {
      name: "young adult",
      minAge: 13,
      maxAge: 19,
      femaleHeightBase: 152,
      maleHeightBase: 147,
      femaleHeightModifier: 10,
      maleHeightModifier: 40,
      femaleWeightBase: 46,
      maleWeightBase: 56,
      femaleWeightModifier: 10,
      maleWeightModifier: 10,
    },
    {
      name: "adult",
      minAge: 20,
      maxAge: 60,
      femaleHeightBase: 152,
      maleHeightBase: 163,
      femaleHeightModifier: 20,
      maleHeightModifier: 20,
      femaleWeightBase: 46,
      maleWeightBase: 70,
      femaleWeightModifier: 20,
      maleWeightModifier: 40,
    },
    {
      name: "elderly",
      minAge: 61,
      maxAge: 100,
      femaleHeightBase: 152,
      maleHeightBase: 163,
      femaleHeightModifier: 20,
      maleHeightModifier: 20,
      femaleWeightBase: 46,
      maleWeightBase: 70,
      femaleWeightModifier: 20,
      maleWeightModifier: 40,
    },
  ]
}
