import type { BiomeClassification } from './biome_types';

const classifications: BiomeClassification[] = [
  // Terrestrial - Tropical
  {
    name: 'tropical rainforest',
    altitudeMax: 0.6,
    altitudeMin: 0.0,
    humidityMax: 1.0,
    humidityMin: 0.8,
    temperatureMax: 45,
    temperatureMin: 22,
    faunaTypes: ['jaguar', 'parrot', 'monkey', 'sloth', 'tree frog'],
    faunaDensity: 0.9,
    vegetationTypes: ['mahogany tree', 'orchid', 'liana', 'bamboo', 'bromeliad'],
    vegetationDensity: 1.0,
    waterFeatures: ['river', 'stream', 'waterfall'],
    waterFeatureDensity: 0.8,
    isAquatic: false,
  },
  {
    name: 'tropical seasonal forest',
    altitudeMax: 0.6,
    altitudeMin: 0.0,
    humidityMax: 0.8,
    humidityMin: 0.5,
    temperatureMax: 40,
    temperatureMin: 18,
    faunaTypes: ['monkey', 'tiger', 'elephant', 'hornbill'],
    faunaDensity: 0.7,
    vegetationTypes: ['teak tree', 'bamboo', 'shrub'],
    vegetationDensity: 0.8,
    waterFeatures: ['river', 'pond'],
    waterFeatureDensity: 0.5,
    isAquatic: false,
  },
  {
    name: 'tropical savanna',
    altitudeMax: 0.7,
    altitudeMin: 0.1,
    humidityMax: 0.5,
    humidityMin: 0.2,
    temperatureMax: 40,
    temperatureMin: 20,
    faunaTypes: ['lion', 'zebra', 'elephant', 'giraffe', 'hyena'],
    faunaDensity: 0.8,
    vegetationTypes: ['acacia tree', 'baobab tree', 'tall grass'],
    vegetationDensity: 0.5,
    waterFeatures: ['waterhole', 'seasonal stream'],
    waterFeatureDensity: 0.3,
    isAquatic: false,
  },
  {
    name: 'subtropical desert',
    altitudeMax: 0.5,
    altitudeMin: 0.0,
    humidityMax: 0.2,
    humidityMin: 0.0,
    temperatureMax: 50,
    temperatureMin: 15,
    faunaTypes: ['camel', 'scorpion', 'fennec fox', 'hyena', 'vulture'],
    faunaDensity: 0.2,
    vegetationTypes: ['cactus', 'tumbleweed', 'date palm'],
    vegetationDensity: 0.1,
    waterFeatures: ['oasis'],
    waterFeatureDensity: 0.05,
    isAquatic: false,
  },

  // Terrestrial - Temperate
  {
    name: 'temperate rainforest',
    altitudeMax: 0.7,
    altitudeMin: 0.0,
    humidityMax: 1.0,
    humidityMin: 0.7,
    temperatureMax: 25,
    temperatureMin: 5,
    faunaTypes: ['bear', 'cougar', 'slug', 'elk', 'owl'],
    faunaDensity: 0.6,
    vegetationTypes: ['redwood tree', 'fern', 'moss', 'cedar tree'],
    vegetationDensity: 0.9,
    waterFeatures: ['stream', 'river'],
    waterFeatureDensity: 0.7,
    isAquatic: false,
  },
  {
    name: 'temperate deciduous forest',
    altitudeMax: 0.6,
    altitudeMin: 0.1,
    humidityMax: 0.7,
    humidityMin: 0.4,
    temperatureMax: 30,
    temperatureMin: -5,
    faunaTypes: ['deer', 'rabbit', 'squirrel', 'fox', 'raccoon', 'skunk', 'bear'],
    faunaDensity: 0.5,
    vegetationTypes: ['oak tree', 'maple tree', 'birch tree', 'elm tree', 'hickory tree'],
    vegetationDensity: 0.7,
    waterFeatures: ['river', 'stream', 'pond'],
    waterFeatureDensity: 0.4,
    isAquatic: false,
  },
  {
    name: 'mediterranean woodland',
    altitudeMax: 0.7,
    altitudeMin: 0.0,
    humidityMax: 0.5,
    humidityMin: 0.2,
    temperatureMax: 35,
    temperatureMin: 5,
    faunaTypes: ['coyote', 'jackrabbit', 'quail', 'lizard'],
    faunaDensity: 0.4,
    vegetationTypes: ['scrub oak', 'sagebrush', 'manzanita', 'olive tree'],
    vegetationDensity: 0.5,
    waterFeatures: ['seasonal creek'],
    waterFeatureDensity: 0.2,
    isAquatic: false,
  },
  {
    name: 'temperate grassland',
    altitudeMax: 0.6,
    altitudeMin: 0.1,
    humidityMax: 0.5,
    humidityMin: 0.2,
    temperatureMax: 35,
    temperatureMin: -10,
    faunaTypes: ['bison', 'prairie dog', 'antelope', 'hawk', 'badger'],
    faunaDensity: 0.5,
    vegetationTypes: ['grass', 'wildflower', 'clover'],
    vegetationDensity: 0.6,
    waterFeatures: ['river', 'stream'],
    waterFeatureDensity: 0.3,
    isAquatic: false,
  },
  {
    name: 'cold desert',
    altitudeMax: 0.8,
    altitudeMin: 0.2,
    humidityMax: 0.3,
    humidityMin: 0.0,
    temperatureMax: 25,
    temperatureMin: -15,
    faunaTypes: ['camel', 'gazelle', 'jackrabbit', 'snake'],
    faunaDensity: 0.2,
    vegetationTypes: ['sagebrush', 'bunchgrass', 'saxaul'],
    vegetationDensity: 0.15,
    waterFeatures: ['alkali flat', 'dry lake'],
    waterFeatureDensity: 0.05,
    isAquatic: false,
  },

  // Terrestrial - Cold / Boreal
  {
    name: 'boreal forest',
    altitudeMax: 0.9,
    altitudeMin: 0.1,
    humidityMax: 0.7,
    humidityMin: 0.3,
    temperatureMax: 20,
    temperatureMin: -30,
    faunaTypes: ['moose', 'bear', 'wolf', 'lynx', 'wolverine'],
    faunaDensity: 0.4,
    vegetationTypes: ['spruce tree', 'fir tree', 'pine tree', 'larch tree'],
    vegetationDensity: 0.8,
    waterFeatures: ['lake', 'river', 'bog'],
    waterFeatureDensity: 0.6,
    isAquatic: false,
  },
  {
    name: 'tundra',
    altitudeMax: 0.6,
    altitudeMin: 0.0,
    humidityMax: 0.6,
    humidityMin: 0.1,
    temperatureMax: 10,
    temperatureMin: -40,
    faunaTypes: ['caribou', 'arctic fox', 'lemming', 'snowy owl'],
    faunaDensity: 0.3,
    vegetationTypes: ['moss', 'lichen', 'dwarf shrub', 'sedge'],
    vegetationDensity: 0.4,
    waterFeatures: ['lake', 'permafrost melt'],
    waterFeatureDensity: 0.5,
    isAquatic: false,
  },
  {
    name: 'ice cap',
    altitudeMax: 1.0,
    altitudeMin: 0.0,
    humidityMax: 0.5,
    humidityMin: 0.0,
    temperatureMax: 0,
    temperatureMin: -60,
    faunaTypes: ['polar bear', 'penguin', 'seal'],
    faunaDensity: 0.1,
    vegetationTypes: ['algae'],
    vegetationDensity: 0.01,
    waterFeatures: ['glacier', 'ice sheet'],
    waterFeatureDensity: 0.0,
    isAquatic: false,
  },

  // Terrestrial - High Altitude / Special
  {
    name: 'alpine tundra',
    altitudeMax: 1.0,
    altitudeMin: 0.8,
    humidityMax: 0.6,
    humidityMin: 0.2,
    temperatureMax: 15,
    temperatureMin: -25,
    faunaTypes: ['mountain goat', 'marmot', 'pika', 'snow leopard'],
    faunaDensity: 0.2,
    vegetationTypes: ['cushion plant', 'moss', 'lichen'],
    vegetationDensity: 0.2,
    waterFeatures: ['glacial stream', 'tarn'],
    waterFeatureDensity: 0.3,
    isAquatic: false,
  },
  {
    name: 'montane forest',
    altitudeMax: 0.8,
    altitudeMin: 0.5,
    humidityMax: 0.8,
    humidityMin: 0.4,
    temperatureMax: 20,
    temperatureMin: -10,
    faunaTypes: ['cougar', 'elk', 'bear', 'eagle'],
    faunaDensity: 0.4,
    vegetationTypes: ['pine tree', 'fir tree', 'aspen tree'],
    vegetationDensity: 0.7,
    waterFeatures: ['mountain stream', 'waterfall'],
    waterFeatureDensity: 0.4,
    isAquatic: false,
  },
  {
    name: 'montane grassland',
    altitudeMax: 0.8,
    altitudeMin: 0.6,
    humidityMax: 0.5,
    humidityMin: 0.2,
    temperatureMax: 20,
    temperatureMin: -15,
    faunaTypes: ['llama', 'vicuna', 'condor', 'yak'],
    faunaDensity: 0.3,
    vegetationTypes: ['tussock grass', 'shrub'],
    vegetationDensity: 0.5,
    waterFeatures: ['stream'],
    waterFeatureDensity: 0.2,
    isAquatic: false,
  },
  {
    name: 'flooded grassland',
    altitudeMax: 0.3,
    altitudeMin: 0.0,
    humidityMax: 1.0,
    humidityMin: 0.6,
    temperatureMax: 35,
    temperatureMin: 15,
    faunaTypes: ['alligator', 'capybara', 'flamingo', 'anaconda', 'heron'],
    faunaDensity: 0.6,
    vegetationTypes: ['reed', 'papyrus', 'water lily', 'sawgrass'],
    vegetationDensity: 0.8,
    waterFeatures: ['swamp', 'marsh', 'shallow lake'],
    waterFeatureDensity: 0.9,
    isAquatic: false,
  },
  {
    name: 'mangrove forest',
    altitudeMax: 0.1,
    altitudeMin: 0.0,
    humidityMax: 1.0,
    humidityMin: 0.7,
    temperatureMax: 35,
    temperatureMin: 20,
    faunaTypes: ['crab', 'crocodile', 'mudskipper', 'pelican'],
    faunaDensity: 0.7,
    vegetationTypes: ['mangrove tree', 'salt-tolerant shrub'],
    vegetationDensity: 0.8,
    waterFeatures: ['brackish water', 'tidal channel'],
    waterFeatureDensity: 0.9,
    isAquatic: false,
  },

  // Aquatic / Semi-Aquatic
  {
    name: 'freshwater lake',
    altitudeMax: 0.8,
    altitudeMin: 0.0,
    humidityMax: 1.0,
    humidityMin: 0.5,
    temperatureMax: 30,
    temperatureMin: 0,
    faunaTypes: ['trout', 'bass', 'duck', 'beaver', 'frog'],
    faunaDensity: 0.6,
    vegetationTypes: ['algae', 'water lily', 'cattail'],
    vegetationDensity: 0.5,
    waterFeatures: ['lake depth', 'shoal'],
    waterFeatureDensity: 1.0,
    isAquatic: true,
  },
  {
    name: 'freshwater river',
    altitudeMax: 0.9,
    altitudeMin: 0.0,
    humidityMax: 1.0,
    humidityMin: 0.4,
    temperatureMax: 30,
    temperatureMin: 0,
    faunaTypes: ['salmon', 'catfish', 'otter', 'kingfisher'],
    faunaDensity: 0.5,
    vegetationTypes: ['algae', 'moss', 'riverweed'],
    vegetationDensity: 0.4,
    waterFeatures: ['rapids', 'eddy', 'waterfall'],
    waterFeatureDensity: 1.0,
    isAquatic: true,
  },
  {
    name: 'freshwater wetland',
    altitudeMax: 0.5,
    altitudeMin: 0.0,
    humidityMax: 1.0,
    humidityMin: 0.6,
    temperatureMax: 30,
    temperatureMin: -5,
    faunaTypes: ['crane', 'frog', 'turtle', 'dragonfly'],
    faunaDensity: 0.7,
    vegetationTypes: ['peat moss', 'sedge', 'pitcher plant', 'cypress tree'],
    vegetationDensity: 0.9,
    waterFeatures: ['bog', 'fen', 'marsh'],
    waterFeatureDensity: 0.9,
    isAquatic: true,
  },
  {
    name: 'intertidal zone',
    altitudeMax: 0.1,
    altitudeMin: 0.0,
    humidityMax: 1.0,
    humidityMin: 0.8,
    temperatureMax: 40,
    temperatureMin: -10,
    faunaTypes: ['starfish', 'crab', 'barnacle', 'seagull', 'anemone'],
    faunaDensity: 0.8,
    vegetationTypes: ['seaweed', 'kelp', 'seagrass'],
    vegetationDensity: 0.6,
    waterFeatures: ['tide pool', 'surge channel'],
    waterFeatureDensity: 0.9,
    isAquatic: true,
  },
  {
    name: 'kelp forest',
    altitudeMax: 0.0,
    altitudeMin: -0.2,
    humidityMax: 1.0,
    humidityMin: 1.0,
    temperatureMax: 20,
    temperatureMin: 5,
    faunaTypes: ['sea otter', 'seal', 'rockfish', 'sea urchin'],
    faunaDensity: 0.8,
    vegetationTypes: ['giant kelp', 'bull kelp'],
    vegetationDensity: 1.0,
    waterFeatures: ['ocean current'],
    waterFeatureDensity: 1.0,
    isAquatic: true,
  },
  {
    name: 'coral reef',
    altitudeMax: 0.0,
    altitudeMin: -0.2,
    humidityMax: 1.0,
    humidityMin: 1.0,
    temperatureMax: 30,
    temperatureMin: 22,
    faunaTypes: ['clownfish', 'shark', 'sea turtle', 'manta ray', 'octopus'],
    faunaDensity: 1.0,
    vegetationTypes: ['zooxanthellae', 'coralline algae', 'seagrass'],
    vegetationDensity: 0.7,
    waterFeatures: ['lagoon', 'reef drop-off'],
    waterFeatureDensity: 1.0,
    isAquatic: true,
  },
  {
    name: 'estuary',
    altitudeMax: 0.1,
    altitudeMin: 0.0,
    humidityMax: 1.0,
    humidityMin: 0.8,
    temperatureMax: 35,
    temperatureMin: 0,
    faunaTypes: ['oyster', 'blue crab', 'salmon', 'heron'],
    faunaDensity: 0.9,
    vegetationTypes: ['salt marsh grass', 'eelgrass', 'phytoplankton'],
    vegetationDensity: 0.8,
    waterFeatures: ['tidal flat', 'brackish pool'],
    waterFeatureDensity: 1.0,
    isAquatic: true,
  },
  {
    name: 'pelagic ocean',
    altitudeMax: 0.0,
    altitudeMin: -0.8,
    humidityMax: 1.0,
    humidityMin: 1.0,
    temperatureMax: 30,
    temperatureMin: 0,
    faunaTypes: ['whale', 'dolphin', 'tuna', 'jellyfish', 'albatross'],
    faunaDensity: 0.3,
    vegetationTypes: ['phytoplankton', 'sargassum'],
    vegetationDensity: 0.2,
    waterFeatures: ['ocean current', 'upwelling'],
    waterFeatureDensity: 1.0,
    isAquatic: true,
  },
  {
    name: 'abyssal ocean',
    altitudeMax: -0.5,
    altitudeMin: -1.0,
    humidityMax: 1.0,
    humidityMin: 1.0,
    temperatureMax: 4,
    temperatureMin: -1,
    faunaTypes: ['anglerfish', 'giant squid', 'tube worm', 'grenadier'],
    faunaDensity: 0.1,
    vegetationTypes: [],
    vegetationDensity: 0.0,
    waterFeatures: ['hydrothermal vent', 'abyssal plain', 'ocean trench'],
    waterFeatureDensity: 1.0,
    isAquatic: true,
  },
];

const classificationsByName: Record<string, BiomeClassification> = classifications.reduce(
  (acc, classification) => {
    acc[classification.name] = classification;
    return acc;
  },
  {} as Record<string, BiomeClassification>,
);

export function getAll(): BiomeClassification[] {
  return classifications;
}

export function getByName(name: string): BiomeClassification {
  const classification = classificationsByName[name];
  if (!classification) {
    throw new Error(`Biome classification ${name} not found`);
  }
  return classification;
}
