export default {
  name: "coniferous forest",
  temperature: 4,
  altitude: 3,
  humidity: 5,
  isAquatic: false,
  descriptions: [
    "This is an old forest region. Some of the trees here are bigger around than ten men linking arms could wrap around.",
    "Coniferous trees cover this area. Thick canopies give way to the occasional meadow.",
    "This forest is filled with conifers and light underbrush.",
    "Through the whispering boughs of towering evergreens, the forest floor is dappled in shifting patterns of sunlight and shadow, where the stillness is broken only by the gentle rustle of pine needles and the occasional call of a woodland creature.",
    "In the heart of the towering evergreen forest, where ancient trees stand sentinel and the scent of pine fills the air, lies a realm of serene beauty and solemn peace.",
    "The coniferous forest stretched on for leagues, its dark, foreboding depths concealing secrets and dangers unknown, while the whispering of the wind through the pines seemed to foretell of ominous portents lurking ahead.",
  ],
  features: [
    "The pine trees here grow tall.",
    "Vast areas of forest are broken occasionally by short, rocky cliffs.",
    "Dense areas of forest nearby hide rare animals.",
    "The occasional logging camp can be found on the outskirts of the forest here.",
    "Pine and spruce trees grow in multitudes here.",
    "The forest here is home to many beasts and other creatures.",
    "The forest floor is littered with a thick blanket of needles, muffling every footfall and leaving a fragrant scent in the air as if the very earth is breathing.",
    "The towering trunks of the ancient conifers rose high overhead, their needled branches casting dappled shade upon the mossy forest floor below.",
    "Shafts of sunlight illuminate the droplets of dew that cling to the delicate needles of the towering pines.",
    "The sound of a distant waterfall echoes through a misty glade.",
  ],
};
