export default {
  name: "mountain",
  temperature: 3,
  altitude: 10,
  humidity: 2,
  isAquatic: false,
  descriptions: [
    "This is a craggy mountainous region, with few trees and a lot of shrubs.",
    "This mountain area is covered in coniferous trees.",
    "This region is high in the mountains.",
    "The towering peaks of the rugged mountain range rise majestically into the sky, their snow-capped summits gleaming in the bright sunlight as they command awe and reverence from all who behold them.",
    "The barren and windswept slopes of the desolate mountain range stretch out as far as the eye can see, their jagged peaks looming like teeth against the stark and unforgiving landscape.",
    "The lush and verdant forests of the mountain range are alive with the sounds of rustling leaves and singing birds, and the air is cool and fresh as it flows down from the snow-capped peaks above.",
    "The craggy and unforgiving terrain of the mountain range is a treacherous and daunting obstacle for even the most skilled climbers, with sheer cliffs and narrow ledges that test the limits of human endurance and bravery.",
  ],
  features: [
    "Sheer cliffs are common here.",
    "An unusual number of trees grow here on the side of the mountain.",
    "This area is heavily forested, despite the extreme elevation.",
    "Low shrubs are particularly common.",
    "Wild goats thrive in the nearby cliffs.",
    "A towering and majestic waterfall cascades down the rocky face of the mountain, its thundering roar echoing through the valleys below and beckoning travelers from far and wide to witness its awe-inspiring beauty.",
    "The ominous and foreboding peak of the mountain looms in the distance, shrouded in dark clouds and seeming to radiate an eerie energy that sends shivers down the spines of all who dare to venture near.",
    "Alpine flora clings tenaciously to the rocky terrain, showcasing bright blooms and hardy leaves that withstand harsh conditions at high altitudes.",
  ],
};
