export default {
  name: "rainforest",
  temperature: 7,
  altitude: 3,
  humidity: 9,
  isAquatic: false,
  descriptions: [
    "This tropical rainforest is filled with lush vegetation.",
    "The heat of this rainforest is oppressive, but the thick canopy and frequent rains provide relief.",
    "Heavy rains, hot temperatures, and rampant predators make this jungle difficult to live in.",
    "The dense foliage of the rainforest towers overhead, as the sound of exotic birds and the occasional monkey fills the air.",
    "The lush foliage of the rainforest, alive with verdant shades of green, rustles gently in the breeze as shafts of sunlight filter through the dense canopy above.",
    "The hot rainforest seethes with life, the air thick with humidity and the sounds of chattering monkeys and chirping insects.",
    "The thick humidity of the rainforest permeates everything, from the damp earth and the clinging vines to the air itself, creating a verdant oasis of life.",
    "The dense canopy and undergrowth teem with life as the humid air carries the sounds of exotic birds and the occasional roar of a distant predator.",
  ],
  features: [
    "This area has beautiful waterfalls in between lush jungle foliage.",
    "A wide variety of colorful animals make their home here.",
    "Vicious jungle predators are unusually common here.",
    "The local flora provides many natural medicines unavailable elsewhere.",
    "Flowers of uncommon beauty draw many visitors to this area.",
    "A colossal stone temple lies deep within the jungle, its once polished walls now obscured by vines and moss.",
    "A majestic waterfall cascades down the rocky cliffs, surrounded by lush vegetation and the sounds of wildlife in the jungle.",
    "A towering statue of a forgotten deity stands amidst the dense jungle foliage, its eyes seeming to follow all who pass by.",
    "A strange and ominous cry in the jungle is often heard at night here.",
  ],
};
