import type { EquipmentItem, EquipmentList } from '../list.js';

export const adventuringGearList: EquipmentList = {
  title: 'Adventuring Gear',
  items: [
    { name: 'backpack', cost: 20 },
    { name: 'bedroll', cost: 8 },
    { name: 'blanket, wool', cost: 12 },
    { name: 'tent, small (2 person)', cost: 120 },
    { name: 'tent, pavilion (6 person)', cost: 480 },
    { name: 'rope, hemp (50 ft)', cost: 10 },
    { name: 'rope, silk (50 ft)', cost: 100 },
    { name: 'grappling hook', cost: 80 },
    { name: 'piton (6)', cost: 6 },
    { name: 'crowbar', cost: 12 },
    { name: 'hammer, iron', cost: 8 },
    { name: 'chalk (1 piece)', cost: 1 },
    { name: 'mirror, small steel', cost: 100 },
    { name: 'mirror, polished glass', cost: 240 },
    { name: 'manacles', cost: 150 },
    { name: 'lock, simple', cost: 200 },
    { name: 'lock, good', cost: 800 },
    { name: 'bell', cost: 10 },
    { name: 'whistle, signal', cost: 4 },
    { name: 'holy symbol, wooden', cost: 10 },
    { name: 'holy symbol, silver', cost: 500 },
    { name: 'holy symbol, gold', cost: 5000 },
    { name: 'component pouch', cost: 250 },
    { name: 'spellbook', cost: 5000 },
    { name: 'fishing tackle', cost: 20 },
    { name: 'net, hunting (25 sq ft)', cost: 40 },
    { name: 'chain (10 ft)', cost: 300 },
    { name: 'pole, 10 ft', cost: 2 },
    { name: 'ladder, wooden (10 ft)', cost: 20 },
    { name: 'shovel', cost: 8 },
    { name: "pick, miner's", cost: 60 },
    { name: 'sack, large', cost: 4 },
    { name: 'sack, small', cost: 2 },
    { name: 'caltrops (bag of 20)', cost: 10 },
    { name: 'marbles (bag)', cost: 2 },
    { name: 'soap (1 bar)', cost: 2 },
    { name: 'towel', cost: 4 },
    { name: 'whetstone', cost: 2 },
    { name: 'oil, weapon (1 flask)', cost: 6 },
  ],
};
