import { EquipmentItem, EquipmentList } from '../list.js';

export const adventuringGearList = new EquipmentList('Adventuring Gear', [
  new EquipmentItem('backpack', 20),
  new EquipmentItem('bedroll', 8),
  new EquipmentItem('blanket, wool', 12),
  new EquipmentItem('tent, small (2 person)', 120),
  new EquipmentItem('tent, pavilion (6 person)', 480),
  new EquipmentItem('rope, hemp (50 ft)', 10),
  new EquipmentItem('rope, silk (50 ft)', 100),
  new EquipmentItem('grappling hook', 80),
  new EquipmentItem('piton (6)', 6),
  new EquipmentItem('crowbar', 12),
  new EquipmentItem('hammer, iron', 8),
  new EquipmentItem('chalk (1 piece)', 1),
  new EquipmentItem('mirror, small steel', 100),
  new EquipmentItem('mirror, polished glass', 240),
  new EquipmentItem('manacles', 150),
  new EquipmentItem('lock, simple', 200),
  new EquipmentItem('lock, good', 800),
  new EquipmentItem('bell', 10),
  new EquipmentItem('whistle, signal', 4),
  new EquipmentItem('holy symbol, wooden', 10),
  new EquipmentItem('holy symbol, silver', 500),
  new EquipmentItem('holy symbol, gold', 5000),
  new EquipmentItem('component pouch', 250),
  new EquipmentItem('spellbook', 5000),
  new EquipmentItem('fishing tackle', 20),
  new EquipmentItem('net, hunting (25 sq ft)', 40),
  new EquipmentItem('chain (10 ft)', 300),
  new EquipmentItem('pole, 10 ft', 2),
  new EquipmentItem('ladder, wooden (10 ft)', 20),
  new EquipmentItem('shovel', 8),
  new EquipmentItem('pick, miner\'s', 60),
  new EquipmentItem('sack, large', 4),
  new EquipmentItem('sack, small', 2),
  new EquipmentItem('caltrops (bag of 20)', 10),
  new EquipmentItem('marbles (bag)', 2),
  new EquipmentItem('soap (1 bar)', 2),
  new EquipmentItem('towel', 4),
  new EquipmentItem('whetstone', 2),
  new EquipmentItem('oil, weapon (1 flask)', 6),
]);
