import { EquipmentItem, EquipmentList } from '../list.js';

export const drinksList = new EquipmentList('Drinks', [
  new EquipmentItem('ale, cheap (1 gallon)', 3),
  new EquipmentItem('ale, cheap (1 mug)', 1),
  new EquipmentItem('ale, good (1 gallon)', 6),
  new EquipmentItem('ale, good (1 mug)', 2),
  new EquipmentItem('beer, cheap (1 gallon)', 8),
  new EquipmentItem('beer, cheap (1 mug)', 2),
  new EquipmentItem('beer, good (1 gallon)', 24),
  new EquipmentItem('beer, good (1 mug)', 4),
  new EquipmentItem('mead, cheap (1 gallon)', 10),
  new EquipmentItem('mead, cheap (1 mug)', 3),
  new EquipmentItem('mead, good (1 gallon)', 28),
  new EquipmentItem('mead, good (1 mug)', 5),
  new EquipmentItem('wine, cheap (1 gallon)', 12),
  new EquipmentItem('wine, cheap (1 mug)', 2),
  new EquipmentItem('wine, good (1 gallon)', 32),
  new EquipmentItem('wine, good (1 mug)', 6),
  new EquipmentItem('cider, cheap (1 gallon)', 6),
  new EquipmentItem('cider, cheap (1 mug)', 1),
  new EquipmentItem('cider, good (1 gallon)', 16),
  new EquipmentItem('cider, good (1 mug)', 3),
  new EquipmentItem('spirits, cheap (1 pint)', 8),
  new EquipmentItem('spirits, good (1 pint)', 24),
  new EquipmentItem('milk (1 gallon)', 5),
  new EquipmentItem('milk (1 mug)', 1),
  new EquipmentItem('herbal tea, cheap (1 gallon)', 2),
  new EquipmentItem('herbal tea, cheap (1 mug)', 1),
  new EquipmentItem('herbal tea, good (1 gallon)', 6),
  new EquipmentItem('herbal tea, good (1 mug)', 2),
]);
