import type { EquipmentList } from '../list.js';

export const drinksList: EquipmentList = {
  title: 'Drinks',
  items: [
    { name: 'ale, cheap (1 gallon)', cost: 3 },
    { name: 'ale, cheap (1 mug)', cost: 1 },
    { name: 'ale, good (1 gallon)', cost: 6 },
    { name: 'ale, good (1 mug)', cost: 2 },
    { name: 'beer, cheap (1 gallon)', cost: 8 },
    { name: 'beer, cheap (1 mug)', cost: 2 },
    { name: 'beer, good (1 gallon)', cost: 24 },
    { name: 'beer, good (1 mug)', cost: 4 },
    { name: 'mead, cheap (1 gallon)', cost: 10 },
    { name: 'mead, cheap (1 mug)', cost: 3 },
    { name: 'mead, good (1 gallon)', cost: 28 },
    { name: 'mead, good (1 mug)', cost: 5 },
    { name: 'wine, cheap (1 gallon)', cost: 12 },
    { name: 'wine, cheap (1 mug)', cost: 2 },
    { name: 'wine, good (1 gallon)', cost: 32 },
    { name: 'wine, good (1 mug)', cost: 6 },
    { name: 'cider, cheap (1 gallon)', cost: 6 },
    { name: 'cider, cheap (1 mug)', cost: 1 },
    { name: 'cider, good (1 gallon)', cost: 16 },
    { name: 'cider, good (1 mug)', cost: 3 },
    { name: 'spirits, cheap (1 pint)', cost: 8 },
    { name: 'spirits, good (1 pint)', cost: 24 },
    { name: 'milk (1 gallon)', cost: 5 },
    { name: 'milk (1 mug)', cost: 1 },
    { name: 'herbal tea, cheap (1 gallon)', cost: 2 },
    { name: 'herbal tea, cheap (1 mug)', cost: 1 },
    { name: 'herbal tea, good (1 gallon)', cost: 6 },
    { name: 'herbal tea, good (1 mug)', cost: 2 },
  ],
};
