import type { EquipmentItem, EquipmentList } from '../list.js';

export const foodList: EquipmentList = {
  title: 'Food and Provisions',
  items: [
    { name: 'bread, white loaf (1 lb)', cost: 1 },
    { name: 'bread, rye loaf (1 lb)', cost: 1 },
    { name: 'bread, barley loaf (1 lb)', cost: 1 },
    { name: "biscuit, ship's (1 lb)", cost: 2 },
    { name: 'cheese, common (1 lb)', cost: 2 },
    { name: 'cheese, aged (1 lb)', cost: 6 },
    { name: 'butter (1 lb)', cost: 4 },
    { name: 'eggs (1 dozen)', cost: 3 },
    { name: 'flour, wheat (1 lb)', cost: 1 },
    { name: 'flour, rye (1 lb)', cost: 1 },
    { name: 'oats (1 lb)', cost: 1 },
    { name: 'rice (1 lb)', cost: 4 },
    { name: 'salt (1 lb)', cost: 6 },
    { name: 'sugar (1 lb)', cost: 12 },
    { name: 'honey (1 lb)', cost: 8 },
    { name: 'dried beans (1 lb)', cost: 2 },
    { name: 'dried peas (1 lb)', cost: 2 },
    { name: 'dried lentils (1 lb)', cost: 2 },
    { name: 'dried fish (1 lb)', cost: 4 },
    { name: 'salted fish (1 lb)', cost: 3 },
    { name: 'smoked fish (1 lb)', cost: 5 },
    { name: 'bacon (1 lb)', cost: 6 },
    { name: 'salt pork (1 lb)', cost: 4 },
    { name: 'sausage (1 lb)', cost: 5 },
    { name: 'dried beef (1 lb)', cost: 8 },
    { name: 'apple (1 lb)', cost: 1 },
    { name: 'dried apple (1 lb)', cost: 2 },
    { name: 'onion (1 lb)', cost: 1 },
    { name: 'garlic (1 lb)', cost: 2 },
    { name: 'cabbage (1 head)', cost: 1 },
    { name: 'turnip (1 lb)', cost: 1 },
    { name: 'carrot (1 lb)', cost: 1 },
    { name: 'nuts, mixed (1 lb)', cost: 4 },
    { name: 'dried fruit (1 lb)', cost: 6 },
    { name: 'spice, pepper (1 oz)', cost: 24 },
    { name: 'spice, cinnamon (1 oz)', cost: 32 },
    { name: 'spice, cloves (1 oz)', cost: 28 },
    { name: 'spice, ginger (1 oz)', cost: 20 },
    { name: 'spice, saffron (1 oz)', cost: 120 },
    { name: 'vinegar (1 pint)', cost: 2 },
    { name: 'olive oil (1 pint)', cost: 6 },
    { name: 'rations, trail (1 day)', cost: 5 },
    { name: 'rations, iron (1 week)', cost: 40 },
    { name: 'rations, siege (1 day)', cost: 2 },
  ],
};
