import { EquipmentItem, EquipmentList } from '../list.js';

export const foodList = new EquipmentList('Food and Provisions', [
  new EquipmentItem('bread, white loaf (1 lb)', 1),
  new EquipmentItem('bread, rye loaf (1 lb)', 1),
  new EquipmentItem('bread, barley loaf (1 lb)', 1),
  new EquipmentItem('biscuit, ship\'s (1 lb)', 2),
  new EquipmentItem('cheese, common (1 lb)', 2),
  new EquipmentItem('cheese, aged (1 lb)', 6),
  new EquipmentItem('butter (1 lb)', 4),
  new EquipmentItem('eggs (1 dozen)', 3),
  new EquipmentItem('flour, wheat (1 lb)', 1),
  new EquipmentItem('flour, rye (1 lb)', 1),
  new EquipmentItem('oats (1 lb)', 1),
  new EquipmentItem('rice (1 lb)', 4),
  new EquipmentItem('salt (1 lb)', 6),
  new EquipmentItem('sugar (1 lb)', 12),
  new EquipmentItem('honey (1 lb)', 8),
  new EquipmentItem('dried beans (1 lb)', 2),
  new EquipmentItem('dried peas (1 lb)', 2),
  new EquipmentItem('dried lentils (1 lb)', 2),
  new EquipmentItem('dried fish (1 lb)', 4),
  new EquipmentItem('salted fish (1 lb)', 3),
  new EquipmentItem('smoked fish (1 lb)', 5),
  new EquipmentItem('bacon (1 lb)', 6),
  new EquipmentItem('salt pork (1 lb)', 4),
  new EquipmentItem('sausage (1 lb)', 5),
  new EquipmentItem('dried beef (1 lb)', 8),
  new EquipmentItem('apple (1 lb)', 1),
  new EquipmentItem('dried apple (1 lb)', 2),
  new EquipmentItem('onion (1 lb)', 1),
  new EquipmentItem('garlic (1 lb)', 2),
  new EquipmentItem('cabbage (1 head)', 1),
  new EquipmentItem('turnip (1 lb)', 1),
  new EquipmentItem('carrot (1 lb)', 1),
  new EquipmentItem('nuts, mixed (1 lb)', 4),
  new EquipmentItem('dried fruit (1 lb)', 6),
  new EquipmentItem('spice, pepper (1 oz)', 24),
  new EquipmentItem('spice, cinnamon (1 oz)', 32),
  new EquipmentItem('spice, cloves (1 oz)', 28),
  new EquipmentItem('spice, ginger (1 oz)', 20),
  new EquipmentItem('spice, saffron (1 oz)', 120),
  new EquipmentItem('vinegar (1 pint)', 2),
  new EquipmentItem('olive oil (1 pint)', 6),
  new EquipmentItem('rations, trail (1 day)', 5),
  new EquipmentItem('rations, iron (1 week)', 40),
  new EquipmentItem('rations, siege (1 day)', 2),
]);
