import { EquipmentItem, EquipmentList } from '../list.js';

export const householdList = new EquipmentList('Household Goods', [
  new EquipmentItem('cook pot, iron', 40),
  new EquipmentItem('skillet, iron', 24),
  new EquipmentItem('cauldron, iron', 120),
  new EquipmentItem('kettle, copper', 60),
  new EquipmentItem('plate and bowl set', 16),
  new EquipmentItem('cup, wooden', 2),
  new EquipmentItem('cup, pewter', 8),
  new EquipmentItem('spoon, wooden', 1),
  new EquipmentItem('spoon, pewter', 4),
  new EquipmentItem('knife, table', 6),
  new EquipmentItem('fork, iron', 8),
  new EquipmentItem('tray, wooden', 6),
  new EquipmentItem('cutting board', 4),
  new EquipmentItem('mortar and pestle', 16),
  new EquipmentItem('blanket, wool', 12),
  new EquipmentItem('mattress, straw', 20),
  new EquipmentItem('mattress, feather', 120),
  new EquipmentItem('pillow', 8),
  new EquipmentItem('sheet, linen', 16),
  new EquipmentItem('stool, wooden', 12),
  new EquipmentItem('chair, wooden', 24),
  new EquipmentItem('table, small', 80),
  new EquipmentItem('table, trestle', 120),
  new EquipmentItem('broom', 4),
  new EquipmentItem('wash basin', 12),
  new EquipmentItem('chamber pot', 8),
  new EquipmentItem('iron, heated', 48),
  new EquipmentItem('sewing kit', 8),
]);
