import type { EquipmentItem, EquipmentList } from '../list.js';

export const householdList: EquipmentList = {
  title: 'Household Goods',
  items: [
    { name: 'cook pot, iron', cost: 40 },
    { name: 'skillet, iron', cost: 24 },
    { name: 'cauldron, iron', cost: 120 },
    { name: 'kettle, copper', cost: 60 },
    { name: 'plate and bowl set', cost: 16 },
    { name: 'cup, wooden', cost: 2 },
    { name: 'cup, pewter', cost: 8 },
    { name: 'spoon, wooden', cost: 1 },
    { name: 'spoon, pewter', cost: 4 },
    { name: 'knife, table', cost: 6 },
    { name: 'fork, iron', cost: 8 },
    { name: 'tray, wooden', cost: 6 },
    { name: 'cutting board', cost: 4 },
    { name: 'mortar and pestle', cost: 16 },
    { name: 'blanket, wool', cost: 12 },
    { name: 'mattress, straw', cost: 20 },
    { name: 'mattress, feather', cost: 120 },
    { name: 'pillow', cost: 8 },
    { name: 'sheet, linen', cost: 16 },
    { name: 'stool, wooden', cost: 12 },
    { name: 'chair, wooden', cost: 24 },
    { name: 'table, small', cost: 80 },
    { name: 'table, trestle', cost: 120 },
    { name: 'broom', cost: 4 },
    { name: 'wash basin', cost: 12 },
    { name: 'chamber pot', cost: 8 },
    { name: 'iron, heated', cost: 48 },
    { name: 'sewing kit', cost: 8 },
  ],
};
