import type { EquipmentList } from '../list.js';

export const medicalHerbalList: EquipmentList = {
  title: 'Medical and Herbal',
  items: [
    { name: 'bandages (1 roll)', cost: 4 },
    { name: "healer's kit", cost: 500 },
    { name: "surgeon's kit", cost: 1200 },
    { name: 'salve, healing (1 jar)', cost: 24 },
    { name: 'salve, burn (1 jar)', cost: 16 },
    { name: 'liniment (1 bottle)', cost: 12 },
    { name: 'smelling salts', cost: 8 },
    { name: 'splint, wooden', cost: 4 },
    { name: 'tourniquet', cost: 6 },
    { name: 'leeches (1 dozen)', cost: 8 },
    { name: 'herb, comfrey (1 bundle)', cost: 4 },
    { name: 'herb, willow bark (1 bundle)', cost: 3 },
    { name: 'herb, yarrow (1 bundle)', cost: 3 },
    { name: 'herb, chamomile (1 bundle)', cost: 2 },
    { name: 'herb, mint (1 bundle)', cost: 2 },
    { name: 'herb, lavender (1 bundle)', cost: 4 },
    { name: 'herb, foxglove (1 bundle)', cost: 6 },
    { name: 'herb, belladonna (1 bundle)', cost: 8 },
    { name: 'herb, valerian (1 bundle)', cost: 4 },
    { name: 'herb, garlic (1 bundle)', cost: 2 },
    { name: 'poultice, herbal (1 dose)', cost: 6 },
    { name: 'tonic, restorative (1 dose)', cost: 12 },
    { name: 'antitoxin (1 dose)', cost: 480 },
    { name: 'feverfew (1 bundle)', cost: 3 },
  ],
};
