import type { EquipmentList } from '../list.js';

export const religiousAlchemicalList: EquipmentList = {
  title: 'Religious and Alchemical',
  items: [
    { name: 'holy water (1 vial)', cost: 250 },
    { name: 'incense (1 lb)', cost: 48 },
    { name: 'incense sticks (20)', cost: 12 },
    { name: 'votive candle', cost: 2 },
    { name: 'censer, brass', cost: 240 },
    { name: 'thurible', cost: 480 },
    { name: 'relic case, silver', cost: 600 },
    { name: 'prayer beads', cost: 8 },
    { name: 'rosary, wooden', cost: 12 },
    { name: 'rosary, ivory', cost: 480 },
    { name: 'vestments, plain', cost: 480 },
    { name: 'vestments, fine', cost: 2400 },
    { name: 'altar cloth', cost: 120 },
    { name: 'communion wine (1 bottle)', cost: 48 },
    { name: 'communion wafer (100)', cost: 24 },
    { name: 'sulfur (1 lb)', cost: 8 },
    { name: 'saltpeter (1 lb)', cost: 12 },
    { name: 'bat guano (1 lb)', cost: 6 },
    { name: 'charcoal, activated (1 lb)', cost: 4 },
    { name: 'mercury (1 oz)', cost: 120 },
    { name: 'vitriol (1 oz)', cost: 16 },
    { name: 'sal ammoniac (1 lb)', cost: 10 },
    { name: 'dragon bile (1 vial)', cost: 480 },
    { name: 'mandrake root (1 root)', cost: 80 },
  ],
};
