import type { EquipmentItem, EquipmentList } from '../list.js';

export const servicesList: EquipmentList = {
  title: 'Services',
  items: [
    { name: 'inn stay, common (1 night)', cost: 4 },
    { name: 'inn stay, private room (1 night)', cost: 20 },
    { name: 'inn stay, suite (1 night)', cost: 80 },
    { name: 'meal, tavern common', cost: 2 },
    { name: 'meal, tavern good', cost: 6 },
    { name: 'meal, feast', cost: 48 },
    { name: 'ferry crossing', cost: 4 },
    { name: 'toll, bridge', cost: 2 },
    { name: 'toll, road (1 day)', cost: 8 },
    { name: 'stable, horse (1 night)', cost: 4 },
    { name: 'stable, feed (1 day)', cost: 2 },
    { name: 'bathhouse visit', cost: 4 },
    { name: 'laundry service', cost: 2 },
    { name: 'scribe (1 page)', cost: 24 },
    { name: 'scribe (1 letter)', cost: 12 },
    { name: 'messenger, local', cost: 8 },
    { name: 'messenger, long distance (1 day)', cost: 48 },
    { name: 'healing, minor wound', cost: 120 },
    { name: 'healing, serious wound', cost: 480 },
    { name: 'barber surgeon, bloodletting', cost: 24 },
    { name: 'guide, local (1 day)', cost: 24 },
    { name: 'guard hire (1 day)', cost: 48 },
    { name: 'porter (1 day)', cost: 12 },
    { name: 'teamster (1 day)', cost: 16 },
  ],
};
