import type { EquipmentList } from '../list.js';

export const toolsList: EquipmentList = {
  title: 'Tools',
  items: [
    { name: 'anvil', cost: 240 },
    { name: 'augur', cost: 12 },
    { name: 'axe', cost: 20 },
    { name: 'bellows', cost: 360 },
    { name: 'chisel', cost: 16 },
    { name: 'hammer', cost: 32 },
    { name: 'shovel', cost: 8 },
    { name: 'spade', cost: 4 },
    { name: 'spinning wheel', cost: 40 },
    { name: 'vice', cost: 176 },
    { name: 'yoke', cost: 96 },
    { name: 'saw', cost: 24 },
    { name: 'plane', cost: 20 },
    { name: 'drawknife', cost: 16 },
    { name: 'adze', cost: 18 },
    { name: 'scythe', cost: 28 },
    { name: 'sickle', cost: 6 },
    { name: 'plow', cost: 480 },
    { name: 'harrow', cost: 120 },
    { name: 'fishing net', cost: 32 },
    { name: 'fish trap', cost: 24 },
    { name: 'loom', cost: 240 },
    { name: 'mortar and pestle', cost: 16 },
    { name: "smith's tongs", cost: 48 },
    { name: "smith's hammer", cost: 40 },
    { name: 'trowel', cost: 8 },
    { name: 'pickaxe', cost: 36 },
    { name: 'crowbar', cost: 12 },
    { name: 'rope ladder (20 ft)', cost: 48 },
    { name: 'block and tackle', cost: 96 },
    { name: 'wheelbarrow', cost: 72 },
    { name: 'hand cart', cost: 120 },
    { name: 'iron pot hook', cost: 8 },
    { name: 'shears', cost: 12 },
    { name: 'needle kit', cost: 4 },
    { name: "carpenter's square", cost: 16 },
  ],
};
