import { EquipmentItem, EquipmentList } from '../list.js';

export const toolsList = new EquipmentList('Tools', [
  new EquipmentItem('anvil', 240),
  new EquipmentItem('augur', 12),
  new EquipmentItem('axe', 20),
  new EquipmentItem('bellows', 360),
  new EquipmentItem('chisel', 16),
  new EquipmentItem('hammer', 32),
  new EquipmentItem('shovel', 8),
  new EquipmentItem('spade', 4),
  new EquipmentItem('spinning wheel', 40),
  new EquipmentItem('vice', 176),
  new EquipmentItem('yoke', 96),
  new EquipmentItem('saw', 24),
  new EquipmentItem('plane', 20),
  new EquipmentItem('drawknife', 16),
  new EquipmentItem('adze', 18),
  new EquipmentItem('scythe', 28),
  new EquipmentItem('sickle', 6),
  new EquipmentItem('plow', 480),
  new EquipmentItem('harrow', 120),
  new EquipmentItem('fishing net', 32),
  new EquipmentItem('fish trap', 24),
  new EquipmentItem('loom', 240),
  new EquipmentItem('mortar and pestle', 16),
  new EquipmentItem('smith\'s tongs', 48),
  new EquipmentItem('smith\'s hammer', 40),
  new EquipmentItem('trowel', 8),
  new EquipmentItem('pickaxe', 36),
  new EquipmentItem('crowbar', 12),
  new EquipmentItem('rope ladder (20 ft)', 48),
  new EquipmentItem('block and tackle', 96),
  new EquipmentItem('wheelbarrow', 72),
  new EquipmentItem('hand cart', 120),
  new EquipmentItem('iron pot hook', 8),
  new EquipmentItem('shears', 12),
  new EquipmentItem('needle kit', 4),
  new EquipmentItem('carpenter\'s square', 16),
]);
