import { EquipmentItem, EquipmentList } from '../list.js';

export const tradeGoodsList = new EquipmentList('Trade Goods and Materials', [
  new EquipmentItem('wool (1 lb)', 2),
  new EquipmentItem('linen (1 yd)', 8),
  new EquipmentItem('cotton (1 lb)', 6),
  new EquipmentItem('silk (1 yd)', 120),
  new EquipmentItem('velvet (1 yd)', 240),
  new EquipmentItem('leather hide, cow', 48),
  new EquipmentItem('leather hide, goat', 24),
  new EquipmentItem('fur pelt, common', 40),
  new EquipmentItem('fur pelt, fine', 200),
  new EquipmentItem('iron ingot (1 lb)', 4),
  new EquipmentItem('steel ingot (1 lb)', 12),
  new EquipmentItem('copper ingot (1 lb)', 8),
  new EquipmentItem('tin ingot (1 lb)', 16),
  new EquipmentItem('lead ingot (1 lb)', 6),
  new EquipmentItem('silver ingot (1 oz)', 60),
  new EquipmentItem('gold ingot (1 oz)', 960),
  new EquipmentItem('copper wire (1 lb)', 12),
  new EquipmentItem('nails, iron (1 lb)', 4),
  new EquipmentItem('beeswax (1 lb)', 8),
  new EquipmentItem('tallow (1 lb)', 2),
  new EquipmentItem('lard (1 lb)', 3),
  new EquipmentItem('charcoal (1 lb)', 1),
  new EquipmentItem('coal (1 lb)', 2),
  new EquipmentItem('pitch (1 lb)', 3),
  new EquipmentItem('tar (1 lb)', 4),
  new EquipmentItem('resin (1 lb)', 6),
  new EquipmentItem('dye, common (1 oz)', 8),
  new EquipmentItem('dye, rare (1 oz)', 48),
  new EquipmentItem('glass pane', 24),
  new EquipmentItem('sand, fine (1 lb)', 1),
  new EquipmentItem('salt (1 lb)', 6),
  new EquipmentItem('sulfur (1 lb)', 8),
  new EquipmentItem('saltpeter (1 lb)', 12),
]);
