import type { EquipmentList } from '../list.js';

export const tradeGoodsList: EquipmentList = {
  title: 'Trade Goods and Materials',
  items: [
    { name: 'wool (1 lb)', cost: 2 },
    { name: 'linen (1 yd)', cost: 8 },
    { name: 'cotton (1 lb)', cost: 6 },
    { name: 'silk (1 yd)', cost: 120 },
    { name: 'velvet (1 yd)', cost: 240 },
    { name: 'leather hide, cow', cost: 48 },
    { name: 'leather hide, goat', cost: 24 },
    { name: 'fur pelt, common', cost: 40 },
    { name: 'fur pelt, fine', cost: 200 },
    { name: 'iron ingot (1 lb)', cost: 4 },
    { name: 'steel ingot (1 lb)', cost: 12 },
    { name: 'copper ingot (1 lb)', cost: 8 },
    { name: 'tin ingot (1 lb)', cost: 16 },
    { name: 'lead ingot (1 lb)', cost: 6 },
    { name: 'silver ingot (1 oz)', cost: 60 },
    { name: 'gold ingot (1 oz)', cost: 960 },
    { name: 'copper wire (1 lb)', cost: 12 },
    { name: 'nails, iron (1 lb)', cost: 4 },
    { name: 'beeswax (1 lb)', cost: 8 },
    { name: 'tallow (1 lb)', cost: 2 },
    { name: 'lard (1 lb)', cost: 3 },
    { name: 'charcoal (1 lb)', cost: 1 },
    { name: 'coal (1 lb)', cost: 2 },
    { name: 'pitch (1 lb)', cost: 3 },
    { name: 'tar (1 lb)', cost: 4 },
    { name: 'resin (1 lb)', cost: 6 },
    { name: 'dye, common (1 oz)', cost: 8 },
    { name: 'dye, rare (1 oz)', cost: 48 },
    { name: 'glass pane', cost: 24 },
    { name: 'sand, fine (1 lb)', cost: 1 },
    { name: 'salt (1 lb)', cost: 6 },
    { name: 'sulfur (1 lb)', cost: 8 },
    { name: 'saltpeter (1 lb)', cost: 12 },
  ],
};
