import type { EcologyRule } from './region_ecology_rule_types';

/** Explicit aliases, not substring matching or interpretation of species prose. */
export const BIOME_ENVIRONMENTS: Record<string, string[]> = {
  'tropical rainforest': ['forest'],
  'tropical seasonal forest': ['forest'],
  'tropical savanna': ['grassland'],
  'subtropical desert': ['desert'],
  'temperate rainforest': ['forest'],
  'temperate deciduous forest': ['forest'],
  'mediterranean woodland': ['forest'],
  'temperate grassland': ['grassland'],
  'cold desert': ['desert'],
  'boreal forest': ['forest', 'arctic'],
  tundra: ['arctic', 'grassland'],
  'ice cap': ['arctic'],
  'alpine tundra': ['arctic', 'mountain'],
  'montane forest': ['forest', 'mountain'],
  'montane grassland': ['grassland', 'mountain'],
  'flooded grassland': ['swamp', 'grassland'],
  'mangrove forest': ['swamp', 'forest', 'coastal'],
};
export const ECOLOGY_LABEL_ALIASES: Record<string, string> = {
  fox: 'red fox',
  caribou: 'reindeer',
  'mountain goat': 'goat',
  otter: 'river otter',
  seagull: 'gull',
  reed: 'reeds',
};
// These catalog labels require open-water communities or more precise habitat data.
export const UNSUPPORTED_ECOLOGY_LABELS = new Set([
  'water lily',
  'algae',
  'penguin',
  'seal',
  'polar bear',
  'date palm',
  'mudskipper',
]);
// Deliberate plant metadata: unknown labels keep role 'other', including unknown fantasy flora.
export const PRODUCER_LABELS = new Set([
  'mahogany tree',
  'orchid',
  'liana',
  'bamboo',
  'bromeliad',
  'teak tree',
  'shrub',
  'acacia tree',
  'baobab tree',
  'tall grass',
  'cactus',
  'tumbleweed',
  'redwood tree',
  'fern',
  'moss',
  'cedar tree',
  'oak tree',
  'maple tree',
  'birch tree',
  'elm tree',
  'hickory tree',
  'scrub oak',
  'sagebrush',
  'manzanita',
  'olive tree',
  'flax',
  'grass',
  'wildflower',
  'clover',
  'bunchgrass',
  'saxaul',
  'spruce tree',
  'fir tree',
  'pine tree',
  'larch tree',
  'dwarf shrub',
  'sedge',
  'cushion plant',
  'aspen tree',
  'tussock grass',
  'reed',
  'reeds',
  'papyrus',
  'sawgrass',
  'mangrove tree',
  'salt-tolerant shrub',
]);

/** Small authored suitability/niche rules supplement catalogs; no diets or relationships. */
export const ECOLOGY_RULES: readonly EcologyRule[] = [
  {
    label: 'flax',
    category: 'flora',
    roles: ['producer'],
    environments: ['grassland'],
    temperature: [10, 25],
    moisture: [0.3, 0.5],
    description:
      'Flax occurs in moderately moist temperate grassland; no cultivated acreage is implied.',
  },
  {
    label: 'papyrus',
    category: 'flora',
    roles: ['producer'],
    environments: ['swamp'],
    temperature: [15, 35],
    moisture: [0.6, 1],
    water: 'freshwater',
    description: 'Papyrus stands occupy the warm freshwater margins.',
  },
  {
    label: 'sawgrass',
    category: 'flora',
    roles: ['producer'],
    environments: ['swamp'],
    temperature: [15, 35],
    moisture: [0.6, 1],
    water: 'freshwater',
    description: 'Sawgrass grows along the warm wet banks.',
  },
  {
    label: 'mangrove tree',
    category: 'flora',
    roles: ['producer'],
    environments: ['coastal'],
    temperature: [20, 35],
    moisture: [0.7, 1],
    water: 'coast',
    description: 'Mangrove trees occupy the warm coastal land margins.',
  },
  {
    label: 'salt-tolerant shrub',
    category: 'flora',
    roles: ['producer'],
    environments: ['coastal'],
    temperature: [20, 35],
    moisture: [0.7, 1],
    water: 'coast',
    description: 'Salt-tolerant shrubs grow along the warm coastal margins.',
  },
  {
    label: 'flamingo',
    category: 'fauna',
    roles: ['other'],
    environments: ['swamp', 'coastal'],
    temperature: [15, 35],
    moisture: [0.6, 1],
    water: 'freshwater',
    description:
      'Flamingos occur at the warm freshwater margins; their feeding niche is unspecified.',
  },
  {
    label: 'crocodile',
    category: 'fauna',
    roles: ['predator'],
    environments: ['swamp', 'coastal'],
    temperature: [20, 35],
    moisture: [0.6, 1],
    water: 'freshwater',
    description: 'Crocodiles inhabit the warm freshwater banks.',
  },

  {
    label: 'reeds',
    category: 'flora',
    roles: ['producer'],
    environments: ['swamp'],
    temperature: [-5, 35],
    moisture: [0.6, 1],
    water: 'freshwater',
    description: 'Reed stands occupy the wet freshwater margins.',
  },
  {
    label: 'heron',
    category: 'fauna',
    roles: ['predator'],
    environments: ['swamp', 'forest', 'grassland', 'coastal'],
    temperature: [0, 35],
    moisture: [0.4, 1],
    water: 'freshwater',
    description: 'Herons forage along the freshwater margins.',
  },
  {
    label: 'crayfish',
    category: 'fauna',
    roles: ['scavenger'],
    environments: ['swamp', 'forest', 'grassland', 'hill'],
    temperature: [0, 30],
    moisture: [0.4, 1],
    water: 'freshwater',
    description: 'Crayfish occur at the wet freshwater banks.',
  },
  {
    label: 'ibex',
    category: 'fauna',
    roles: ['grazer'],
    environments: ['mountain'],
    temperature: [-20, 20],
    moisture: [0.2, 0.8],
    landforms: ['hill', 'mountain', 'highMountain'],
    description: 'Ibex range over the rocky upland slopes.',
  },
  {
    label: 'deer',
    category: 'fauna',
    roles: ['grazer'],
    environments: ['forest', 'grassland', 'hill'],
    temperature: [-15, 30],
    moisture: [0.3, 0.8],
    description: 'Deer inhabit the vegetated land patches.',
  },
  {
    label: 'rabbit',
    category: 'fauna',
    roles: ['grazer'],
    environments: ['forest', 'grassland', 'hill'],
    temperature: [-10, 30],
    moisture: [0.2, 0.8],
    description: 'Rabbits inhabit the vegetated land patches.',
  },
  {
    label: 'fennec fox',
    category: 'fauna',
    roles: ['predator'],
    environments: ['desert'],
    temperature: [15, 50],
    moisture: [0, 0.2],
    landforms: ['plain', 'hill'],
    description: 'Fennec foxes occupy the warm dry ground.',
  },
  {
    label: 'alligator',
    category: 'fauna',
    roles: ['predator'],
    environments: ['swamp'],
    temperature: [15, 35],
    moisture: [0.6, 1],
    water: 'freshwater',
    description: 'Alligators occur along the warm freshwater banks.',
  },
  {
    label: 'capybara',
    category: 'fauna',
    roles: ['grazer'],
    environments: ['swamp', 'grassland'],
    temperature: [15, 35],
    moisture: [0.6, 1],
    water: 'freshwater',
    description: 'Capybaras occupy the warm wet banks.',
  },
  {
    label: 'crab',
    category: 'fauna',
    roles: ['scavenger'],
    environments: ['coastal', 'swamp'],
    temperature: [5, 35],
    moisture: [0.5, 1],
    water: 'coast',
    description: 'Crabs occur along the coastal land margins.',
  },
  {
    label: "will o' the wisp",
    category: 'fantastical',
    roles: ['other'],
    environments: ['swamp'],
    temperature: [-5, 35],
    moisture: [0.6, 1],
    water: 'freshwater',
    description:
      'Will o’ the wisps bring wandering lights to the wet banks; no feeding role is asserted.',
  },
  {
    label: 'owlbear',
    category: 'fantastical',
    roles: ['other'],
    environments: ['forest'],
    temperature: [-10, 25],
    moisture: [0.4, 0.9],
    description: 'Owlbears inhabit sheltered woodland patches; their diet is unspecified.',
  },
];
