'use strict';

import ADNDArmor from './adndarmor';
import ADNDWeapon from './adndweapon';

export function getAmmoTypes(weapon: ADNDWeapon): ADNDWeapon[] {
  let result = [];

  if (weapon.name == 'blowgun') {
    result = [
      new ADNDWeapon(
        'blowgun barbed dart',
        1 * 10,
        1,
        'small',
        'piercing',
        -1,
        '1d3',
        '1d2',
        'blowgun dart',
      ),
      new ADNDWeapon(
        'blowgun needle',
        1 * 10,
        1,
        'small',
        'piercing',
        -1,
        '1d3',
        '1d2',
        'blowgun dart',
      ),
    ];
  } else if (weapon.category == 'bow') {
    result = [
      new ADNDWeapon(
        'flight arrow (12)',
        3 * 10,
        1,
        'small',
        'piercing',
        -1,
        '1d6',
        '1d6',
        'arrow',
      ),
      new ADNDWeapon('sheaf arrow (6)', 3 * 10, 1, 'small', 'piercing', -1, '1d8', '1d8', 'arrow'),
    ];
  } else if (weapon.name == 'Crossbow, hand') {
    result = [
      new ADNDWeapon(
        'hand quarrel',
        1 * 100,
        1,
        'small',
        'piercing',
        -1,
        '1d3',
        '1d2',
        'crossbow quarrel',
      ),
    ];
  } else if (weapon.name == 'Crossbow, light') {
    result = [
      new ADNDWeapon(
        'light quarrel',
        1 * 10,
        1,
        'small',
        'piercing',
        -1,
        '1d4',
        '1d4',
        'crossbow quarrel',
      ),
    ];
  } else if (weapon.name == 'crossbow, heavy') {
    result = [
      new ADNDWeapon(
        'heavy quarrel',
        2 * 10,
        1,
        'small',
        'piercing',
        -1,
        '1d4+1',
        '1d6+1',
        'crossbow quarrel',
      ),
    ];
  } else if (weapon.category == 'sling') {
    result = [
      new ADNDWeapon(
        'sling bullet',
        1,
        0,
        'small',
        'bludgeoning',
        -1,
        '1d4+1',
        '1d6+1',
        'sling bullet',
      ),
      new ADNDWeapon('sling stone', 0, 0, 'small', 'bludgeoning', -1, '1d4', '1d4', 'sling bullet'),
    ];
  }

  return result;
}

export function getArmor(): ADNDArmor[] {
  return [
    new ADNDArmor('banded mail', -7, 35, 300 * 100),
    new ADNDArmor('brigandine', -4, 35, 120 * 100),
    new ADNDArmor('bronze plate mail', -7, 45, 400 * 100),
    new ADNDArmor('chain mail', -6, 40, 75 * 100),
    new ADNDArmor('field plate', -8, 60, 2000 * 100),
    new ADNDArmor('full plate', -9, 70, 4000 * 100),
    new ADNDArmor('hide', -4, 30, 15 * 100),
    new ADNDArmor('leather', -2, 15, 5 * 100),
    new ADNDArmor('padded', -2, 10, 4 * 100),
    new ADNDArmor('plate mail', -7, 50, 600 * 100),
    new ADNDArmor('ring mail', -3, 30, 100 * 100),
    new ADNDArmor('scale mail', -4, 40, 120 * 100),
    new ADNDArmor('shield, body', -1, 15, 10 * 100),
    new ADNDArmor('shield, small buckler', -1, 10, 7 * 100),
    new ADNDArmor('shield, medium buckler', -1, 5, 3 * 100),
    new ADNDArmor('splint mail', -6, 40, 80 * 100),
    new ADNDArmor('studded leather', -4, 25, 20 * 100),
  ];
}

export function getWeapons(): ADNDWeapon[] {
  return [
    new ADNDWeapon('arquebus', 500 * 100, 10, 'medium', 'piercing', 15, '1d10', '1d10', 'musket'),
    new ADNDWeapon('battle axe', 5 * 100, 6, 'medium', 'slashing', 7, '1d8', '1d8', 'axe'),
    new ADNDWeapon('blowgun', 5 * 100, 1, 'large', 'piercing', 5, '1', '1', 'blowgun', true),
    new ADNDWeapon('short bow', 30 * 100, 2, 'medium', 'piercing', 7, '1', '1', 'bow', true),
    new ADNDWeapon('long bow', 75 * 100, 3, 'large', 'piercing', 8, '1', '1', 'bow', true),
    new ADNDWeapon(
      'composite short bow',
      75 * 100,
      2,
      'medium',
      'piercing',
      6,
      '1',
      '1',
      'bow',
      true,
    ),
    new ADNDWeapon(
      'composite long bow',
      100 * 100,
      3,
      'large',
      'piercing',
      7,
      '1',
      '1',
      'bow',
      true,
    ),
    new ADNDWeapon('club', 0, 3, 'medium', 'bludgeoning', 4, '1d6', '1d3', 'club'),
    new ADNDWeapon(
      'crossbow, hand',
      300 * 100,
      3,
      'small',
      'piercing',
      5,
      '0',
      '0',
      'crossbow',
      true,
    ),
    new ADNDWeapon(
      'crossbow, light',
      35 * 100,
      7,
      'medium',
      'piercing',
      7,
      '0',
      '0',
      'crossbow',
      true,
    ),
    new ADNDWeapon(
      'crossbow, heavy',
      50 * 100,
      14,
      'medium',
      'piercing',
      10,
      '0',
      '0',
      'crossbow',
      true,
    ),
    new ADNDWeapon('dagger', 2 * 100, 1, 'small', 'piercing', 2, '1d4', '1d3', 'dagger'),
    new ADNDWeapon('dart', 5 * 10, 0.5, 'small', 'piercing', 2, '1d4', '1d3', 'dart'),
    new ADNDWeapon(
      "footman's flail",
      15 * 100,
      15,
      'medium',
      'bludgeoning',
      7,
      '1d6+1',
      '2d4',
      'flail',
    ),
    new ADNDWeapon(
      "footman's mace",
      8 * 100,
      10,
      'medium',
      'bludgeoning',
      7,
      '1d6+1',
      '1d6',
      'mace',
    ),
    new ADNDWeapon("footman's pick", 8 * 100, 6, 'medium', 'piercing', 7, '1d6+1', '2d4', 'pick'),
    new ADNDWeapon('hand axe', 1 * 100, 5, 'medium', 'slashing', 4, '1d6', '1d4', 'axe'),
    new ADNDWeapon('harpoon', 20 * 100, 6, 'large', 'piercing', 7, '2d4', '2d6', 'spear'),
    new ADNDWeapon(
      "horseman's flail",
      8 * 100,
      5,
      'medium',
      'bludgeoning',
      6,
      '1d4+1',
      '1d4+1',
      'flail',
    ),
    new ADNDWeapon("horseman's mace", 5 * 100, 6, 'medium', 'bludgeoning', 6, '1d6', '1d4', 'mace'),
    new ADNDWeapon("horseman's pick", 7 * 100, 4, 'medium', 'piercing', 5, '1d4+1', '1d4', 'pick'),
    new ADNDWeapon('javelin', 5 * 10, 2, 'medium', 'piercing', 4, '1d6', '1d6', 'spear'),
    new ADNDWeapon('knife', 5 * 10, 0.5, 'small', 'piercing', 2, '1d3', '1d2', 'dagger'),
    new ADNDWeapon(
      'jousting lance',
      20 * 100,
      20,
      'large',
      'piercing',
      10,
      '1d3-1',
      '1d2-1',
      'lance',
    ),
    new ADNDWeapon(
      'heavy horse lance',
      15 * 100,
      15,
      'large',
      'piercing',
      8,
      '1d8+1',
      '3d6',
      'lance',
    ),
    new ADNDWeapon('light horse lance', 6 * 100, 5, 'large', 'piercing', 6, '1d6', '1d8', 'lance'),
    new ADNDWeapon(
      'medium horse lance',
      10 * 100,
      10,
      'large',
      'piercing',
      7,
      '1d6+1',
      '2d6',
      'lance',
    ),
    new ADNDWeapon('mancatcher', 30 * 100, 8, 'large', 'none', 7, '0', '0', 'nonlethal'),
    new ADNDWeapon('morningstar', 10 * 100, 12, 'medium', 'bludgeoning', 7, '2d4', '1d6+1', 'mace'),
    new ADNDWeapon('awl pike', 5 * 100, 12, 'large', 'piercing', 13, '1d6', '1d12', 'polearm'),
    new ADNDWeapon('bardiche', 7 * 100, 12, 'large', 'slashing', 9, '2d4', '2d6', 'polearm'),
    new ADNDWeapon(
      'bec de corbin',
      8 * 100,
      10,
      'large',
      'piercing/bludgeoning',
      9,
      '1d8',
      '1d6',
      'polearm',
    ),
    new ADNDWeapon(
      'bill-guisarme',
      7 * 100,
      15,
      'large',
      'piercing/slashing',
      10,
      '2d4',
      '1d10',
      'polearm',
    ),
    new ADNDWeapon(
      'fauchard',
      5 * 100,
      7,
      'large',
      'piercing/slashing',
      8,
      '1d6',
      '1d8',
      'polearm',
    ),
    new ADNDWeapon(
      'fauchard-fork',
      8 * 100,
      9,
      'large',
      'piercing/slashing',
      8,
      '1d8',
      '1d10',
      'polearm',
    ),
    new ADNDWeapon('glaive', 6 * 100, 8, 'large', 'slashing', 8, '1d6', '1d10', 'polearm'),
    new ADNDWeapon(
      'glaive-guisarme',
      10 * 100,
      10,
      'large',
      'piercing/slashing',
      9,
      '2d4',
      '2d6',
      'polearm',
    ),
    new ADNDWeapon('guisarme', 5 * 100, 8, 'large', 'slashing', 8, '2d4', '1d8', 'polearm'),
    new ADNDWeapon(
      'guisarme-voulge',
      8 * 100,
      15,
      'large',
      'piercing/slashing',
      10,
      '2d4',
      '2d4',
      'polearm',
    ),
    new ADNDWeapon(
      'halberd',
      10 * 100,
      15,
      'large',
      'piercing/slashing',
      9,
      '1d10',
      '2d6',
      'polearm',
    ),
    new ADNDWeapon(
      'hook fauchard',
      10 * 100,
      8,
      'large',
      'piercing/slashing',
      9,
      '1d4',
      '1d4',
      'polearm',
    ),
    new ADNDWeapon(
      'lucern hammer',
      7 * 100,
      15,
      'large',
      'piercing/bludgeoning',
      9,
      '2d4',
      '1d6',
      'polearm',
    ),
    new ADNDWeapon('military fork', 5 * 100, 7, 'large', 'piercing', 7, '1d8', '2d4', 'polearm'),
    new ADNDWeapon('partisan', 10 * 100, 8, 'large', 'piercing', 9, '1d6', '1d6+1', 'polearm'),
    new ADNDWeapon('ranseur', 6 * 100, 7, 'large', 'piercing', 8, '2d4', '2d4', 'polearm'),
    new ADNDWeapon('spetum', 5 * 100, 7, 'large', 'piercing', 8, '1d6+1', '1d6+1', 'polearm'),
    new ADNDWeapon('voulge', 5 * 100, 12, 'large', 'slashing', 10, '2d4', '2d4', 'polearm'),
    new ADNDWeapon('quarterstaff', 0, 4, 'large', 'bludgeoning', 4, '1d6', '1d6', 'staff'),
    new ADNDWeapon('scourge', 1 * 100, 2, 'small', 'none', 5, '1d4', '1d2', 'whip'),
    new ADNDWeapon('sickle', 6 * 10, 3, 'small', 'slashing', 4, '1d4+1', '1d4', 'sickle'),
    new ADNDWeapon('sling', 5, 0, 'small', 'bludgeoning', 6, '0', '0', 'sling', true),
    new ADNDWeapon('spear', 8 * 10, 5, 'medium', 'piercing', 6, '1d6', '1d8', 'spear'),
    new ADNDWeapon('staff sling', 2 * 10, 2, 'medium', 'none', 11, '0', '0', 'sling', true),
    new ADNDWeapon(
      'bastard sword, 1H',
      25 * 100,
      10,
      'medium',
      'slashing',
      6,
      '1d8',
      '1d12',
      'sword',
    ),
    new ADNDWeapon(
      'bastard sword, 2H',
      25 * 100,
      10,
      'medium',
      'slashing',
      8,
      '2d4',
      '2d8',
      'sword',
    ),
    new ADNDWeapon('broad sword', 10 * 100, 4, 'medium', 'slashing', 5, '2d4', '1d6+1', 'sword'),
    new ADNDWeapon('khopesh', 10 * 100, 7, 'medium', 'slashing', 9, '2d4', '1d6', 'sword'),
    new ADNDWeapon('long sword', 15 * 100, 4, 'medium', 'slashing', 5, '1d8', '1d12', 'sword'),
    new ADNDWeapon('scimitar', 15 * 100, 4, 'medium', 'slashing', 5, '1d8', '1d8', 'sword'),
    new ADNDWeapon('short sword', 10 * 100, 3, 'small', 'piercing', 3, '1d6', '1d8', 'sword'),
    new ADNDWeapon(
      'two-handed sword',
      50 * 100,
      15,
      'large',
      'slashing',
      10,
      '1d10',
      '3d6',
      'sword',
    ),
    new ADNDWeapon('trident', 10 * 10, 6, 'medium', 'piercing', 6, '1d6', '1d8', 'spear'),
    new ADNDWeapon('warhammer', 2 * 100, 6, 'medium', 'bludgeoning', 4, '1d4+1', '1d4', 'mace'),
    new ADNDWeapon('whip', 1 * 10, 2, 'medium', 'none', 8, '1d2', '1', 'whip'),
  ];
}
