import type { Decoration } from './equipment_types';

export const DECORATIONS: Record<string, Decoration> = {
  engraved: {
    name: 'engraved',
    description: 'This item has intricate engravings.',
    valueMultiplier: 1.5,
    tagsAdded: ['engraved'],
  },
  jeweled: {
    name: 'jeweled',
    description: 'This item is adorned with gemstones.',
    valueMultiplier: 5,
    tagsAdded: ['jeweled'],
  },
  ancient: {
    name: 'ancient',
    description: 'This item is very old.',
    valueMultiplier: 2,
    tagsAdded: ['ancient'],
  },
  ceremonial: {
    name: 'ceremonial',
    description: 'This item is intended for ceremonial use.',
    valueMultiplier: 3,
    tagsAdded: ['ceremonial'],
  },
  battle_worn: {
    name: 'battle-worn',
    description: 'This item has seen many battles.',
    valueMultiplier: 0.8,
    tagsAdded: ['battle-worn'],
    tagsExcluded: ['ceremonial', 'jeweled'],
  },
  gilded: {
    name: 'gilded',
    description: 'This item is plated with gold.',
    valueMultiplier: 3,
    tagsAdded: ['gilded'],
    tagsRequired: ['metal'],
  },
  runic: {
    name: 'runic',
    description: 'This item is carved with runes.',
    valueMultiplier: 1.2,
    tagsAdded: ['runic'],
  },
  spiked: {
    name: 'spiked',
    description: 'This item has decorative spikes.',
    valueMultiplier: 1.1,
    tagsAdded: ['spiked'],
    tagsRequired: ['armor'],
  },
  tattered: {
    name: 'tattered',
    description: 'This item is torn and tattered.',
    valueMultiplier: 0.5,
    tagsAdded: ['tattered'],
    tagsRequired: ['cloth'],
  },
  pristine: {
    name: 'pristine',
    description: 'This item looks brand new.',
    valueMultiplier: 1.5,
    tagsAdded: ['pristine'],
    tagsExcluded: ['battle-worn', 'tattered', 'rusty'],
  },
  winged: {
    name: 'winged',
    description: 'This item has wing motifs.',
    valueMultiplier: 1.2,
    tagsAdded: ['winged', 'air'],
  },
  bestial: {
    name: 'bestial',
    description: 'This item is decorated with images of beasts.',
    valueMultiplier: 1.2,
    tagsAdded: ['bestial', 'animals', 'hunting'],
  },
  artistic: {
    name: 'artistic',
    description: 'This item is a work of art.',
    valueMultiplier: 2.0,
    tagsAdded: ['artistic', 'art'],
  },
  leafy: {
    name: 'leafy',
    description: 'This item is engraved with leaves and vines.',
    valueMultiplier: 1.1,
    tagsAdded: ['leafy', 'nature', 'plants'],
  },
  balanced: {
    name: 'balanced',
    description: 'This item feels perfectly balanced.',
    valueMultiplier: 1.3,
    tagsAdded: ['balanced', 'balance', 'justice'],
  },
  chaotic: {
    name: 'chaotic',
    description: 'The patterns on this item seem to shift when not looked at directly.',
    valueMultiplier: 1.5,
    tagsAdded: ['chaotic', 'chaos'],
  },
  shadowed: {
    name: 'shadowed',
    description: 'This item seems to absorb light.',
    valueMultiplier: 1.4,
    tagsAdded: ['shadowed', 'darkness', 'thieves'],
  },
  radiant: {
    name: 'radiant',
    description: 'This item reflects light brilliantly.',
    valueMultiplier: 1.4,
    tagsAdded: ['radiant', 'light', 'sun', 'dawn'],
  },
  macabre: {
    name: 'macabre',
    description: 'This item is decorated with skulls and bones.',
    valueMultiplier: 1.2,
    tagsAdded: ['macabre', 'death', 'fear'],
  },
  demonic: {
    name: 'demonic',
    description: 'This item features disturbing imagery of demons.',
    valueMultiplier: 1.3,
    tagsAdded: ['demonic', 'demons', 'evil'],
  },
  broken: {
    name: 'broken',
    description: 'This item appears broken but functions perfectly.',
    valueMultiplier: 0.8,
    tagsAdded: ['broken', 'destruction'],
  },
  earthen: {
    name: 'earthen',
    description: 'This item looks as if it is hewn from solid rock.',
    valueMultiplier: 1.1,
    tagsAdded: ['earthen', 'earth'],
  },
  vile: {
    name: 'vile',
    description: 'This item makes one uneasy to look at.',
    valueMultiplier: 1.0,
    tagsAdded: ['vile', 'evil'],
  },
  blooming: {
    name: 'blooming',
    description: 'This item is decorated with flowers.',
    valueMultiplier: 1.2,
    tagsAdded: ['blooming', 'fertility', 'spring', 'summer'],
  },
  fiery: {
    name: 'fiery',
    description: 'This item uses flame motifs.',
    valueMultiplier: 1.3,
    tagsAdded: ['fiery', 'fire', 'summer'],
  },
  vulpine: {
    name: 'fox-themed',
    description: 'This item is decorated with images of foxes.',
    valueMultiplier: 1.2,
    tagsAdded: ['vulpine', 'foxes'],
  },
  holy: {
    name: 'holy',
    description: 'This item is engraved with religious symbols.',
    valueMultiplier: 1.5,
    tagsAdded: ['holy', 'good'],
  },
  grim: {
    name: 'grim',
    description: 'This item depicts harvest scenes.',
    valueMultiplier: 1.1,
    tagsAdded: ['grim', 'harvests'],
  },
  stormy: {
    name: 'stormy',
    description: 'This item depicts lightning and clouds.',
    valueMultiplier: 1.3,
    tagsAdded: ['stormy', 'lightning', 'thunder', 'sky'],
  },
  lovely: {
    name: 'lovely',
    description: 'This item is decorated with hearts and ribbons.',
    valueMultiplier: 1.2,
    tagsAdded: ['lovely', 'love'],
  },
  lucky: {
    name: 'lucky',
    description: 'This item has symbols of luck engraved on it.',
    valueMultiplier: 1.5,
    tagsAdded: ['lucky', 'luck'],
  },
  musical: {
    name: 'musical',
    description: 'This item has musical notes and instruments in its design.',
    valueMultiplier: 1.2,
    tagsAdded: ['musical', 'music'],
  },
  royal: {
    name: 'royal',
    description: 'This item displays the crests of nobility.',
    valueMultiplier: 2.0,
    tagsAdded: ['royal', 'nobility'],
  },
  oceanic: {
    name: 'oceanic',
    description: 'This item has wavelike patterns.',
    valueMultiplier: 1.2,
    tagsAdded: ['oceanic', 'oceans', 'water'],
  },
  sturdy: {
    name: 'sturdy',
    description: 'This item looks exceptionally solid.',
    valueMultiplier: 1.1,
    tagsAdded: ['sturdy', 'protection', 'strength', 'persistence'],
  },
  lunar: {
    name: 'lunar',
    description: 'This item is decorated with crescents and stars.',
    valueMultiplier: 1.3,
    tagsAdded: ['lunar', 'the moon'],
  },
  solar: {
    name: 'solar',
    description: 'This item is decorated with sunbursts.',
    valueMultiplier: 1.3,
    tagsAdded: ['solar', 'the sun'],
  },
  wealthy: {
    name: 'wealthy',
    description: 'This item is adorned with coins and gems.',
    valueMultiplier: 5.0,
    tagsAdded: ['wealthy', 'trade'],
  },
  traveling: {
    name: 'traveling',
    description: 'This item looks like it has seen the world.',
    valueMultiplier: 1.1,
    tagsAdded: ['traveling', 'travel'],
  },
  martial: {
    name: 'martial',
    description: 'This item is purely functional and deadly.',
    valueMultiplier: 1.1,
    tagsAdded: ['martial', 'war'],
  },
  frozen: {
    name: 'frozen',
    description: 'This item looks as if it is made of ice.',
    valueMultiplier: 1.3,
    tagsAdded: ['frozen', 'winter'],
  },
};
