import type { Enchantment } from './equipment_types';

export const ENCHANTMENTS: Record<string, Enchantment> = {
  flaming: {
    name: 'flaming',
    description: 'This item is wreathed in magical fire.',
    elements: ['fire'],
    spheres: ['physical'],
    intent: 'destroy',
    magnitude: 30,
    valueAdder: 50000,
    additionalDamage: '1d6',
    additionalDamageType: 'fire',
    tagsRequired: ['weapon'],
    tagsAdded: ['flaming', 'magical', 'fire'],
  },
  frost: {
    name: 'frost',
    description: 'This item is cold to the touch and covered in frost.',
    elements: ['ice'],
    spheres: ['physical'],
    intent: 'destroy',
    magnitude: 30,
    valueAdder: 50000,
    additionalDamage: '1d6',
    additionalDamageType: 'cold',
    tagsRequired: ['weapon'],
    tagsAdded: ['frost', 'magical', 'winter'],
  },
  shocking: {
    name: 'shocking',
    description: 'This item crackles with electricity.',
    elements: ['lightning'],
    spheres: ['physical'],
    intent: 'destroy',
    magnitude: 35,
    valueAdder: 200000,
    additionalDamage: '1d6',
    additionalDamageType: 'electricity',
    tagsRequired: ['weapon', 'metal'],
    tagsAdded: ['shocking', 'magical', 'lightning'],
  },
  vampiric: {
    name: 'vampiric',
    description: 'This weapon drains the life force of its victims.',
    elements: ['blood', 'death'],
    spheres: ['physical', 'spiritual'],
    intent: 'drain',
    magnitude: 60,
    valueAdder: 1000000,
    statOffsets: {
      damage: 1,
    },
    tagsRequired: ['weapon', 'slashing'],
    tagsAdded: ['vampiric', 'magical', 'evil'],
  },
  vorpal: {
    name: 'vorpal',
    description: 'This weapon is incredibly sharp and seeks to sever heads.',
    elements: ['void'],
    spheres: ['physical'],
    intent: 'destroy',
    magnitude: 80,
    valueAdder: 5000000,
    statOffsets: {
      damage: 5,
    },
    tagsRequired: ['weapon', 'slashing'],
    tagsAdded: ['vorpal', 'magical'],
  },
  deflecting: {
    name: 'deflecting',
    description: 'This armor seems to push attacks away.',
    elements: ['force'],
    spheres: ['physical'],
    intent: 'protect',
    magnitude: 40,
    valueAdder: 200000,
    statOffsets: {
      defense: 2,
    },
    tagsRequired: ['armor'],
    tagsAdded: ['deflecting', 'magical'],
  },
  fortified: {
    name: 'fortified',
    description: 'This armor is magically hardened.',
    elements: ['earth'],
    spheres: ['physical'],
    intent: 'protect',
    magnitude: 30,
    valueAdder: 50000,
    statOffsets: {
      defense: 1,
    },
    tagsRequired: ['armor'],
    tagsAdded: ['fortified', 'magical'],
  },
  shadow: {
    name: 'shadow',
    description: 'This item seems to absorb light.',
    elements: ['shadow'],
    spheres: ['physical'],
    intent: 'alter',
    magnitude: 40,
    valueAdder: 200000,
    tagsRequired: ['armor', 'light'],
    tagsAdded: ['shadow', 'magical', 'stealthy'],
  },
  holy: {
    name: 'holy',
    description: 'This item glows with a divine light.',
    elements: ['light', 'divine'],
    spheres: ['spiritual'],
    intent: 'imbue',
    magnitude: 50,
    valueAdder: 200000,
    statOffsets: {
      damage: 2,
    },
    tagsRequired: ['weapon'],
    tagsAdded: ['holy', 'magical', 'good'],
    tagsExcluded: ['evil', 'vampiric'],
  },
  unholy: {
    name: 'unholy',
    description: 'This item radiates a dark aura.',
    elements: ['shadow', 'death'],
    spheres: ['spiritual'],
    intent: 'imbue',
    magnitude: 50,
    valueAdder: 200000,
    statOffsets: {
      damage: 2,
    },
    tagsRequired: ['weapon'],
    tagsAdded: ['unholy', 'magical', 'evil'],
    tagsExcluded: ['good', 'holy'],
  },
  dancing: {
    name: 'dancing',
    description: 'This weapon can fight on its own.',
    elements: ['air', 'mind'],
    spheres: ['physical', 'mental'],
    intent: 'control',
    magnitude: 60,
    valueAdder: 1000000,
    tagsRequired: ['weapon'],
    tagsAdded: ['dancing', 'magical'],
  },
  ethereal: {
    name: 'ethereal',
    description: 'This item exists partially in the spirit realm.',
    elements: ['spirit', 'aether'],
    spheres: ['planar'],
    intent: 'move',
    magnitude: 70,
    valueAdder: 2000000,
    tagsAdded: ['ethereal', 'magical'],
  },
  // Domains
  air: {
    name: 'gusting',
    description: 'This item summons powerful gusts of wind.',
    elements: ['air'],
    spheres: ['physical'],
    intent: 'move',
    magnitude: 30,
    valueAdder: 50000,
    tagsAdded: ['magical', 'air'],
  },
  animals: {
    name: 'bestial',
    description: 'This item is adorned with animal motifs and grants power over beasts.',
    elements: ['life'],
    spheres: ['nature'],
    intent: 'control',
    magnitude: 30,
    valueAdder: 40000,
    tagsAdded: ['magical', 'animals'],
  },
  art: {
    name: 'artistic',
    description: 'This item is a masterpiece of craftsmanship, inspiring creativity.',
    elements: ['mind'],
    spheres: ['mental'],
    intent: 'create',
    magnitude: 20,
    valueAdder: 60000,
    tagsAdded: ['magical', 'art'],
  },
  autumn: {
    name: 'autumnal',
    description: 'This item carries the chill and decay of autumn.',
    elements: ['decay'],
    spheres: ['nature'],
    intent: 'alter',
    magnitude: 25,
    valueAdder: 45000,
    tagsAdded: ['magical', 'autumn'],
  },
  balance: {
    name: 'balanced',
    description: 'This item is perfectly balanced and seeks to equalize forces.',
    elements: ['force'],
    spheres: ['conceptual'],
    intent: 'restore',
    magnitude: 35,
    valueAdder: 70000,
    tagsAdded: ['magical', 'balance'],
  },
  chaos: {
    name: 'chaotic',
    description: 'This item shifts and changes, embodying unpredictability.',
    elements: ['chaos'],
    spheres: ['conceptual'],
    intent: 'alter',
    magnitude: 40,
    valueAdder: 80000,
    tagsAdded: ['magical', 'chaos'],
  },
  darkness: {
    name: 'dark',
    description: 'This item seems to absorb light and radiates darkness.',
    elements: ['shadow'],
    spheres: ['physical'],
    intent: 'alter',
    magnitude: 35,
    valueAdder: 60000,
    tagsAdded: ['magical', 'darkness'],
  },
  dawn: {
    name: 'dawning',
    description: 'This item acts as a beacon of new beginnings.',
    elements: ['light'],
    spheres: ['conceptual'],
    intent: 'create',
    magnitude: 30,
    valueAdder: 55000,
    tagsAdded: ['magical', 'dawn'],
  },
  demons: {
    name: 'demonic',
    description: 'This item is infused with the essence of demons.',
    elements: ['fire', 'shadow'],
    spheres: ['spiritual'],
    intent: 'imbue',
    magnitude: 55,
    valueAdder: 120000,
    tagsAdded: ['magical', 'demons', 'evil'],
  },
  destruction: {
    name: 'destructive',
    description: 'This item craves the annihilation of all things.',
    elements: ['fire', 'force'],
    spheres: ['physical'],
    intent: 'destroy',
    magnitude: 45,
    valueAdder: 90000,
    tagsAdded: ['magical', 'destruction'],
  },
  dusk: {
    name: 'dimming',
    description: 'This item brings the twilight and shadow.',
    elements: ['shadow'],
    spheres: ['conceptual'],
    intent: 'alter',
    magnitude: 30,
    valueAdder: 50000,
    tagsAdded: ['magical', 'dusk'],
  },
  earth: {
    name: 'earthen',
    description: 'This item is heavy and solid as the mountain.',
    elements: ['earth'],
    spheres: ['physical'],
    intent: 'protect',
    magnitude: 35,
    valueAdder: 65000,
    tagsAdded: ['magical', 'earth'],
  },
  evil: {
    name: 'vile',
    description: 'This item radiates pure malevolence.',
    elements: ['shadow', 'death'],
    spheres: ['spiritual'],
    intent: 'destroy',
    magnitude: 50,
    valueAdder: 100000,
    tagsAdded: ['magical', 'evil'],
  },
  fear: {
    name: 'terrifying',
    description: 'This item instills supernatural dread in those who view it.',
    elements: ['mind'],
    spheres: ['mental'],
    intent: 'control',
    magnitude: 40,
    valueAdder: 75000,
    tagsAdded: ['magical', 'fear'],
  },
  fertility: {
    name: 'fertile',
    description: 'This item causes life to bloom around it.',
    elements: ['life'],
    spheres: ['nature'],
    intent: 'create',
    magnitude: 30,
    valueAdder: 50000,
    tagsAdded: ['magical', 'fertility'],
  },
  fire: {
    name: 'flaming',
    description: 'This item is wreathed in magical fire.',
    elements: ['fire'],
    spheres: ['physical'],
    intent: 'destroy',
    magnitude: 30,
    valueAdder: 50000,
    additionalDamage: '1d6',
    additionalDamageType: 'fire',
    tagsRequired: ['weapon'],
    tagsAdded: ['flaming', 'magical', 'fire'],
  },
  foxes: {
    name: 'vulpine',
    description: 'This item grants the cunning and agility of a fox.',
    elements: ['life'],
    spheres: ['nature'],
    intent: 'control',
    magnitude: 25,
    valueAdder: 40000,
    tagsAdded: ['magical', 'foxes'],
  },
  good: {
    name: 'righteous',
    description: 'This item radiates a holy aura of goodness.',
    elements: ['light'],
    spheres: ['spiritual'],
    intent: 'imbue',
    magnitude: 50,
    valueAdder: 100000,
    tagsAdded: ['magical', 'good'],
  },
  harvests: {
    name: 'reaping',
    description: 'This item is associated with the gathering of crops and souls.',
    elements: ['death', 'life'],
    spheres: ['nature'],
    intent: 'drain',
    magnitude: 35,
    valueAdder: 60000,
    tagsAdded: ['magical', 'harvests'],
  },
  healing: {
    name: 'healing',
    description: 'This item knits flesh and mends bones.',
    elements: ['life'],
    spheres: ['physical'],
    intent: 'restore',
    magnitude: 45,
    valueAdder: 90000,
    tagsAdded: ['magical', 'healing'],
  },
  hope: {
    name: 'hopeful',
    description: 'This item brings courage and hope to its wielder.',
    elements: ['light', 'mind'],
    spheres: ['spiritual'],
    intent: 'imbue',
    magnitude: 40,
    valueAdder: 80000,
    tagsAdded: ['magical', 'hope'],
  },
  horses: {
    name: 'equine',
    description: 'This item embodies the speed and strength of the horse.',
    elements: ['life'],
    spheres: ['nature'],
    intent: 'move',
    magnitude: 30,
    valueAdder: 50000,
    tagsAdded: ['magical', 'horses'],
  },
  hunting: {
    name: 'hunting',
    description: 'This item acts as a bane to prey.',
    elements: ['nature'],
    spheres: ['physical'],
    intent: 'destroy',
    magnitude: 35,
    valueAdder: 65000,
    tagsAdded: ['magical', 'hunting'],
  },
  justice: {
    name: 'just',
    description: 'This item seeks to right wrongs.',
    elements: ['light', 'force'],
    spheres: ['conceptual'],
    intent: 'restore',
    magnitude: 45,
    valueAdder: 90000,
    tagsAdded: ['magical', 'justice'],
  },
  knowledge: {
    name: 'erudite',
    description: 'This item seems to whisper secrets to its bearer.',
    elements: ['mind'],
    spheres: ['mental'],
    intent: 'sense',
    magnitude: 40,
    valueAdder: 85000,
    tagsAdded: ['magical', 'knowledge'],
  },
  languages: {
    name: 'polyglot',
    description: 'This item allows communication across barriers.',
    elements: ['mind'],
    spheres: ['mental'],
    intent: 'sense',
    magnitude: 30,
    valueAdder: 60000,
    tagsAdded: ['magical', 'languages'],
  },
  law: {
    name: 'lawful',
    description: 'This item enforces order and structure.',
    elements: ['force'],
    spheres: ['conceptual'],
    intent: 'control',
    magnitude: 40,
    valueAdder: 80000,
    tagsAdded: ['magical', 'law'],
  },
  life: {
    name: 'living',
    description: 'This item pulses with vitality.',
    elements: ['life'],
    spheres: ['nature'],
    intent: 'create',
    magnitude: 50,
    valueAdder: 100000,
    tagsAdded: ['magical', 'life'],
  },
  lightning: {
    name: 'shocking',
    description: 'This item crackles with electricity.',
    elements: ['lightning'],
    spheres: ['physical'],
    intent: 'destroy',
    magnitude: 35,
    valueAdder: 200000,
    additionalDamage: '1d6',
    additionalDamageType: 'electricity',
    tagsRequired: ['weapon', 'metal'],
    tagsAdded: ['shocking', 'magical', 'lightning'],
  },
  light: {
    name: 'luminous',
    description: 'This item sheds bright light.',
    elements: ['light'],
    spheres: ['physical'],
    intent: 'create',
    magnitude: 30,
    valueAdder: 50000,
    tagsAdded: ['magical', 'light'],
  },
  love: {
    name: 'amorous',
    description: 'This item inflames passions.',
    elements: ['mind'],
    spheres: ['mental'],
    intent: 'control',
    magnitude: 40,
    valueAdder: 70000,
    tagsAdded: ['magical', 'love'],
  },
  luck: {
    name: 'lucky',
    description: 'This item bends probability in favor of the wielder.',
    elements: ['chaos'],
    spheres: ['conceptual'],
    intent: 'alter',
    magnitude: 50,
    valueAdder: 150000,
    tagsAdded: ['magical', 'luck'],
  },
  mercy: {
    name: 'merciful',
    description: 'This item stays lethality.',
    elements: ['life', 'light'],
    spheres: ['spiritual'],
    intent: 'protect',
    magnitude: 35,
    valueAdder: 60000,
    tagsAdded: ['magical', 'mercy'],
  },
  music: {
    name: 'melodic',
    description: 'This item creates beautiful sounds when used.',
    elements: ['sound'],
    spheres: ['spatial'],
    intent: 'create',
    magnitude: 25,
    valueAdder: 45000,
    tagsAdded: ['magical', 'music'],
  },
  nature: {
    name: 'natural',
    description: 'This item is in harmony with the wild.',
    elements: ['life', 'earth'],
    spheres: ['nature'],
    intent: 'protect',
    magnitude: 35,
    valueAdder: 70000,
    tagsAdded: ['magical', 'nature'],
  },
  nobility: {
    name: 'noble',
    description: 'This item imparts an air of majesty.',
    elements: ['mind'],
    spheres: ['mental'],
    intent: 'control',
    magnitude: 30,
    valueAdder: 80000,
    tagsAdded: ['magical', 'nobility'],
  },
  oceans: {
    name: 'oceanic',
    description: 'This item smells of salt spray and the sea.',
    elements: ['water'],
    spheres: ['physical'],
    intent: 'control',
    magnitude: 35,
    valueAdder: 65000,
    tagsAdded: ['magical', 'oceans'],
  },
  persistence: {
    name: 'persisting',
    description: 'This item urges its wielder to never give up.',
    elements: ['earth', 'force'],
    spheres: ['physical'],
    intent: 'alter',
    magnitude: 40,
    valueAdder: 80000,
    tagsAdded: ['magical', 'persistence'],
  },
  plants: {
    name: 'verdant',
    description: 'This item encourages plant growth.',
    elements: ['life', 'earth'],
    spheres: ['nature'],
    intent: 'create',
    magnitude: 30,
    valueAdder: 50000,
    tagsAdded: ['magical', 'plants'],
  },
  protection: {
    name: 'protecting',
    description: 'This item shields its wielder from harm.',
    elements: ['force'],
    spheres: ['physical'],
    intent: 'protect',
    magnitude: 45,
    valueAdder: 90000,
    tagsAdded: ['magical', 'protection'],
  },
  revenge: {
    name: 'vengeful',
    description: 'This item burns with the desire for retribution.',
    elements: ['shadow', 'mind'],
    spheres: ['mental'],
    intent: 'destroy',
    magnitude: 40,
    valueAdder: 85000,
    tagsAdded: ['magical', 'revenge'],
  },
  sky: {
    name: 'aerial',
    description: 'This item feels light as a feather.',
    elements: ['air'],
    spheres: ['physical'],
    intent: 'move',
    magnitude: 30,
    valueAdder: 60000,
    tagsAdded: ['magical', 'sky'],
  },
  spring: {
    name: 'vernal',
    description: 'This item embodies the renewal of spring.',
    elements: ['life'],
    spheres: ['nature'],
    intent: 'create',
    magnitude: 30,
    valueAdder: 55000,
    tagsAdded: ['magical', 'spring'],
  },
  strength: {
    name: 'strong',
    description: 'This item augments physical power.',
    elements: ['force'],
    spheres: ['physical'],
    intent: 'imbue',
    magnitude: 40,
    valueAdder: 80000,
    tagsAdded: ['magical', 'strength'],
  },
  summer: {
    name: 'summer',
    description: 'This item radiates the heat of summer.',
    elements: ['fire', 'light'],
    spheres: ['nature'],
    intent: 'alter',
    magnitude: 30,
    valueAdder: 55000,
    tagsAdded: ['magical', 'summer'],
  },
  thieves: {
    name: 'stealthy',
    description: 'This item aids in remaining unseen.',
    elements: ['shadow'],
    spheres: ['physical'],
    intent: 'alter',
    magnitude: 35,
    valueAdder: 70000,
    tagsAdded: ['magical', 'thieves'],
  },
  'the moon': {
    name: 'lunar',
    description: 'This item glows with a soft, pale light.',
    elements: ['light', 'shadow'],
    spheres: ['celestial'],
    intent: 'create',
    magnitude: 35,
    valueAdder: 70000,
    tagsAdded: ['magical', 'the moon'],
  },
  'the sun': {
    name: 'solar',
    description: 'This item burns with the intensity of the sun.',
    elements: ['light', 'fire'],
    spheres: ['celestial'],
    intent: 'destroy',
    magnitude: 50,
    valueAdder: 120000,
    tagsAdded: ['magical', 'the sun'],
  },
  thunder: {
    name: 'thunderous',
    description: 'This item booms with the sound of thunder.',
    elements: ['sound'],
    spheres: ['physical'],
    intent: 'create',
    magnitude: 35,
    valueAdder: 70000,
    tagsAdded: ['magical', 'thunder'],
  },
  time: {
    name: 'timeless',
    description: 'This item seems untouched by the passage of time.',
    elements: ['time'],
    spheres: ['conceptual'],
    intent: 'protect',
    magnitude: 60,
    valueAdder: 200000,
    tagsAdded: ['magical', 'time'],
  },
  trade: {
    name: 'mercantile',
    description: 'This item causes the bearer to excel in trade and negotiation.',
    elements: ['mind'],
    spheres: ['mental'],
    intent: 'summon',
    magnitude: 25,
    valueAdder: 50000,
    tagsAdded: ['magical', 'trade'],
  },
  travel: {
    name: 'traveling',
    description:
      'This item aids in long journeys, allowing the bearer to travel swiftly and without fatigue.',
    elements: ['flesh'],
    spheres: ['physical'],
    intent: 'move',
    magnitude: 30,
    valueAdder: 60000,
    tagsAdded: ['magical', 'travel'],
  },
  trickery: {
    name: 'tricky',
    description: 'This item deceives the senses.',
    elements: ['mind', 'chaos'],
    spheres: ['mental'],
    intent: 'alter',
    magnitude: 40,
    valueAdder: 80000,
    tagsAdded: ['magical', 'trickery'],
  },
  war: {
    name: 'warlike',
    description: 'This item thirsts for battle.',
    elements: ['force', 'blood'],
    spheres: ['physical'],
    intent: 'destroy',
    magnitude: 45,
    valueAdder: 90000,
    tagsAdded: ['magical', 'war'],
  },
  water: {
    name: 'aquatic',
    description: 'This item is at home in the water.',
    elements: ['water'],
    spheres: ['physical'],
    intent: 'control',
    magnitude: 30,
    valueAdder: 60000,
    tagsAdded: ['magical', 'water'],
  },
  winter: {
    name: 'frost',
    description: 'This item is cold to the touch and covered in frost.',
    elements: ['ice'],
    spheres: ['physical'],
    intent: 'destroy',
    magnitude: 30,
    valueAdder: 50000,
    additionalDamage: '1d6',
    additionalDamageType: 'cold',
    tagsRequired: ['weapon'],
    tagsAdded: ['frost', 'magical', 'winter'],
  },
  wisdom: {
    name: 'wise',
    description: 'This item grants insight and clarity.',
    elements: ['mind'],
    spheres: ['mental'],
    intent: 'sense',
    magnitude: 40,
    valueAdder: 85000,
    tagsAdded: ['magical', 'wisdom'],
  },
};
