import type { Enchantment } from './equipment_types';

export const ENCHANTMENTS: Record<string, Enchantment> = {
  flaming: {
    name: 'Flaming',
    description: 'This item is wreathed in magical fire.',
    elements: ['fire'],
    spheres: ['physical'],
    intent: 'destroy',
    magnitude: 30,
    valueAdder: 50000,
    statOffsets: {
      damage: 2,
    },
    tagsRequired: ['weapon'],
    tagsAdded: ['flaming', 'magical'],
  },
  frost: {
    name: 'Frost',
    description: 'This item is cold to the touch and covered in frost.',
    elements: ['ice'],
    spheres: ['physical'],
    intent: 'destroy',
    magnitude: 30,
    valueAdder: 50000,
    statOffsets: {
      damage: 2,
    },
    tagsRequired: ['weapon'],
    tagsAdded: ['frost', 'magical'],
  },
  shocking: {
    name: 'Shocking',
    description: 'This item crackles with electricity.',
    elements: ['lightning'],
    spheres: ['physical'],
    intent: 'destroy',
    magnitude: 35,
    valueAdder: 200000,
    statOffsets: {
      damage: 3,
    },
    tagsRequired: ['weapon', 'metal'],
    tagsAdded: ['shocking', 'magical'],
  },
  vampiric: {
    name: 'Vampiric',
    description: 'This weapon drains the life force of its victims.',
    elements: ['blood', 'death'],
    spheres: ['physical', 'spiritual'],
    intent: 'drain',
    magnitude: 60,
    valueAdder: 1000000,
    statOffsets: {
      damage: 1,
    },
    tagsRequired: ['weapon', 'slashing'],
    tagsAdded: ['vampiric', 'magical', 'evil'],
  },
  vorpal: {
    name: 'Vorpal',
    description: 'This weapon is incredibly sharp and seeks to sever heads.',
    elements: ['void'],
    spheres: ['physical'],
    intent: 'destroy',
    magnitude: 80,
    valueAdder: 5000000,
    statOffsets: {
      damage: 5,
    },
    tagsRequired: ['weapon', 'slashing'],
    tagsAdded: ['vorpal', 'magical'],
  },
  deflecting: {
    name: 'Deflecting',
    description: 'This armor seems to push attacks away.',
    elements: ['force'],
    spheres: ['physical'],
    intent: 'protect',
    magnitude: 40,
    valueAdder: 200000,
    statOffsets: {
      defense: 2,
    },
    tagsRequired: ['armor'],
    tagsAdded: ['deflecting', 'magical'],
  },
  fortified: {
    name: 'Fortified',
    description: 'This armor is magically hardened.',
    elements: ['earth'],
    spheres: ['physical'],
    intent: 'protect',
    magnitude: 30,
    valueAdder: 50000,
    statOffsets: {
      defense: 1,
    },
    tagsRequired: ['armor'],
    tagsAdded: ['fortified', 'magical'],
  },
  shadow: {
    name: 'Shadow',
    description: 'This item seems to absorb light.',
    elements: ['shadow'],
    spheres: ['physical'],
    intent: 'alter',
    magnitude: 40,
    valueAdder: 200000,
    tagsRequired: ['armor', 'light'],
    tagsAdded: ['shadow', 'magical', 'stealthy'],
  },
  holy: {
    name: 'Holy',
    description: 'This item glows with a divine light.',
    elements: ['light', 'divine'],
    spheres: ['spiritual'],
    intent: 'imbue',
    magnitude: 50,
    valueAdder: 200000,
    statOffsets: {
      damage: 2,
    },
    tagsRequired: ['weapon'],
    tagsAdded: ['holy', 'magical', 'good'],
    tagsExcluded: ['evil', 'vampiric'],
  },
  unholy: {
    name: 'Unholy',
    description: 'This item radiates a dark aura.',
    elements: ['shadow', 'death'],
    spheres: ['spiritual'],
    intent: 'imbue',
    magnitude: 50,
    valueAdder: 200000,
    statOffsets: {
      damage: 2,
    },
    tagsRequired: ['weapon'],
    tagsAdded: ['unholy', 'magical', 'evil'],
    tagsExcluded: ['good', 'holy'],
  },
  dancing: {
    name: 'Dancing',
    description: 'This weapon can fight on its own.',
    elements: ['air', 'mind'],
    spheres: ['physical', 'mental'],
    intent: 'control',
    magnitude: 60,
    valueAdder: 1000000,
    tagsRequired: ['weapon'],
    tagsAdded: ['dancing', 'magical'],
  },
  ethereal: {
    name: 'Ethereal',
    description: 'This item exists partially in the spirit realm.',
    elements: ['spirit', 'aether'],
    spheres: ['planar'],
    intent: 'move',
    magnitude: 70,
    valueAdder: 2000000,
    tagsAdded: ['ethereal', 'magical'],
  },
};
