import * as iarnd from "../random.js";

export function nations() {
  let prefixes = [
    "Ali",
    "Ana",
    "Ago",
    "Arri",
    "Banu",
    "Bana",
    "Bara",
    "Bel",
    "Car",
    "Carra",
    "Dor",
    "Dora",
    "Dol",
    "Ecka",
    "Eso",
    "Ezra",
    "Fan",
    "Far",
    "Fal",
    "Gre",
    "Gar",
    "Gam",
    "Hon",
    "Hala",
    "Hem",
    "Ino",
    "Iza",
    "Ir",
    "Jan",
    "Jo",
    "Kem",
    "Kal",
    "Kara",
    "Lo",
    "Lan",
    "Lem",
    "Les",
    "Mar",
    "Man",
    "Mer",
    "No",
    "Nor",
    "Nora",
    "Os",
    "Ogo",
    "Ogu",
    "Par",
    "Pas",
    "Pem",
    "Qes",
    "Qen",
    "Ran",
    "Rari",
    "Rani",
    "Rali",
    "Rasa",
    "Su",
    "Sura",
    "Suna",
    "Sona",
    "Sola",
    "Sole",
    "Ta",
    "Tar",
    "Tara",
    "Uta",
    "Una",
    "Uno",
    "Va",
    "Van",
    "Wa",
    "We",
    "Xa",
    "Xe",
    "Yan",
    "Yata",
    "Yen",
    "Ye",
    "Za",
    "Ze",
    "Zo",
  ];

  let suffixes = [
    "ali",
    "anar",
    "asar",
    "bani",
    "banu",
    "bantu",
    "batu",
    "chen",
    "den",
    "dar",
    "el",
    "eli",
    "fen",
    "far",
    "fari",
    "ga",
    "go",
    "hen",
    "iran",
    "janu",
    "jan",
    "jen",
    "ken",
    "kar",
    "len",
    "latu",
    "ma",
    "me",
    "na",
    "ne",
    "o",
    "pa",
    "qe",
    "ra",
    "rai",
    "re",
    "rei",
    "rel",
    "su",
    "sa",
    "se",
    "so",
    "tan",
    "ten",
    "uran",
    "var",
    "ven",
    "wa",
    "xa",
    "xe",
    "ya",
    "ye",
    "yen",
    "zar",
    "zem",
  ];

  let names = [];

  for (let i = 0; i < 50; i++) {
    let name = iarnd.item(prefixes) + iarnd.item(suffixes);
    names.push(name);
  }

  return names;
}

export function towns() {
  return [
    "Adurant",
    "Aenor's Hill",
    "Aerilon",
    "Amram",
    "Anfauglith",
    "Aquarin",
    "Aramoor",
    "Arlan's Way",
    "Arnor",
    "Arrendyll",
    "Ashdrift",
    "Avaglade",
    "Azmar",
    "Barrow Hills",
    "Barrow Falls",
    "Battlecliff",
    "Bay of Balar",
    "Begger's Hole",
    "Beleriand",
    "Black Hollow",
    "Blue Field",
    "Boatwright",
    "Briar Glen",
    "Brickelwhyte",
    "Brilthor",
    "Broken Shield",
    "Bruinen",
    "Bullmar",
    "Camorrus",
    "Carran",
    "Coalfell",
    "Corralis",
    "Crow's Cry",
    "Cullfield",
    "Darendale",
    "Darkwell",
    "Deathfall",
    "Death's Door",
    "Dimbar",
    "Doonatel",
    "Doriath",
    "Dorlomin",
    "Dorthonion",
    "Doveseal",
    "Doveshire",
    "Dragon's Coast",
    "Dry Gulch",
    "Duarudelf",
    "Duskendale",
    "East Armistice",
    "Eastford",
    "Easthaven",
    "Eastwatch",
    "Ecrin",
    "Eden's Gulf",
    "Ekaia",
    "Elbright",
    "Eldarmar",
    "Embertown",
    "End's Run",
    "Erast",
    "Ered",
    "Erede",
    "Eredluin",
    "Eribourne",
    "Ethermoor",
    "Fallenedge",
    "Fangorn",
    "Far Water",
    "Firebend",
    "Firecrow",
    "Fool's March",
    "Freevale",
    "Frostenvale",
    "Frostfangs",
    "Frostford",
    "Garen's Well",
    "Glaskerville",
    "Goldcrest",
    "Goldenleaf",
    "Greenflower",
    "Greenglade",
    "Greenloft",
    "Gulltown",
    "Haran",
    "Harlen",
    "Harsengaard",
    "Hillfar",
    "Hogsfeet",
    "Hollyhead",
    "Horizon's End",
    "Hull",
    "Hwen",
    "Icemeet",
    "Iron Hills",
    "Ironforge",
    "Irragin",
    "Jarren's Outpost",
    "Jongvale",
    "Kara's Vale",
    "Knife's Edge",
    "Lakeshore",
    "Lakestown",
    "Lamorra",
    "Last Lock",
    "Leeside",
    "Legolin",
    "Linesse",
    "Lochley",
    "Lothlann",
    "Lullin",
    "Maglor's Gap",
    "Mahalaga",
    "Marren's Eve",
    "Merriwich",
    "Millstone",
    "Moonbright",
    "Mountmend",
    "Nandungorteb",
    "Nargorthon",
    "Nearon",
    "New Cresthill",
    "Nogrod",
    "Northpass",
    "Northstead",
    "Northtown",
    "Nuxvar",
    "Oakensword",
    "Oakheart",
    "Oar's Rest",
    "Old Ashton",
    "Orrinshire",
    "Ozryn",
    "Pavv",
    "Pella's Wish",
    "Pineland",
    "Pinnella Pass",
    "Pony Run",
    "Pran",
    "Pyreacre",
    "Quan Ma",
    "Queenstown",
    "Ramshorn",
    "Red Hawk",
    "Rhaunar",
    "Rhudaur",
    "Rhuin",
    "Rivermouth",
    "Riverwind",
    "Saker Keep",
    "Seameet",
    "Shadestown",
    "Shiny Ship",
    "Ship's Haven",
    "Silverkeep",
    "Snake's Canyon",
    "Snowforge",
    "Snowmelt",
    "South Warren",
    "Southern Vale",
    "Squall's End",
    "Stone's Throw",
    "Stonewatch",
    "Strong Oak",
    "Suilwen",
    "Sundance",
    "Swordbreak",
    "Tarrin",
    "Taur-in-duinath",
    "Thales",
    "The Gale",
    "The Last Battle",
    "Three Rivers",
    "Three Streams",
    "Twin Rivers",
    "Two Rivers",
    "Two Towers",
    "Trudid",
    "Ubbin Falls",
    "Ula'ree",
    "Duskvale",
    "Veritas",
    "Vertrock",
    "Violl's Garden",
    "Wolfsrealm",
    "Wellspring",
    "Westend",
    "Westwend",
    "Whiteridge",
    "Whiterun",
    "Widow's Peak",
    "Willowdale",
    "Windrip",
    "Wintergale",
    "Wintervale",
    "Wolfden",
    "Xan's Bequest",
    "Xynnar",
    "Yarrin",
    "Yellowseed",
    "Zeffari",
    "Zumka",
  ];
}
