import * as iarnd from "../random.js";
import * as Common from "./common.js";

export function all() {
  return [
    "Adurant",
    "Aenor's Hill",
    "Aerilon",
    "Amram",
    "Anfauglith",
    "Aquarin",
    "Aramoor",
    "Arlan's Way",
    "Arnor",
    "Arrendyll",
    "Ashdrift",
    "Avaglade",
    "Azmar",
    "Barrow Hills",
    "Barrow Falls",
    "Battlecliff",
    "Bay of Balar",
    "Begger's Hole",
    "Beleriand",
    "Black Hollow",
    "Blue Field",
    "Boatwright",
    "Briar Glen",
    "Brickelwhyte",
    "Brilthor",
    "Broken Shield",
    "Bruinen",
    "Bullmar",
    "Camorrus",
    "Carran",
    "Coalfell",
    "Corralis",
    "Crow's Cry",
    "Cullfield",
    "Darendale",
    "Darkwell",
    "Deathfall",
    "Death's Door",
    "Dimbar",
    "Doonatel",
    "Doriath",
    "Dorlomin",
    "Dorthonion",
    "Doveseal",
    "Doveshire",
    "Dragon's Coast",
    "Dry Gulch",
    "Duarudelf",
    "Duskendale",
    "East Armistice",
    "Eastford",
    "Easthaven",
    "Eastwatch",
    "Ecrin",
    "Eden's Gulf",
    "Ekaia",
    "Elbright",
    "Eldarmar",
    "Embertown",
    "End's Run",
    "Erast",
    "Ered",
    "Erede",
    "Eredluin",
    "Eribourne",
    "Ethermoor",
    "Fallenedge",
    "Fangorn",
    "Far Water",
    "Firebend",
    "Firecrow",
    "Fool's March",
    "Freevale",
    "Frostenvale",
    "Frostfangs",
    "Frostford",
    "Garen's Well",
    "Glaskerville",
    "Goldcrest",
    "Goldenleaf",
    "Greenflower",
    "Greenglade",
    "Greenloft",
    "Gulltown",
    "Haran",
    "Harlen",
    "Harsengaard",
    "Hillfar",
    "Hogsfeet",
    "Hollyhead",
    "Horizon's End",
    "Hull",
    "Hwen",
    "Icemeet",
    "Iron Hills",
    "Ironforge",
    "Irragin",
    "Jarren's Outpost",
    "Jongvale",
    "Kara's Vale",
    "Knife's Edge",
    "Lakeshore",
    "Lakestown",
    "Lamorra",
    "Last Lock",
    "Leeside",
    "Legolin",
    "Linesse",
    "Lochley",
    "Lothlann",
    "Lullin",
    "Maglor's Gap",
    "Mahalaga",
    "Marren's Eve",
    "Merriwich",
    "Millstone",
    "Moonbright",
    "Mountmend",
    "Nandungorteb",
    "Nargorthon",
    "Nearon",
    "New Cresthill",
    "Nogrod",
    "Northpass",
    "Northstead",
    "Northtown",
    "Nuxvar",
    "Oakensword",
    "Oakheart",
    "Oar's Rest",
    "Old Ashton",
    "Orrinshire",
    "Ozryn",
    "Pavv",
    "Pella's Wish",
    "Pineland",
    "Pinnella Pass",
    "Pony Run",
    "Pran",
    "Pyreacre",
    "Quan Ma",
    "Queenstown",
    "Ramshorn",
    "Red Hawk",
    "Rhaunar",
    "Rhudaur",
    "Rhuin",
    "Rivermouth",
    "Riverwind",
    "Saker Keep",
    "Seameet",
    "Shadestown",
    "Shiny Ship",
    "Ship's Haven",
    "Silverkeep",
    "Snake's Canyon",
    "Snowforge",
    "Snowmelt",
    "South Warren",
    "Southern Vale",
    "Squall's End",
    "Stone's Throw",
    "Stonewatch",
    "Strong Oak",
    "Suilwen",
    "Sundance",
    "Swordbreak",
    "Tarrin",
    "Taur-in-duinath",
    "Thales",
    "The Gale",
    "The Last Battle",
    "Three Rivers",
    "Three Streams",
    "Twin Rivers",
    "Two Rivers",
    "Two Towers",
    "Trudid",
    "Ubbin Falls",
    "Ula'ree",
    "Duskvale",
    "Veritas",
    "Vertrock",
    "Violl's Garden",
    "Wolfsrealm",
    "Wellspring",
    "Westend",
    "Westwend",
    "Whiteridge",
    "Whiterun",
    "Widow's Peak",
    "Willowdale",
    "Windrip",
    "Wintergale",
    "Wintervale",
    "Wolfden",
    "Xan's Bequest",
    "Xynnar",
    "Yarrin",
    "Yellowseed",
    "Zeffari",
    "Zumka",
  ];
}

export function randomSet(numberOfNames) {
  let nameTypes = [
    {
      generate: function() {
        let first = [
          "Two",
          "Three",
          "Four",
          "Five",
          "Six",
          "Seven",
          "Eight",
          "Nine",
          "Ten",
          "Twin",
          "Triple",
        ];

        let second = [
          "Towers",
          "Rivers",
          "Mountains",
          "Hills",
          "Peaks",
          "Streams",
          "Rocks",
          "Trees",
          "Hollows",
          "Valleys",
          "Falls",
        ];

        return iarnd.item(first) + " " + iarnd.item(second);
      }
    },
    {
      generate: function() {
        let firstNames = Common.maleFirstNames();

        let first = iarnd.item(firstNames);

        let second = iarnd.item([
          "Folly",
          "Boon",
          "Rest",
          "Bequest",
          "Garden",
          "Repose",
          "Haven",
          "End",
          "Pass",
          "Forge",
          "Bulwark",
        ]);

        return first + "'s " + second;
      }
    },
    {
      generate: function() {
        let first = iarnd.item([
          "Lake",
          "River",
          "Fire",
          "Mountain",
          "Stream",
          "Hill",
          "White",
          "Winter",
          "Fall",
          "Gold",
          "Silver",
          "Copper",
          "Iron",
          "Field",
          "Sky",
          "Summer",
          "Autumn",
          "Spring",
          "Night",
        ]);

        let second = iarnd.item([
          "stead",
          "town",
          "bend",
          "ton",
          "vale",
          "borough",
          "haven",
          "keep",
          "meet",
          "forge",
          "gale",
          "stone",
          "rock",
          "glade",
          "ford",
        ]);

        return first + second;
      }
    }
  ];

  let names = [];

  for (let i=0;i<numberOfNames;i++) {
    let nameType = iarnd.item(nameTypes);
    let name = nameType.generate();

    if (!names.includes(name)) {
      names.push(name);
    }
  }

  return names;
}
