import type { Fitting } from './starship';

/**
 * Every fitting a starship can be built with, in the order the generator considers them.
 *
 * `costExpands`, `powerExpands`, and `massExpands` mark the figures that scale with hull class
 * rather than staying flat; `minimumClass`/`maximumClass` bound the hulls a fitting will fit.
 * Cargo space is an ordinary row here — it is only singled out at build time, when an owner
 * that hauls freight fills its leftover mass with it.
 */
export const STARSHIP_FITTINGS: Fitting[] = [
  {
    name: 'Advanced lab',
    fittingType: 'science',
    cost: 10000,
    costExpands: true,
    power: 1,
    powerExpands: true,
    mass: 2,
    massExpands: false,
    minimumClass: 1,
    maximumClass: 3,
    effect: 'Skill bonus for analysis and research',
  },
  {
    name: 'Advanced nav computer',
    fittingType: 'navigation',
    cost: 10000,
    costExpands: true,
    power: 1,
    powerExpands: true,
    mass: 0,
    massExpands: false,
    minimumClass: 1,
    maximumClass: 3,
    effect: 'Adds +2 for traveling familiar spike courses',
  },
  {
    name: 'Amphibious operation',
    fittingType: 'landing',
    cost: 25000,
    costExpands: false,
    power: 1,
    powerExpands: false,
    mass: 1,
    massExpands: true,
    minimumClass: 0,
    maximumClass: 3,
    effect: 'Can land and can operate under water',
  },
  {
    name: 'Armory',
    fittingType: 'weapons',
    cost: 10000,
    costExpands: true,
    power: 0,
    powerExpands: false,
    mass: 0,
    massExpands: false,
    minimumClass: 1,
    maximumClass: 3,
    effect: 'Weapons and armor for the crew',
  },
  {
    name: 'Atmospheric configuration',
    fittingType: 'landing',
    cost: 5000,
    costExpands: true,
    power: 0,
    powerExpands: false,
    mass: 1,
    massExpands: false,
    minimumClass: 0,
    maximumClass: 1,
    effect: 'Can land',
  },
  {
    name: 'Auto-targeting system',
    fittingType: 'weapons',
    cost: 50000,
    costExpands: false,
    power: 1,
    powerExpands: false,
    mass: 0,
    massExpands: false,
    minimumClass: 0,
    maximumClass: 3,
    effect: 'Fires one weapon system without a gunner',
  },
  {
    name: 'Automation support',
    fittingType: 'computer',
    cost: 10000,
    costExpands: true,
    power: 2,
    powerExpands: false,
    mass: 1,
    massExpands: false,
    minimumClass: 0,
    maximumClass: 3,
    effect: 'Ship can use simple robots as crew',
  },
  {
    name: 'Boarding tubes',
    fittingType: 'troops',
    cost: 5000,
    costExpands: true,
    power: 0,
    powerExpands: false,
    mass: 1,
    massExpands: false,
    minimumClass: 1,
    maximumClass: 3,
    effect: 'Allows boarding of a hostile disabled ship',
  },
  {
    name: 'Cargo lighter',
    fittingType: 'shuttle',
    cost: 25000,
    costExpands: false,
    power: 0,
    powerExpands: false,
    mass: 2,
    massExpands: false,
    minimumClass: 1,
    maximumClass: 3,
    effect: 'Orbit-to-surface cargo shuttle',
  },
  {
    name: 'Cargo space',
    fittingType: 'cargo',
    cost: 0,
    costExpands: false,
    power: 0,
    powerExpands: false,
    mass: 1,
    massExpands: false,
    minimumClass: 0,
    maximumClass: 3,
    effect: 'Pressurized cargo space',
  },
  {
    name: 'Cold sleep pods',
    fittingType: 'passenger',
    cost: 5000,
    costExpands: true,
    power: 1,
    powerExpands: false,
    mass: 1,
    massExpands: false,
    minimumClass: 1,
    maximumClass: 3,
    effect: 'Keeps occupants in stasis',
  },
  {
    name: 'Colony core',
    fittingType: 'colony',
    cost: 100000,
    costExpands: true,
    power: 4,
    powerExpands: false,
    mass: 2,
    massExpands: true,
    minimumClass: 1,
    maximumClass: 3,
    effect: 'Ship can be deconstructed into a colony base',
  },
  {
    name: 'Drill course regulator',
    fittingType: 'navigation',
    cost: 25000,
    costExpands: true,
    power: 1,
    powerExpands: true,
    mass: 1,
    massExpands: false,
    minimumClass: 1,
    maximumClass: 3,
    effect: 'Common drill routes become auto-successes',
  },
  {
    name: 'Drop pod',
    fittingType: 'troops',
    cost: 300000,
    costExpands: false,
    power: 0,
    powerExpands: false,
    mass: 2,
    massExpands: false,
    minimumClass: 1,
    maximumClass: 3,
    effect: 'Stealthed landing pod for troops',
  },
  {
    name: 'Emissions dampers',
    fittingType: 'stealth',
    cost: 25000,
    costExpands: true,
    power: 1,
    powerExpands: true,
    mass: 1,
    massExpands: true,
    minimumClass: 0,
    maximumClass: 3,
    effect: 'Adds +2 to skill checks to avoid detection',
  },
  {
    name: 'Exodus bay',
    fittingType: 'passenger',
    cost: 50000,
    costExpands: true,
    power: 1,
    powerExpands: true,
    mass: 2,
    massExpands: true,
    minimumClass: 2,
    maximumClass: 3,
    effect: 'House vast numbers of cold sleep passengers',
  },
  {
    name: 'Extended life support',
    fittingType: 'crew',
    cost: 5000,
    costExpands: true,
    power: 1,
    powerExpands: true,
    mass: 1,
    massExpands: true,
    minimumClass: 0,
    maximumClass: 3,
    effect: 'Doubles maximum crew size',
  },
  {
    name: 'Extended medbay',
    fittingType: 'medical',
    cost: 5000,
    costExpands: true,
    power: 1,
    powerExpands: false,
    mass: 1,
    massExpands: false,
    minimumClass: 1,
    maximumClass: 3,
    effect: 'Can provide medical care to more patients',
  },
  {
    name: 'Extended stores',
    fittingType: 'crew',
    cost: 2500,
    costExpands: true,
    power: 0,
    powerExpands: false,
    mass: 1,
    massExpands: true,
    minimumClass: 0,
    maximumClass: 3,
    effect: 'Maximum life support duration is doubled',
  },
  {
    name: 'Fuel bunkers',
    fittingType: 'fuel',
    cost: 2500,
    costExpands: true,
    power: 0,
    powerExpands: false,
    mass: 1,
    massExpands: false,
    minimumClass: 0,
    maximumClass: 3,
    effect: 'Adds fuel for one more drill between fuelings',
  },
  {
    name: 'Fuel scoops',
    fittingType: 'fuel',
    cost: 5000,
    costExpands: true,
    power: 2,
    powerExpands: false,
    mass: 1,
    massExpands: true,
    minimumClass: 1,
    maximumClass: 3,
    effect: 'Ship can scoop fuel from a gas giant or star',
  },
  {
    name: 'Hydroponic production',
    fittingType: 'crew',
    cost: 10000,
    costExpands: true,
    power: 1,
    powerExpands: true,
    mass: 2,
    massExpands: true,
    minimumClass: 2,
    maximumClass: 3,
    effect: 'Ship produces life support resources',
  },
  {
    name: 'Lifeboats',
    fittingType: 'shuttle',
    cost: 2500,
    costExpands: true,
    power: 0,
    powerExpands: false,
    mass: 1,
    massExpands: false,
    minimumClass: 1,
    maximumClass: 3,
    effect: "Emergency escape craft for a ship's crew",
  },
  {
    name: 'Luxury cabins',
    fittingType: 'crew',
    cost: 10000,
    costExpands: true,
    power: 0,
    powerExpands: false,
    mass: 1,
    massExpands: true,
    minimumClass: 1,
    maximumClass: 3,
    effect: '10% of the max crew get luxurious quarters',
  },
  {
    name: 'Mobile extractor',
    fittingType: 'mining',
    cost: 50000,
    costExpands: false,
    power: 2,
    powerExpands: false,
    mass: 1,
    massExpands: false,
    minimumClass: 1,
    maximumClass: 3,
    effect: 'Space mining and refinery fittings',
  },
  {
    name: 'Mobile factory',
    fittingType: 'factory',
    cost: 50000,
    costExpands: true,
    power: 3,
    powerExpands: false,
    mass: 2,
    massExpands: true,
    minimumClass: 2,
    maximumClass: 3,
    effect: 'Self-sustaining factory and repair facilities',
  },
  {
    name: 'Precognitive nav chamber',
    fittingType: 'psychic',
    cost: 100000,
    costExpands: true,
    power: 1,
    powerExpands: false,
    mass: 0,
    massExpands: false,
    minimumClass: 1,
    maximumClass: 3,
    effect: 'Allows a precog to assist in navigation',
  },
  {
    name: 'Sensor mask',
    fittingType: 'stealth',
    cost: 10000,
    costExpands: true,
    power: 1,
    powerExpands: true,
    mass: 0,
    massExpands: false,
    minimumClass: 1,
    maximumClass: 3,
    effect: 'At long distances, disguise ship as another',
  },
  {
    name: 'Ship bay: fighter',
    fittingType: 'carrier',
    cost: 200000,
    costExpands: false,
    power: 0,
    powerExpands: false,
    mass: 2,
    massExpands: false,
    minimumClass: 2,
    maximumClass: 3,
    effect: 'Carrier housing for a fighter',
  },
  {
    name: 'Ship bay: frigate',
    fittingType: 'carrier',
    cost: 1000000,
    costExpands: false,
    power: 1,
    powerExpands: false,
    mass: 4,
    massExpands: false,
    minimumClass: 3,
    maximumClass: 3,
    effect: 'Carrier housing for a frigate',
  },
  {
    name: "Ship's locker",
    fittingType: 'cargo',
    cost: 2000,
    costExpands: true,
    power: 0,
    powerExpands: false,
    mass: 0,
    massExpands: false,
    minimumClass: 1,
    maximumClass: 3,
    effect: 'General equipment for the crew',
  },
  {
    name: 'Shiptender mount',
    fittingType: 'support',
    cost: 25000,
    costExpands: true,
    power: 1,
    powerExpands: false,
    mass: 1,
    massExpands: false,
    minimumClass: 1,
    maximumClass: 3,
    effect: 'Allow another ship to hitch on a spike drive',
  },
  {
    name: "Smuggler's hold",
    fittingType: 'smuggling',
    cost: 2500,
    costExpands: true,
    power: 0,
    powerExpands: false,
    mass: 1,
    massExpands: false,
    minimumClass: 0,
    maximumClass: 3,
    effect: 'Small amount of well-hidden cargo space',
  },
  {
    name: 'Survey sensor array',
    fittingType: 'sensors',
    cost: 5000,
    costExpands: true,
    power: 2,
    powerExpands: false,
    mass: 1,
    massExpands: false,
    minimumClass: 1,
    maximumClass: 3,
    effect: 'Improved planetary sensor array',
  },
  {
    name: 'Tractor beams',
    fittingType: 'support',
    cost: 10000,
    costExpands: true,
    power: 2,
    powerExpands: false,
    mass: 1,
    massExpands: false,
    minimumClass: 1,
    maximumClass: 3,
    effect: 'Manipulate objects in space at a distance',
  },
  {
    name: 'Vehicle transport fittings',
    fittingType: 'carrier',
    cost: 2500,
    costExpands: true,
    power: 0,
    powerExpands: false,
    mass: 1,
    massExpands: true,
    minimumClass: 1,
    maximumClass: 3,
    effect: 'Halve tonnage space of carried vehicles',
  },
  {
    name: 'Workshop',
    fittingType: 'support',
    cost: 500,
    costExpands: true,
    power: 1,
    powerExpands: false,
    mass: 0.5,
    massExpands: true,
    minimumClass: 1,
    maximumClass: 3,
    effect: 'Automated tech workshops for maintenance',
  },
];
