import type ADNDArmor from './adndarmor.js';
import type ADNDWeapon from './adndweapon.js';

export function getAmmoTypes(weapon: ADNDWeapon): ADNDWeapon[] {
  let result: ADNDWeapon[] = [];

  if (weapon.name === 'blowgun') {
    result = [
      {
        name: 'blowgun barbed dart',
        cost: 1 * 10,
        weight: 1,
        size: 'small',
        damageType: 'piercing',
        speedFactor: -1,
        damageSM: '1d3',
        damageL: '1d2',
        category: 'blowgun dart',
        usesAmmo: false,
      },
      {
        name: 'blowgun needle',
        cost: 1 * 10,
        weight: 1,
        size: 'small',
        damageType: 'piercing',
        speedFactor: -1,
        damageSM: '1d3',
        damageL: '1d2',
        category: 'blowgun dart',
        usesAmmo: false,
      },
    ];
  } else if (weapon.category === 'bow') {
    result = [
      {
        name: 'flight arrow (12)',
        cost: 3 * 10,
        weight: 1,
        size: 'small',
        damageType: 'piercing',
        speedFactor: -1,
        damageSM: '1d6',
        damageL: '1d6',
        category: 'arrow',
        usesAmmo: false,
      },
      {
        name: 'sheaf arrow (6)',
        cost: 3 * 10,
        weight: 1,
        size: 'small',
        damageType: 'piercing',
        speedFactor: -1,
        damageSM: '1d8',
        damageL: '1d8',
        category: 'arrow',
        usesAmmo: false,
      },
    ];
  } else if (weapon.name === 'Crossbow, hand') {
    result = [
      {
        name: 'hand quarrel',
        cost: 1 * 100,
        weight: 1,
        size: 'small',
        damageType: 'piercing',
        speedFactor: -1,
        damageSM: '1d3',
        damageL: '1d2',
        category: 'crossbow quarrel',
        usesAmmo: false,
      },
    ];
  } else if (weapon.name === 'Crossbow, light') {
    result = [
      {
        name: 'light quarrel',
        cost: 1 * 10,
        weight: 1,
        size: 'small',
        damageType: 'piercing',
        speedFactor: -1,
        damageSM: '1d4',
        damageL: '1d4',
        category: 'crossbow quarrel',
        usesAmmo: false,
      },
    ];
  } else if (weapon.name === 'crossbow, heavy') {
    result = [
      {
        name: 'heavy quarrel',
        cost: 2 * 10,
        weight: 1,
        size: 'small',
        damageType: 'piercing',
        speedFactor: -1,
        damageSM: '1d4+1',
        damageL: '1d6+1',
        category: 'crossbow quarrel',
        usesAmmo: false,
      },
    ];
  } else if (weapon.category === 'sling') {
    result = [
      {
        name: 'sling bullet',
        cost: 1,
        weight: 0,
        size: 'small',
        damageType: 'bludgeoning',
        speedFactor: -1,
        damageSM: '1d4+1',
        damageL: '1d6+1',
        category: 'sling bullet',
        usesAmmo: false,
      },
      {
        name: 'sling stone',
        cost: 0,
        weight: 0,
        size: 'small',
        damageType: 'bludgeoning',
        speedFactor: -1,
        damageSM: '1d4',
        damageL: '1d4',
        category: 'sling bullet',
        usesAmmo: false,
      },
    ];
  }

  return result;
}

export function getArmor(): ADNDArmor[] {
  return [
    {
      name: 'banded mail',
      ac: -7,
      weight: 35,
      cost: 300 * 100,
    },
    {
      name: 'brigandine',
      ac: -4,
      weight: 35,
      cost: 120 * 100,
    },
    {
      name: 'bronze plate mail',
      ac: -7,
      weight: 45,
      cost: 400 * 100,
    },
    {
      name: 'chain mail',
      ac: -6,
      weight: 40,
      cost: 75 * 100,
    },
    {
      name: 'field plate',
      ac: -8,
      weight: 60,
      cost: 2000 * 100,
    },
    {
      name: 'full plate',
      ac: -9,
      weight: 70,
      cost: 4000 * 100,
    },
    {
      name: 'hide',
      ac: -4,
      weight: 30,
      cost: 15 * 100,
    },
    {
      name: 'leather',
      ac: -2,
      weight: 15,
      cost: 5 * 100,
    },
    {
      name: 'padded',
      ac: -2,
      weight: 10,
      cost: 4 * 100,
    },
    {
      name: 'plate mail',
      ac: -7,
      weight: 50,
      cost: 600 * 100,
    },
    {
      name: 'ring mail',
      ac: -3,
      weight: 30,
      cost: 100 * 100,
    },
    {
      name: 'scale mail',
      ac: -4,
      weight: 40,
      cost: 120 * 100,
    },
    {
      name: 'shield, body',
      ac: -1,
      weight: 15,
      cost: 10 * 100,
    },
    {
      name: 'shield, small buckler',
      ac: -1,
      weight: 10,
      cost: 7 * 100,
    },
    {
      name: 'shield, medium buckler',
      ac: -1,
      weight: 5,
      cost: 3 * 100,
    },
    {
      name: 'splint mail',
      ac: -6,
      weight: 40,
      cost: 80 * 100,
    },
    {
      name: 'studded leather',
      ac: -4,
      weight: 25,
      cost: 20 * 100,
    },
  ];
}

export function getWeapons(): ADNDWeapon[] {
  return [
    {
      name: 'arquebus',
      cost: 500 * 100,
      weight: 10,
      size: 'medium',
      damageType: 'piercing',
      speedFactor: 15,
      damageSM: '1d10',
      damageL: '1d10',
      category: 'musket',
      usesAmmo: false,
    },
    {
      name: 'battle axe',
      cost: 5 * 100,
      weight: 6,
      size: 'medium',
      damageType: 'slashing',
      speedFactor: 7,
      damageSM: '1d8',
      damageL: '1d8',
      category: 'axe',
      usesAmmo: false,
    },
    {
      name: 'blowgun',
      cost: 5 * 100,
      weight: 1,
      size: 'large',
      damageType: 'piercing',
      speedFactor: 5,
      damageSM: '1',
      damageL: '1',
      category: 'blowgun',
      usesAmmo: true,
    },
    {
      name: 'short bow',
      cost: 30 * 100,
      weight: 2,
      size: 'medium',
      damageType: 'piercing',
      speedFactor: 7,
      damageSM: '1',
      damageL: '1',
      category: 'bow',
      usesAmmo: true,
    },
    {
      name: 'long bow',
      cost: 75 * 100,
      weight: 3,
      size: 'large',
      damageType: 'piercing',
      speedFactor: 8,
      damageSM: '1',
      damageL: '1',
      category: 'bow',
      usesAmmo: true,
    },
    {
      name: 'composite short bow',
      cost: 75 * 100,
      weight: 2,
      size: 'medium',
      damageType: 'piercing',
      speedFactor: 6,
      damageSM: '1',
      damageL: '1',
      category: 'bow',
      usesAmmo: true,
    },
    {
      name: 'composite long bow',
      cost: 100 * 100,
      weight: 3,
      size: 'large',
      damageType: 'piercing',
      speedFactor: 7,
      damageSM: '1',
      damageL: '1',
      category: 'bow',
      usesAmmo: true,
    },
    {
      name: 'club',
      cost: 0,
      weight: 3,
      size: 'medium',
      damageType: 'bludgeoning',
      speedFactor: 4,
      damageSM: '1d6',
      damageL: '1d3',
      category: 'club',
      usesAmmo: false,
    },
    {
      name: 'crossbow, hand',
      cost: 300 * 100,
      weight: 3,
      size: 'small',
      damageType: 'piercing',
      speedFactor: 5,
      damageSM: '0',
      damageL: '0',
      category: 'crossbow',
      usesAmmo: true,
    },
    {
      name: 'crossbow, light',
      cost: 35 * 100,
      weight: 7,
      size: 'medium',
      damageType: 'piercing',
      speedFactor: 7,
      damageSM: '0',
      damageL: '0',
      category: 'crossbow',
      usesAmmo: true,
    },
    {
      name: 'crossbow, heavy',
      cost: 50 * 100,
      weight: 14,
      size: 'medium',
      damageType: 'piercing',
      speedFactor: 10,
      damageSM: '0',
      damageL: '0',
      category: 'crossbow',
      usesAmmo: true,
    },
    {
      name: 'dagger',
      cost: 2 * 100,
      weight: 1,
      size: 'small',
      damageType: 'piercing',
      speedFactor: 2,
      damageSM: '1d4',
      damageL: '1d3',
      category: 'dagger',
      usesAmmo: false,
    },
    {
      name: 'dart',
      cost: 5 * 10,
      weight: 0.5,
      size: 'small',
      damageType: 'piercing',
      speedFactor: 2,
      damageSM: '1d4',
      damageL: '1d3',
      category: 'dart',
      usesAmmo: false,
    },
    {
      name: "footman's flail",
      cost: 15 * 100,
      weight: 15,
      size: 'medium',
      damageType: 'bludgeoning',
      speedFactor: 7,
      damageSM: '1d6+1',
      damageL: '2d4',
      category: 'flail',
      usesAmmo: false,
    },
    {
      name: "footman's mace",
      cost: 8 * 100,
      weight: 10,
      size: 'medium',
      damageType: 'bludgeoning',
      speedFactor: 7,
      damageSM: '1d6+1',
      damageL: '1d6',
      category: 'mace',
      usesAmmo: false,
    },
    {
      name: "footman's pick",
      cost: 8 * 100,
      weight: 6,
      size: 'medium',
      damageType: 'piercing',
      speedFactor: 7,
      damageSM: '1d6+1',
      damageL: '2d4',
      category: 'pick',
      usesAmmo: false,
    },
    {
      name: 'hand axe',
      cost: 1 * 100,
      weight: 5,
      size: 'medium',
      damageType: 'slashing',
      speedFactor: 4,
      damageSM: '1d6',
      damageL: '1d4',
      category: 'axe',
      usesAmmo: false,
    },
    {
      name: 'harpoon',
      cost: 20 * 100,
      weight: 6,
      size: 'large',
      damageType: 'piercing',
      speedFactor: 7,
      damageSM: '2d4',
      damageL: '2d6',
      category: 'spear',
      usesAmmo: false,
    },
    {
      name: "horseman's flail",
      cost: 8 * 100,
      weight: 5,
      size: 'medium',
      damageType: 'bludgeoning',
      speedFactor: 6,
      damageSM: '1d4+1',
      damageL: '1d4+1',
      category: 'flail',
      usesAmmo: false,
    },
    {
      name: "horseman's mace",
      cost: 5 * 100,
      weight: 6,
      size: 'medium',
      damageType: 'bludgeoning',
      speedFactor: 6,
      damageSM: '1d6',
      damageL: '1d4',
      category: 'mace',
      usesAmmo: false,
    },
    {
      name: "horseman's pick",
      cost: 7 * 100,
      weight: 4,
      size: 'medium',
      damageType: 'piercing',
      speedFactor: 5,
      damageSM: '1d4+1',
      damageL: '1d4',
      category: 'pick',
      usesAmmo: false,
    },
    {
      name: 'javelin',
      cost: 5 * 10,
      weight: 2,
      size: 'medium',
      damageType: 'piercing',
      speedFactor: 4,
      damageSM: '1d6',
      damageL: '1d6',
      category: 'spear',
      usesAmmo: false,
    },
    {
      name: 'knife',
      cost: 5 * 10,
      weight: 0.5,
      size: 'small',
      damageType: 'piercing',
      speedFactor: 2,
      damageSM: '1d3',
      damageL: '1d2',
      category: 'dagger',
      usesAmmo: false,
    },
    {
      name: 'jousting lance',
      cost: 20 * 100,
      weight: 20,
      size: 'large',
      damageType: 'piercing',
      speedFactor: 10,
      damageSM: '1d3-1',
      damageL: '1d2-1',
      category: 'lance',
      usesAmmo: false,
    },
    {
      name: 'heavy horse lance',
      cost: 15 * 100,
      weight: 15,
      size: 'large',
      damageType: 'piercing',
      speedFactor: 8,
      damageSM: '1d8+1',
      damageL: '3d6',
      category: 'lance',
      usesAmmo: false,
    },
    {
      name: 'light horse lance',
      cost: 6 * 100,
      weight: 5,
      size: 'large',
      damageType: 'piercing',
      speedFactor: 6,
      damageSM: '1d6',
      damageL: '1d8',
      category: 'lance',
      usesAmmo: false,
    },
    {
      name: 'medium horse lance',
      cost: 10 * 100,
      weight: 10,
      size: 'large',
      damageType: 'piercing',
      speedFactor: 7,
      damageSM: '1d6+1',
      damageL: '2d6',
      category: 'lance',
      usesAmmo: false,
    },
    {
      name: 'mancatcher',
      cost: 30 * 100,
      weight: 8,
      size: 'large',
      damageType: 'none',
      speedFactor: 7,
      damageSM: '0',
      damageL: '0',
      category: 'nonlethal',
      usesAmmo: false,
    },
    {
      name: 'morningstar',
      cost: 10 * 100,
      weight: 12,
      size: 'medium',
      damageType: 'bludgeoning',
      speedFactor: 7,
      damageSM: '2d4',
      damageL: '1d6+1',
      category: 'mace',
      usesAmmo: false,
    },
    {
      name: 'awl pike',
      cost: 5 * 100,
      weight: 12,
      size: 'large',
      damageType: 'piercing',
      speedFactor: 13,
      damageSM: '1d6',
      damageL: '1d12',
      category: 'polearm',
      usesAmmo: false,
    },
    {
      name: 'bardiche',
      cost: 7 * 100,
      weight: 12,
      size: 'large',
      damageType: 'slashing',
      speedFactor: 9,
      damageSM: '2d4',
      damageL: '2d6',
      category: 'polearm',
      usesAmmo: false,
    },
    {
      name: 'bec de corbin',
      cost: 8 * 100,
      weight: 10,
      size: 'large',
      damageType: 'piercing/bludgeoning',
      speedFactor: 9,
      damageSM: '1d8',
      damageL: '1d6',
      category: 'polearm',
      usesAmmo: false,
    },
    {
      name: 'bill-guisarme',
      cost: 7 * 100,
      weight: 15,
      size: 'large',
      damageType: 'piercing/slashing',
      speedFactor: 10,
      damageSM: '2d4',
      damageL: '1d10',
      category: 'polearm',
      usesAmmo: false,
    },
    {
      name: 'fauchard',
      cost: 5 * 100,
      weight: 7,
      size: 'large',
      damageType: 'piercing/slashing',
      speedFactor: 8,
      damageSM: '1d6',
      damageL: '1d8',
      category: 'polearm',
      usesAmmo: false,
    },
    {
      name: 'fauchard-fork',
      cost: 8 * 100,
      weight: 9,
      size: 'large',
      damageType: 'piercing/slashing',
      speedFactor: 8,
      damageSM: '1d8',
      damageL: '1d10',
      category: 'polearm',
      usesAmmo: false,
    },
    {
      name: 'glaive',
      cost: 6 * 100,
      weight: 8,
      size: 'large',
      damageType: 'slashing',
      speedFactor: 8,
      damageSM: '1d6',
      damageL: '1d10',
      category: 'polearm',
      usesAmmo: false,
    },
    {
      name: 'glaive-guisarme',
      cost: 10 * 100,
      weight: 10,
      size: 'large',
      damageType: 'piercing/slashing',
      speedFactor: 9,
      damageSM: '2d4',
      damageL: '2d6',
      category: 'polearm',
      usesAmmo: false,
    },
    {
      name: 'guisarme',
      cost: 5 * 100,
      weight: 8,
      size: 'large',
      damageType: 'slashing',
      speedFactor: 8,
      damageSM: '2d4',
      damageL: '1d8',
      category: 'polearm',
      usesAmmo: false,
    },
    {
      name: 'guisarme-voulge',
      cost: 8 * 100,
      weight: 15,
      size: 'large',
      damageType: 'piercing/slashing',
      speedFactor: 10,
      damageSM: '2d4',
      damageL: '2d4',
      category: 'polearm',
      usesAmmo: false,
    },
    {
      name: 'halberd',
      cost: 10 * 100,
      weight: 15,
      size: 'large',
      damageType: 'piercing/slashing',
      speedFactor: 9,
      damageSM: '1d10',
      damageL: '2d6',
      category: 'polearm',
      usesAmmo: false,
    },
    {
      name: 'hook fauchard',
      cost: 10 * 100,
      weight: 8,
      size: 'large',
      damageType: 'piercing/slashing',
      speedFactor: 9,
      damageSM: '1d4',
      damageL: '1d4',
      category: 'polearm',
      usesAmmo: false,
    },
    {
      name: 'lucern hammer',
      cost: 7 * 100,
      weight: 15,
      size: 'large',
      damageType: 'piercing/bludgeoning',
      speedFactor: 9,
      damageSM: '2d4',
      damageL: '1d6',
      category: 'polearm',
      usesAmmo: false,
    },
    {
      name: 'military fork',
      cost: 5 * 100,
      weight: 7,
      size: 'large',
      damageType: 'piercing',
      speedFactor: 7,
      damageSM: '1d8',
      damageL: '2d4',
      category: 'polearm',
      usesAmmo: false,
    },
    {
      name: 'partisan',
      cost: 10 * 100,
      weight: 8,
      size: 'large',
      damageType: 'piercing',
      speedFactor: 9,
      damageSM: '1d6',
      damageL: '1d6+1',
      category: 'polearm',
      usesAmmo: false,
    },
    {
      name: 'ranseur',
      cost: 6 * 100,
      weight: 7,
      size: 'large',
      damageType: 'piercing',
      speedFactor: 8,
      damageSM: '2d4',
      damageL: '2d4',
      category: 'polearm',
      usesAmmo: false,
    },
    {
      name: 'spetum',
      cost: 5 * 100,
      weight: 7,
      size: 'large',
      damageType: 'piercing',
      speedFactor: 8,
      damageSM: '1d6+1',
      damageL: '1d6+1',
      category: 'polearm',
      usesAmmo: false,
    },
    {
      name: 'voulge',
      cost: 5 * 100,
      weight: 12,
      size: 'large',
      damageType: 'slashing',
      speedFactor: 10,
      damageSM: '2d4',
      damageL: '2d4',
      category: 'polearm',
      usesAmmo: false,
    },
    {
      name: 'quarterstaff',
      cost: 0,
      weight: 4,
      size: 'large',
      damageType: 'bludgeoning',
      speedFactor: 4,
      damageSM: '1d6',
      damageL: '1d6',
      category: 'staff',
      usesAmmo: false,
    },
    {
      name: 'scourge',
      cost: 1 * 100,
      weight: 2,
      size: 'small',
      damageType: 'none',
      speedFactor: 5,
      damageSM: '1d4',
      damageL: '1d2',
      category: 'whip',
      usesAmmo: false,
    },
    {
      name: 'sickle',
      cost: 6 * 10,
      weight: 3,
      size: 'small',
      damageType: 'slashing',
      speedFactor: 4,
      damageSM: '1d4+1',
      damageL: '1d4',
      category: 'sickle',
      usesAmmo: false,
    },
    {
      name: 'sling',
      cost: 5,
      weight: 0,
      size: 'small',
      damageType: 'bludgeoning',
      speedFactor: 6,
      damageSM: '0',
      damageL: '0',
      category: 'sling',
      usesAmmo: true,
    },
    {
      name: 'spear',
      cost: 8 * 10,
      weight: 5,
      size: 'medium',
      damageType: 'piercing',
      speedFactor: 6,
      damageSM: '1d6',
      damageL: '1d8',
      category: 'spear',
      usesAmmo: false,
    },
    {
      name: 'staff sling',
      cost: 2 * 10,
      weight: 2,
      size: 'medium',
      damageType: 'none',
      speedFactor: 11,
      damageSM: '0',
      damageL: '0',
      category: 'sling',
      usesAmmo: true,
    },
    {
      name: 'bastard sword, 1H',
      cost: 25 * 100,
      weight: 10,
      size: 'medium',
      damageType: 'slashing',
      speedFactor: 6,
      damageSM: '1d8',
      damageL: '1d12',
      category: 'sword',
      usesAmmo: false,
    },
    {
      name: 'bastard sword, 2H',
      cost: 25 * 100,
      weight: 10,
      size: 'medium',
      damageType: 'slashing',
      speedFactor: 8,
      damageSM: '2d4',
      damageL: '2d8',
      category: 'sword',
      usesAmmo: false,
    },
    {
      name: 'broad sword',
      cost: 10 * 100,
      weight: 4,
      size: 'medium',
      damageType: 'slashing',
      speedFactor: 5,
      damageSM: '2d4',
      damageL: '1d6+1',
      category: 'sword',
      usesAmmo: false,
    },
    {
      name: 'khopesh',
      cost: 10 * 100,
      weight: 7,
      size: 'medium',
      damageType: 'slashing',
      speedFactor: 9,
      damageSM: '2d4',
      damageL: '1d6',
      category: 'sword',
      usesAmmo: false,
    },
    {
      name: 'long sword',
      cost: 15 * 100,
      weight: 4,
      size: 'medium',
      damageType: 'slashing',
      speedFactor: 5,
      damageSM: '1d8',
      damageL: '1d12',
      category: 'sword',
      usesAmmo: false,
    },
    {
      name: 'scimitar',
      cost: 15 * 100,
      weight: 4,
      size: 'medium',
      damageType: 'slashing',
      speedFactor: 5,
      damageSM: '1d8',
      damageL: '1d8',
      category: 'sword',
      usesAmmo: false,
    },
    {
      name: 'short sword',
      cost: 10 * 100,
      weight: 3,
      size: 'small',
      damageType: 'piercing',
      speedFactor: 3,
      damageSM: '1d6',
      damageL: '1d8',
      category: 'sword',
      usesAmmo: false,
    },
    {
      name: 'two-handed sword',
      cost: 50 * 100,
      weight: 15,
      size: 'large',
      damageType: 'slashing',
      speedFactor: 10,
      damageSM: '1d10',
      damageL: '3d6',
      category: 'sword',
      usesAmmo: false,
    },
    {
      name: 'trident',
      cost: 10 * 10,
      weight: 6,
      size: 'medium',
      damageType: 'piercing',
      speedFactor: 6,
      damageSM: '1d6',
      damageL: '1d8',
      category: 'spear',
      usesAmmo: false,
    },
    {
      name: 'warhammer',
      cost: 2 * 100,
      weight: 6,
      size: 'medium',
      damageType: 'bludgeoning',
      speedFactor: 4,
      damageSM: '1d4+1',
      damageL: '1d4',
      category: 'mace',
      usesAmmo: false,
    },
    {
      name: 'whip',
      cost: 1 * 10,
      weight: 2,
      size: 'medium',
      damageType: 'none',
      speedFactor: 8,
      damageSM: '1d2',
      damageL: '1',
      category: 'whip',
      usesAmmo: false,
    },
  ];
}
