import { c as create_ssr_component, a as add_attribute, f as each, e as escape } from "../../../chunks/ssr.js";
import * as RND from "@ironarachne/rng";
import { g as getClassificationNames, P as PlanetGenerator, a as PlanetGeneratorConfig } from "../../../chunks/generator.js";
import "../../../chunks/sentry-release-injection-file.js";
import random from "random";
import * as THREE from "three";
import seedrandom from "seedrandom";
const _page_svelte_svelte_type_style_lang = "";
const css = {
  code: 'div.svelte-1mgpjv4.svelte-1mgpjv4,h1.svelte-1mgpjv4.svelte-1mgpjv4,h2.svelte-1mgpjv4.svelte-1mgpjv4,p.svelte-1mgpjv4.svelte-1mgpjv4,strong.svelte-1mgpjv4.svelte-1mgpjv4,sup.svelte-1mgpjv4.svelte-1mgpjv4,label.svelte-1mgpjv4.svelte-1mgpjv4,canvas.svelte-1mgpjv4.svelte-1mgpjv4,section.svelte-1mgpjv4.svelte-1mgpjv4{margin:0;padding:0;border:0;font-size:100%;font:inherit;vertical-align:baseline}section.svelte-1mgpjv4.svelte-1mgpjv4{display:block}@font-face{font-family:"alienleague";src:url("$lib/assets/fonts/alienleagueregular-9d3z-webfont.woff2") format("woff2");font-weight:normal;font-style:normal}@font-face{font-family:"azonix";src:url("$lib/assets/fonts/azonix-webfont.woff2") format("woff2");font-weight:normal;font-style:normal}h1.svelte-1mgpjv4.svelte-1mgpjv4,h2.svelte-1mgpjv4.svelte-1mgpjv4{font-family:system-ui, Helvetica, sans-serif;margin:0.5rem 0}sup.svelte-1mgpjv4.svelte-1mgpjv4{vertical-align:super;font-size:0.6rem}h1.svelte-1mgpjv4.svelte-1mgpjv4{color:#000;font-weight:700;font-size:2.5rem;line-height:2.5rem;padding:3px}h2.svelte-1mgpjv4.svelte-1mgpjv4{color:#000;font-weight:500;font-size:2.25rem;line-height:2.25rem;padding:3px}p.svelte-1mgpjv4.svelte-1mgpjv4{margin:1rem 0}label.svelte-1mgpjv4.svelte-1mgpjv4{font-weight:700;margin-right:1rem}input.svelte-1mgpjv4.svelte-1mgpjv4,select.svelte-1mgpjv4.svelte-1mgpjv4{font-size:1rem;line-height:1rem;padding:0.25rem}div.input-group.svelte-1mgpjv4.svelte-1mgpjv4{margin-bottom:1rem}strong.svelte-1mgpjv4.svelte-1mgpjv4{font-weight:700}section.main.svelte-1mgpjv4.svelte-1mgpjv4{padding:0.5rem}#seed.svelte-1mgpjv4.svelte-1mgpjv4{font-family:monospace}.scifi.svelte-1mgpjv4.svelte-1mgpjv4{background:rgb(16, 17, 25);background:linear-gradient(90deg, rgb(16, 17, 25) 0%, rgb(38, 58, 96) 49%, rgb(16, 17, 25) 100%);color:white}.scifi.svelte-1mgpjv4 h1.svelte-1mgpjv4,.scifi.svelte-1mgpjv4 h2.svelte-1mgpjv4{color:#a2d4ff;text-shadow:0 0 6px #0086ff;font-family:"alienleague", sans-serif}.scifi.svelte-1mgpjv4 button.svelte-1mgpjv4{background:rgb(2, 37, 95);background:linear-gradient(165deg, rgb(2, 37, 95) 0%, rgb(10, 10, 10) 100%);border:3px solid rgb(108, 146, 255);border-radius:3px;color:#fff;font-family:"alienleague", sans-serif;font-size:1.15rem;line-height:1rem;margin:0.1rem;padding:0.5rem 1rem}.scifi.svelte-1mgpjv4 button.svelte-1mgpjv4:active{background:rgb(92, 86, 73);background:linear-gradient(339deg, rgb(92, 86, 73) 0%, rgb(10, 10, 10) 100%);color:rgb(108, 146, 255);transform:translateY(2px)}.scifi.svelte-1mgpjv4 button.svelte-1mgpjv4:disabled{background:#666;color:#777;border-color:#999}canvas.svelte-1mgpjv4.svelte-1mgpjv4{display:block;width:600px;height:400px;margin:1rem auto}',
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let planetTypes = getClassificationNames();
  let seed = RND.randomString(13);
  random.use(seedrandom(seed));
  let planetGenConfig = new PlanetGeneratorConfig();
  let planetGen = new PlanetGenerator(planetGenConfig);
  let planet = planetGen.generate();
  new THREE.Scene();
  $$result.css.add(css);
  return `${$$result.head += `<!-- HEAD_svelte-1rxcaiu_START -->${$$result.title = `<title>Planet Generator | Iron Arachne</title>`, ""}<!-- HEAD_svelte-1rxcaiu_END -->`, ""} <section class="main scifi svelte-1mgpjv4"><h1 class="svelte-1mgpjv4" data-svelte-h="svelte-32imzj">Planet Generator</h1> <p class="svelte-1mgpjv4" data-svelte-h="svelte-ranut0">This lets you generate a planet. It uses WebGL and your graphics card.</p> <div class="input-group svelte-1mgpjv4"><label for="seed" class="svelte-1mgpjv4" data-svelte-h="svelte-1akft3f">Random Seed</label> <input type="text" name="seed" id="seed" class="svelte-1mgpjv4"${add_attribute("value", seed, 0)}></div> <div class="input-group svelte-1mgpjv4"><label for="planetType" class="svelte-1mgpjv4" data-svelte-h="svelte-c877bm">Planet Type</label> <select id="planetType" class="svelte-1mgpjv4"><option value="random" data-svelte-h="svelte-15kmviv">random</option>${each(planetTypes, (pType) => {
    return `<option${add_attribute("value", pType, 0)}>${escape(pType)}</option>`;
  })}</select></div> <button class="svelte-1mgpjv4" data-svelte-h="svelte-1u7zbd5">Generate From Seed</button> <button class="svelte-1mgpjv4" data-svelte-h="svelte-192mxrq">Random Seed (and Generate)</button> <h2 class="svelte-1mgpjv4">${escape(planet.name)}</h2> <canvas id="render" class="svelte-1mgpjv4"></canvas> <p class="svelte-1mgpjv4">${escape(planet.description)}</p> <p class="svelte-1mgpjv4"><strong class="svelte-1mgpjv4" data-svelte-h="svelte-1x3lack">Planet Type:</strong> ${escape(planet.classification.name)}</p> <p class="svelte-1mgpjv4"><strong class="svelte-1mgpjv4" data-svelte-h="svelte-vxfh5n">Population:</strong> ${escape(planet.populationFriendly)}</p> <p class="svelte-1mgpjv4"><strong class="svelte-1mgpjv4" data-svelte-h="svelte-1per3yf">Government:</strong> ${escape(planet.government)}</p> <p class="svelte-1mgpjv4"><strong class="svelte-1mgpjv4" data-svelte-h="svelte-ywc3a4">Culture:</strong> ${escape(planet.culture)}</p> <p class="svelte-1mgpjv4"><strong class="svelte-1mgpjv4" data-svelte-h="svelte-1hjtszb">Distance from Star:</strong> ${escape(new Intl.NumberFormat().format(planet.distance_from_sun))} AU</p> <p class="svelte-1mgpjv4"><strong class="svelte-1mgpjv4" data-svelte-h="svelte-1dyh534">Mass:</strong> ${escape(new Intl.NumberFormat().format(planet.mass))} × 10<sup class="svelte-1mgpjv4" data-svelte-h="svelte-17ldsqy">24</sup> kg (${escape(new Intl.NumberFormat().format(Math.floor(planet.mass / 5.9722 * 100)))}% Earth&#39;s mass)</p> <p class="svelte-1mgpjv4"><strong class="svelte-1mgpjv4" data-svelte-h="svelte-151n5sv">Diameter:</strong> ${escape(new Intl.NumberFormat().format(Math.floor(planet.diameter)))} km (${escape(new Intl.NumberFormat().format(Math.floor(planet.diameter / 12756 * 100)))}% Earth&#39;s diameter)</p> <p class="svelte-1mgpjv4"><strong class="svelte-1mgpjv4" data-svelte-h="svelte-y44lrs">Gravity:</strong> ${escape(new Intl.NumberFormat().format(planet.gravity))} m/s<sup class="svelte-1mgpjv4" data-svelte-h="svelte-1nsjm82">2</sup>
    (${escape(new Intl.NumberFormat().format(Math.floor(planet.gravity / 9.81 * 100)))}% Earth&#39;s gravity)</p> <p class="svelte-1mgpjv4"><strong class="svelte-1mgpjv4" data-svelte-h="svelte-18c8r4q">Orbital Period:</strong> ${escape(new Intl.NumberFormat().format(Math.floor(planet.orbital_period)))} days</p> </section>`;
});
export {
  Page as default
};
//# sourceMappingURL=_page.svelte.js.map
