/**
 * Maintenance: reads powerlanguage word list, uses compromise for POS hints,
 * writes src/lib/languages/lexicon_powerlanguage_bucket_lists.ts
 *
 * Run: node scripts/generate_lexicon_frequency_buckets.mjs
 * Requires: npm install compromise
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import nlp from 'compromise';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const srcPath = path.join(root, 'src/lib/languages/data/powerlanguage_1000.txt');
const outPath = path.join(root, 'src/lib/languages/lexicon_powerlanguage_bucket_lists.ts');

const raw = fs.readFileSync(srcPath, 'utf8');
const lines = raw
  .split(/\n/)
  .map((s) => s.trim().toLowerCase())
  .filter(Boolean);

/** No standalone noun entry (function words, determiners, expletives, etc.). */
const notNoun = new Set([
  'a',
  'an',
  'the',
  'of',
  'to',
  'and',
  'in',
  'is',
  'it',
  'that',
  'he',
  'was',
  'for',
  'on',
  'are',
  'as',
  'at',
  'be',
  'or',
  'had',
  'by',
  'but',
  'some',
  'we',
  'can',
  'out',
  'other',
  'were',
  'there',
  'when',
  'up',
  'how',
  'each',
  'their',
  'if',
  'will',
  'would',
  'like',
  'so',
  'these',
  'her',
  'has',
  'this',
  'them',
  'my',
  'than',
  'any',
  'every',
  'no',
  'most',
  'such',
  'then',
  'under',
  'while',
  'may',
  'also',
  'only',
  'over',
  'even',
  'must',
  'should',
  'might',
  'both',
  'few',
  'those',
  'during',
  'though',
  'against',
  'ever',
  'from',
  'off',
  'again',
  'not',
  'into',
  'through',
  'because',
  'either',
  'nor',
  'yet',
  'once',
  'twice',
  'perhaps',
  'thus',
  'whether',
  'quite',
  'else',
  'ago',
  'yes',
  'oh',
  'am',
  'shall',
  'could',
]);

const forcePronoun = new Set([
  'i',
  'you',
  'he',
  'she',
  'it',
  'we',
  'they',
  'me',
  'him',
  'her',
  'us',
  'them',
  'my',
  'your',
  'his',
  'its',
  'our',
  'their',
  'mine',
  'yours',
  'hers',
  'ours',
  'theirs',
  'myself',
  'yourself',
  'himself',
  'herself',
  'itself',
  'ourselves',
  'yourselves',
  'themselves',
  'who',
  'whom',
  'whose',
]);

function tagsFor(w) {
  const doc = nlp(w);
  return doc.json()[0]?.terms?.[0]?.tags ?? [];
}

const buckets = new Map([
  ['article', new Set()],
  ['noun', new Set()],
  ['verb', new Set()],
  ['adjective', new Set()],
  ['adverb', new Set()],
  ['preposition', new Set()],
  ['pronoun', new Set()],
  ['question', new Set()],
  ['number', new Set()],
  ['interjection', new Set()],
]);

function add(part, w) {
  buckets.get(part)?.add(w);
}

for (const w of lines) {
  if (!/^[a-z]+$/.test(w)) {
    continue;
  }

  const tags = tagsFor(w);

  if (tags.includes('QuestionWord')) {
    add('question', w);
  }
  if (tags.includes('Expression')) {
    add('interjection', w);
  }
  if (tags.includes('Cardinal') || tags.includes('Ordinal') || tags.includes('Multiple')) {
    add('number', w);
  }
  if (tags.includes('Preposition')) {
    add('preposition', w);
  }
  if (tags.includes('Conjunction')) {
    add('preposition', w);
  }
  if (tags.includes('Adverb')) {
    add('adverb', w);
  }
  if (tags.includes('Adjective')) {
    add('adjective', w);
  }

  if (tags.includes('Pronoun') || forcePronoun.has(w)) {
    add('pronoun', w);
  }

  if (tags.includes('Possessive') && ['my', 'your', 'his', 'its', 'our', 'their'].includes(w)) {
    add('pronoun', w);
  }

  const isModal = tags.includes('Modal');
  if (tags.includes('Verb') && !isModal) {
    add('verb', w);
  }

  if (!notNoun.has(w)) {
    add('noun', w);
  }
}

for (const art of ['a', 'an', 'the']) {
  if (lines.includes(art)) {
    add('article', art);
  }
}

const orderedParts = [
  'article',
  'adjective',
  'adverb',
  'preposition',
  'pronoun',
  'question',
  'verb',
  'noun',
  'number',
  'interjection',
];

function toTsArray(name, values) {
  const body = values.map((s) => JSON.stringify(s)).join(',\n  ');
  return `export const ${name} = [\n  ${body},\n] as const;\n`;
}

let out = `/** Generated by scripts/generate_lexicon_frequency_buckets.mjs — do not edit by hand. */\n\n`;

for (const part of orderedParts) {
  const values = [...(buckets.get(part) ?? [])].sort((a, b) => a.localeCompare(b));
  const constName = `POWERLANGUAGE_${part.toUpperCase()}S`;
  out += toTsArray(constName, values);
  out += '\n';
}

const alphaSorted = [...new Set(lines.filter((w) => /^[a-z]+$/.test(w)))].sort((a, b) =>
  a.localeCompare(b),
);
out += toTsArray('POWERLANGUAGE_ALPHABETIC', alphaSorted);

fs.writeFileSync(outPath, out, 'utf8');
console.log(
  'wrote',
  outPath,
  'sizes:',
  Object.fromEntries([...buckets.entries()].map(([k, v]) => [k, v.size])),
);
