"use strict";

import type AppearanceTrait from "$lib/appearance/trait.js";
import * as AppearanceTraits from "$lib/appearance/traits.js";
import type RealmConcept from "./realms/realmconcept.js";

export const allTraits = [
  AppearanceTraits.newTrait("six feathered wings", "wings", ["sky"]),
  AppearanceTraits.newTrait("four feathered wings", "wings", ["sky"]),
  AppearanceTraits.newTrait("two large feathered wings", "wings", ["sky", "dreamlike"]),
  AppearanceTraits.newTrait("large leathery wings", "wings", ["sky", "death"]),
  AppearanceTraits.newTrait("a lion's tail'", "tail", ["earth", "forest"]),
  AppearanceTraits.newTrait("a whip-like tail", "tail", ["earth", "death"]),
  AppearanceTraits.newTrait("two tails", "tail", ["alien"]),
  AppearanceTraits.newTrait("the horns of a goat", "horns", ["earth", "forest"]),
  AppearanceTraits.newTrait("the horns of a ram", "horns", ["earth", "forest"]),
  AppearanceTraits.newTrait("the antlers of a stag", "horns", ["forest"]),
  AppearanceTraits.newTrait("the antlers of a deer", "horns", ["forest", "surreal"]),
  AppearanceTraits.newTrait("short, pointed horns", "horns", ["earth", "death"]),
  AppearanceTraits.newTrait("tall, straight horns", "horns", ["earth", "death"]),
  AppearanceTraits.newTrait("glowing blue eyes", "eyes", ["water"]),
  AppearanceTraits.newTrait("glowing yellow eyes", "eyes", ["sky", "water"]),
  AppearanceTraits.newTrait("glowing red eyes", "eyes", ["earth", "death", "alien"]),
  AppearanceTraits.newTrait("glowing orange eyes", "eyes", ["earth", "sky"]),
  AppearanceTraits.newTrait("glowing green eyes", "eyes", ["earth", "forest"]),
  AppearanceTraits.newTrait("glowing purple eyes", "eyes", ["death", "alien"]),
  AppearanceTraits.newTrait("eyes that burn with an inner fire", "eyes", ["sky"]),
  AppearanceTraits.newTrait("four eyes", "eyes", ["alien"]),
  AppearanceTraits.newTrait("six eyes", "eyes", ["alien"]),
  AppearanceTraits.newTrait("eight eyes", "eyes", ["alien"]),
  AppearanceTraits.newTrait("no eyes", "eyes", ["death", "alien"]),
  AppearanceTraits.newTrait("reptilian eyes", "eyes", ["forest", "earth"]),
  AppearanceTraits.newTrait("scales instead of skin", "skin", ["earth", "forest"]),
  AppearanceTraits.newTrait("skin that glows faintly", "skin", ["sky"]),
  AppearanceTraits.newTrait("skin made of living rock", "skin", ["earth"]),
  AppearanceTraits.newTrait("blue skin", "skin", ["water"]),
  AppearanceTraits.newTrait("green skin", "skin", ["water"]),
  AppearanceTraits.newTrait("crystalline skin", "skin", ["earth"]),
  AppearanceTraits.newTrait("translucent grey skin", "skin", ["death"]),
  AppearanceTraits.newTrait("dull grey skin", "skin", ["death"]),
  AppearanceTraits.newTrait("skin covered in leaves", "skin", ["forest"]),
  AppearanceTraits.newTrait("skin made of star-lit blackness", "skin", ["alien"]),
  AppearanceTraits.newTrait("iridescent skin", "skin", ["alien", "surreal"]),
  AppearanceTraits.newTrait("eight tentacles", "tentacles", ["alien"]),
  AppearanceTraits.newTrait("six tentacles", "tentacles", ["alien"]),
  AppearanceTraits.newTrait("four tentacles", "tentacles", ["alien"]),
  AppearanceTraits.newTrait("the head of a lion", "head", ["forest"]),
  AppearanceTraits.newTrait("the head of a bear", "head", ["forest"]),
  AppearanceTraits.newTrait("the head of a dragon", "head", ["earth", "forest"]),
  AppearanceTraits.newTrait("the head of a swan", "head", ["sky", "water"]),
  AppearanceTraits.newTrait("the head of a deer", "head", ["forest"]),
  AppearanceTraits.newTrait("the head of a cat", "head", ["earth", "desert"]),
  AppearanceTraits.newTrait("the head of a wolf", "head", ["earth", "forest"]),
  AppearanceTraits.newTrait("twelve feathered wings", "wings", ["sky", "dreamlike"]),
  AppearanceTraits.newTrait("bat-like wings", "wings", ["night", "moon"]),
  AppearanceTraits.newTrait("insect-like wings", "wings", ["earth", "forest"]),
  AppearanceTraits.newTrait("crystal-clear wings", "wings", ["sky", "surreal"]),
  AppearanceTraits.newTrait("feathered wings that shimmer", "wings", ["sky", "water"]),
  AppearanceTraits.newTrait("a serpent's tail", "tail", ["earth", "water"]),
  AppearanceTraits.newTrait("a tail with a bioluminescent tip", "tail", ["water", "surreal"]),
  AppearanceTraits.newTrait("three tails", "tail", ["surreal"]),
  AppearanceTraits.newTrait("twisted horns with glowing runes", "horns", ["magic", "surreal"]),
  AppearanceTraits.newTrait("curved horns with gemstone inlays", "horns", ["earth", "wealth"]),
  AppearanceTraits.newTrait("feathery antlers with ethereal wisps", "horns", ["forest", "dreamlike"]),
  AppearanceTraits.newTrait("horns that emit a haunting melody", "horns", ["earth", "music"]),
  AppearanceTraits.newTrait("pearlescent eyes that change colors", "eyes", ["sky", "water"]),
  AppearanceTraits.newTrait("eyes with galaxies swirling within", "eyes", ["sky", "cosmic"]),
  AppearanceTraits.newTrait("eyes that see into other dimensions", "eyes", ["surreal", "alien"]),
  AppearanceTraits.newTrait("eyes with a mesmerizing hypnotic gaze", "eyes", ["magic", "surreal"]),
  AppearanceTraits.newTrait("eyes that mirror the emotions of others", "eyes", ["empathy", "surreal"]),
  AppearanceTraits.newTrait("eyes that emit sparks of lightning", "eyes", ["storm", "electricity"]),
  AppearanceTraits.newTrait("eyes on flexible stalks", "eyes", ["alien", "surreal"]),
  AppearanceTraits.newTrait("molten lava-like skin", "skin", ["volcano", "fire"]),
  AppearanceTraits.newTrait("shimmering opalescent skin", "skin", ["sky", "water"]),
  AppearanceTraits.newTrait("butterfly wings with shifting patterns", "wings", ["dream", "surreal"]),
  AppearanceTraits.newTrait("floating ethereal wings of light", "wings", ["dream", "surreal"]),
  AppearanceTraits.newTrait("wings made of iridescent mist", "wings", ["dream", "surreal"]),
  AppearanceTraits.newTrait("feathers that change color with emotions", "wings", ["dream", "empathy"]),
  AppearanceTraits.newTrait("a tail of shimmering stardust", "tail", ["dream", "cosmic"]),
  AppearanceTraits.newTrait("tail that trails rainbows as you move", "tail", ["dream", "surreal"]),
  AppearanceTraits.newTrait("a tail with glowing constellations", "tail", ["dream", "cosmic"]),
  AppearanceTraits.newTrait("horns that emit soft, soothing melodies", "horns", ["dream", "music"]),
  AppearanceTraits.newTrait("horns adorned with floating gemstones", "horns", ["dream", "surreal"]),
  AppearanceTraits.newTrait("horns that sparkle like starlight", "horns", ["dream", "cosmic"]),
  AppearanceTraits.newTrait("eyes that reflect the landscapes of dreams", "eyes", ["dream", "surreal"]),
  AppearanceTraits.newTrait("eyes with ever-changing patterns of light", "eyes", ["dream", "surreal"]),
  AppearanceTraits.newTrait("eyes that shimmer like enchanted pools", "eyes", ["dream", "water"]),
  AppearanceTraits.newTrait("skin that shifts like flowing watercolors", "skin", ["dream", "surreal"]),
  AppearanceTraits.newTrait("skin that glows softly with inner thoughts", "skin", ["dream", "empathy"]),
  AppearanceTraits.newTrait("skin covered in delicate, luminescent vines", "skin", ["dream", "forest"]),
  AppearanceTraits.newTrait("skin that shimmers like a mirage", "skin", ["dream", "desert"]),
  AppearanceTraits.newTrait("skin that resembles the surface of a nebula", "skin", ["dream", "cosmic"]),
  AppearanceTraits.newTrait("skin that changes texture with emotions", "skin", ["dream", "empathy"]),
  AppearanceTraits.newTrait("a head crowned with floating ethereal flames", "head", ["dream", "fire"]),
  AppearanceTraits.newTrait("a head with a halo of radiant energy", "head", ["dream", "surreal"]),
  AppearanceTraits.newTrait("fiery wings with ember-like feathers", "wings", ["fire", "heat"]),
  AppearanceTraits.newTrait("wings that resemble molten lava flows", "wings", ["fire", "earth"]),
  AppearanceTraits.newTrait("smoldering wings that leave trails of sparks", "wings", ["fire", "surreal"]),
  AppearanceTraits.newTrait("earthen wings with intricate rock formations", "wings", ["earth", "mountain"]),
  AppearanceTraits.newTrait("wings made of intertwined vines and roots", "wings", ["earth", "forest"]),
  AppearanceTraits.newTrait("crystalline wings that shimmer like gemstones", "wings", ["earth", "jewel"]),
  AppearanceTraits.newTrait("a tail with a fiery, flickering tip", "tail", ["fire", "surreal"]),
  AppearanceTraits.newTrait("tail adorned with rugged, earthy textures", "tail", ["earth", "mountain"]),
  AppearanceTraits.newTrait("tail with geode-like patterns and colors", "tail", ["earth", "jewel"]),
  AppearanceTraits.newTrait("horns that resemble twisting flames", "horns", ["fire", "heat"]),
  AppearanceTraits.newTrait("horns made of sturdy, petrified wood", "horns", ["earth", "forest"]),
  AppearanceTraits.newTrait("horns with patterns reminiscent of ancient runes", "horns", ["earth", "magic"]),
  AppearanceTraits.newTrait("eyes that flicker like burning embers", "eyes", ["fire", "heat"]),
  AppearanceTraits.newTrait("eyes with deep, earthy hues like rich soil", "eyes", ["earth", "nature"]),
  AppearanceTraits.newTrait("eyes that reflect the molten core of the earth", "eyes", ["earth", "cosmic"]),
  AppearanceTraits.newTrait("skin that glows with inner fire", "skin", ["fire", "surreal"]),
  AppearanceTraits.newTrait("skin with a texture resembling cracked earth", "skin", ["earth", "desert"]),
  AppearanceTraits.newTrait("skin covered in intricate, glowing tribal patterns", "skin", ["earth", "magic"]),
  AppearanceTraits.newTrait("a head crowned with blazing, fiery tendrils", "head", ["fire", "surreal"]),
  AppearanceTraits.newTrait("a head with rugged, stone-like features", "head", ["earth", "mountain"]),
  AppearanceTraits.newTrait("a head adorned with gemstone-encrusted horns", "head", ["earth", "jewel"]),
];

export function byRealmConcept(concept: RealmConcept): AppearanceTrait[] {
  return AppearanceTraits.byAnyTag(allTraits, concept.appearanceTags);
}
